// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

/** Environment-scoped settings, with workspace-level defaults. Note that we use MergeFrom to combine workspace / environment settings, which will *append* any `repeated` fields! */
export interface EnvironmentSettings {
  imageBuilderVersion?: string;
  webhookSuffix?: string;
  maxConcurrentGpus?: number;
  maxConcurrentTasks?: number;
}
export const EnvironmentSettings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageBuilderVersion: S.optional(S.String),
    webhookSuffix: S.optional(S.String),
    maxConcurrentGpus: S.optional(S.Number),
    maxConcurrentTasks: S.optional(S.Number),
  }),
).annotate({
  identifier: "EnvironmentSettings",
}) as any as S.Schema<EnvironmentSettings>;

/** Creation-time environment classification. Captures whether an environment is public. is_managed and machine_generated may be folded in as future values. */
export type EnvironmentType =
  | "ENVIRONMENT_TYPE_UNSPECIFIED"
  | "ENVIRONMENT_TYPE_PUBLIC";
export const EnvironmentType = S.String;

export type EnvironmentRole =
  | "ENVIRONMENT_ROLE_UNSPECIFIED"
  | "ENVIRONMENT_ROLE_VIEWER"
  | "ENVIRONMENT_ROLE_CONTRIBUTOR"
  | "ENVIRONMENT_ROLE_NO_ACCESS";
export const EnvironmentRole = S.String;

export interface CreateEnvironmentRequest {
  name?: string;
  isManaged?: boolean;
  settings?: EnvironmentSettings;
  environmentType?: EnvironmentType | (string & {});
  defaultMemberRole?: EnvironmentRole | (string & {});
  defaultMemberRoleStr?: string;
}
export const CreateEnvironmentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    isManaged: S.optional(S.Boolean),
    settings: S.optional(EnvironmentSettings),
    environmentType: S.optional(EnvironmentType),
    defaultMemberRole: S.optional(EnvironmentRole),
    defaultMemberRoleStr: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateEnvironmentRequest",
}) as any as S.Schema<CreateEnvironmentRequest>;

export interface CreateEnvironmentResponse {}
export const CreateEnvironmentResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreateEnvironmentResponse",
}) as any as S.Schema<CreateEnvironmentResponse>;

export interface DeleteEnvironmentRequest {
  name?: string;
}
export const DeleteEnvironmentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentDelete",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteEnvironmentRequest",
}) as any as S.Schema<DeleteEnvironmentRequest>;

export interface DeleteEnvironmentResponse {}
export const DeleteEnvironmentResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteEnvironmentResponse",
}) as any as S.Schema<DeleteEnvironmentResponse>;

export interface EnvironmentBillingSummaryRequest {
  /** all query intervals are implicitly one month long (to line up with billing cycles) */
  startTimestamp?: string;
  environmentId?: string;
}
export const EnvironmentBillingSummaryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    startTimestamp: S.optional(S.String),
    environmentId: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentBillingSummary",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentBillingSummaryRequest",
}) as any as S.Schema<EnvironmentBillingSummaryRequest>;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface EnvironmentBillingSummaryResponse {
  startTimestamp?: string;
  endTimestamp?: string;
  /** not showing credits, reservations, etc as those are applied at the workspace level */
  meteredCost?: string;
  /** keyed by deployed, ephemeral, volume, notebook */
  meteredCostBreakdown?: StringMap;
}
export const EnvironmentBillingSummaryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    startTimestamp: S.optional(S.String),
    endTimestamp: S.optional(S.String),
    meteredCost: S.optional(S.String),
    meteredCostBreakdown: S.optional(StringMap),
  }),
).annotate({
  identifier: "EnvironmentBillingSummaryResponse",
}) as any as S.Schema<EnvironmentBillingSummaryResponse>;

export interface EnvironmentGetBudgetRequest {
  environmentId?: string;
}
export const EnvironmentGetBudgetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentGetBudget",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentGetBudgetRequest",
}) as any as S.Schema<EnvironmentGetBudgetRequest>;

export interface EnvironmentGetBudgetResponse {
  cycleBudgetDollars?: number;
  effectiveCycleSpendLimit?: number;
  currentCycleUsage?: number;
  spendLimitReached?: boolean;
}
export const EnvironmentGetBudgetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cycleBudgetDollars: S.optional(S.Number),
    effectiveCycleSpendLimit: S.optional(S.Number),
    currentCycleUsage: S.optional(S.Number),
    spendLimitReached: S.optional(S.Boolean),
  }),
).annotate({
  identifier: "EnvironmentGetBudgetResponse",
}) as any as S.Schema<EnvironmentGetBudgetResponse>;

export interface EnvironmentGetManagedRequest {
  environmentId?: string;
}
export const EnvironmentGetManagedRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentGetManaged",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentGetManagedRequest",
}) as any as S.Schema<EnvironmentGetManagedRequest>;

export type MemberRole =
  | "MEMBER_ROLE_UNSPECIFIED"
  | "MEMBER_ROLE_USER"
  | "MEMBER_ROLE_MANAGER"
  | "MEMBER_ROLE_OWNER";
export const MemberRole = S.String;

export interface EnvironmentGetManagedResponsePrincipalEnvRole {
  userId?: string;
  serviceUserId?: string;
  email?: string;
  avatarUrl?: string;
  serviceUserName?: string;
  role?: EnvironmentRole;
  memberRole?: MemberRole;
  userName?: string;
}
export const EnvironmentGetManagedResponsePrincipalEnvRole =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      userId: S.optional(S.String),
      serviceUserId: S.optional(S.String),
      email: S.optional(S.String),
      avatarUrl: S.optional(S.String),
      serviceUserName: S.optional(S.String),
      role: S.optional(EnvironmentRole),
      memberRole: S.optional(MemberRole),
      userName: S.optional(S.String),
    }),
  ).annotate({
    identifier: "EnvironmentGetManagedResponsePrincipalEnvRole",
  }) as any as S.Schema<EnvironmentGetManagedResponsePrincipalEnvRole>;

export type EnvironmentGetManagedResponsePrincipalEnvRoleList =
  Array<EnvironmentGetManagedResponsePrincipalEnvRole>;
export const EnvironmentGetManagedResponsePrincipalEnvRoleList =
  /*@__PURE__*/ S.Array(
    EnvironmentGetManagedResponsePrincipalEnvRole,
  ) as any as S.Schema<EnvironmentGetManagedResponsePrincipalEnvRoleList>;

export interface EnvironmentGetManagedResponse {
  environmentId?: string;
  name?: string;
  createdAt?: number;
  principalRoles?: EnvironmentGetManagedResponsePrincipalEnvRoleList;
  additionalRoles?: EnvironmentGetManagedResponsePrincipalEnvRoleList;
}
export const EnvironmentGetManagedResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
    name: S.optional(S.String),
    createdAt: S.optional(S.Number),
    principalRoles: S.optional(
      EnvironmentGetManagedResponsePrincipalEnvRoleList,
    ),
    additionalRoles: S.optional(
      EnvironmentGetManagedResponsePrincipalEnvRoleList,
    ),
  }),
).annotate({
  identifier: "EnvironmentGetManagedResponse",
}) as any as S.Schema<EnvironmentGetManagedResponse>;

export type ObjectCreationType =
  | "OBJECT_CREATION_TYPE_UNSPECIFIED"
  | "OBJECT_CREATION_TYPE_CREATE_IF_MISSING"
  | "OBJECT_CREATION_TYPE_CREATE_FAIL_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_CREATE_OVERWRITE_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP"
  | "OBJECT_CREATION_TYPE_EPHEMERAL";
export const ObjectCreationType = S.String;

export interface EnvironmentGetOrCreateRequest {
  deploymentName?: string;
  objectCreationType?: ObjectCreationType | (string & {});
}
export const EnvironmentGetOrCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deploymentName: S.optional(S.String),
    objectCreationType: S.optional(ObjectCreationType),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentGetOrCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentGetOrCreateRequest",
}) as any as S.Schema<EnvironmentGetOrCreateRequest>;

export interface EnvironmentMetadata {
  name?: string;
  settings?: EnvironmentSettings;
  environmentType?: EnvironmentType;
}
export const EnvironmentMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    settings: S.optional(EnvironmentSettings),
    environmentType: S.optional(EnvironmentType),
  }),
).annotate({
  identifier: "EnvironmentMetadata",
}) as any as S.Schema<EnvironmentMetadata>;

export interface EnvironmentGetOrCreateResponse {
  environmentId?: string;
  metadata?: EnvironmentMetadata;
}
export const EnvironmentGetOrCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
    metadata: S.optional(EnvironmentMetadata),
  }),
).annotate({
  identifier: "EnvironmentGetOrCreateResponse",
}) as any as S.Schema<EnvironmentGetOrCreateResponse>;

export interface EnvironmentGetRolesRequest {
  environmentId?: string;
}
export const EnvironmentGetRolesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentGetRoles",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentGetRolesRequest",
}) as any as S.Schema<EnvironmentGetRolesRequest>;

export type EnvironmentRoleList = Array<EnvironmentRole>;
export const EnvironmentRoleList = /*@__PURE__*/ S.Array(
  EnvironmentRole,
) as any as S.Schema<EnvironmentRoleList>;

export interface EnvironmentGetRolesResponsePrincipal {
  userId?: string;
  serviceUserId?: string;
  email?: string;
  avatarUrl?: string;
  userName?: string;
  serviceUserName?: string;
  role?: EnvironmentRole;
  roleStr?: string;
  /** String representation for the CLI */
  choosableRoles?: EnvironmentRoleList;
  memberRole?: MemberRole;
  inheritsDefaultMemberRole?: boolean;
  hasRoleAssignment?: boolean;
}
export const EnvironmentGetRolesResponsePrincipal = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      userId: S.optional(S.String),
      serviceUserId: S.optional(S.String),
      email: S.optional(S.String),
      avatarUrl: S.optional(S.String),
      userName: S.optional(S.String),
      serviceUserName: S.optional(S.String),
      role: S.optional(EnvironmentRole),
      roleStr: S.optional(S.String),
      choosableRoles: S.optional(EnvironmentRoleList),
      memberRole: S.optional(MemberRole),
      inheritsDefaultMemberRole: S.optional(S.Boolean),
      hasRoleAssignment: S.optional(S.Boolean),
    }),
).annotate({
  identifier: "EnvironmentGetRolesResponsePrincipal",
}) as any as S.Schema<EnvironmentGetRolesResponsePrincipal>;

export type EnvironmentGetRolesResponsePrincipalList =
  Array<EnvironmentGetRolesResponsePrincipal>;
export const EnvironmentGetRolesResponsePrincipalList = /*@__PURE__*/ S.Array(
  EnvironmentGetRolesResponsePrincipal,
) as any as S.Schema<EnvironmentGetRolesResponsePrincipalList>;

export interface EnvironmentGetRolesResponse {
  name?: string;
  createdAt?: number;
  principalRoles?: EnvironmentGetRolesResponsePrincipalList;
  defaultMemberRole?: EnvironmentRole;
}
export const EnvironmentGetRolesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    createdAt: S.optional(S.Number),
    principalRoles: S.optional(EnvironmentGetRolesResponsePrincipalList),
    defaultMemberRole: S.optional(EnvironmentRole),
  }),
).annotate({
  identifier: "EnvironmentGetRolesResponse",
}) as any as S.Schema<EnvironmentGetRolesResponse>;

export interface EnvironmentSetBudgetRequest {
  environmentId?: string;
  cycleBudgetDollars?: number;
  clearBudget?: boolean;
}
export const EnvironmentSetBudgetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
    cycleBudgetDollars: S.optional(S.Number),
    clearBudget: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentSetBudget",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentSetBudgetRequest",
}) as any as S.Schema<EnvironmentSetBudgetRequest>;

export interface EnvironmentSetBudgetResponse {}
export const EnvironmentSetBudgetResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "EnvironmentSetBudgetResponse",
}) as any as S.Schema<EnvironmentSetBudgetResponse>;

export interface EnvironmentSetDefaultMemberRoleRequest {
  environmentId?: string;
  defaultMemberRole?: EnvironmentRole | (string & {});
}
export const EnvironmentSetDefaultMemberRoleRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      environmentId: S.optional(S.String),
      defaultMemberRole: S.optional(EnvironmentRole),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/modal.client.ModalClient/EnvironmentSetDefaultMemberRole",
        code: 200,
      }),
    ),
).annotate({
  identifier: "EnvironmentSetDefaultMemberRoleRequest",
}) as any as S.Schema<EnvironmentSetDefaultMemberRoleRequest>;

export interface EnvironmentSetDefaultMemberRoleResponse {}
export const EnvironmentSetDefaultMemberRoleResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "EnvironmentSetDefaultMemberRoleResponse",
}) as any as S.Schema<EnvironmentSetDefaultMemberRoleResponse>;

export interface EnvironmentSetManagedRequest {
  environmentId?: string;
  managed?: boolean;
  defaultMemberRole?: EnvironmentRole | (string & {});
}
export const EnvironmentSetManagedRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
    managed: S.optional(S.Boolean),
    defaultMemberRole: S.optional(EnvironmentRole),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentSetManaged",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EnvironmentSetManagedRequest",
}) as any as S.Schema<EnvironmentSetManagedRequest>;

export interface EnvironmentSetManagedResponse {}
export const EnvironmentSetManagedResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "EnvironmentSetManagedResponse",
}) as any as S.Schema<EnvironmentSetManagedResponse>;

export interface ListEnvironmentRequest {}
export const ListEnvironmentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListEnvironmentRequest",
}) as any as S.Schema<ListEnvironmentRequest>;

export interface EnvironmentListItem {
  name?: string;
  webhookSuffix?: string;
  createdAt?: number;
  default?: boolean;
  isManaged?: boolean;
  environmentId?: string;
  maxConcurrentTasks?: number;
  maxConcurrentGpus?: number;
  currentConcurrentTasks?: number;
  currentConcurrentGpus?: number;
  cycleBudgetDollars?: number;
  /** manager-set */
  effectiveCycleSpendLimit?: number;
  currentCycleUsage?: number;
  spendLimitReached?: boolean;
  environmentType?: EnvironmentType;
  defaultMemberRole?: EnvironmentRole;
}
export const EnvironmentListItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    webhookSuffix: S.optional(S.String),
    createdAt: S.optional(S.Number),
    default: S.optional(S.Boolean),
    isManaged: S.optional(S.Boolean),
    environmentId: S.optional(S.String),
    maxConcurrentTasks: S.optional(S.Number),
    maxConcurrentGpus: S.optional(S.Number),
    currentConcurrentTasks: S.optional(S.Number),
    currentConcurrentGpus: S.optional(S.Number),
    cycleBudgetDollars: S.optional(S.Number),
    effectiveCycleSpendLimit: S.optional(S.Number),
    currentCycleUsage: S.optional(S.Number),
    spendLimitReached: S.optional(S.Boolean),
    environmentType: S.optional(EnvironmentType),
    defaultMemberRole: S.optional(EnvironmentRole),
  }),
).annotate({
  identifier: "EnvironmentListItem",
}) as any as S.Schema<EnvironmentListItem>;

export type EnvironmentListItemList = Array<EnvironmentListItem>;
export const EnvironmentListItemList = /*@__PURE__*/ S.Array(
  EnvironmentListItem,
) as any as S.Schema<EnvironmentListItemList>;

export interface ListEnvironmentResponse {
  items?: EnvironmentListItemList;
}
export const ListEnvironmentResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(EnvironmentListItemList),
  }),
).annotate({
  identifier: "ListEnvironmentResponse",
}) as any as S.Schema<ListEnvironmentResponse>;

export interface SetEnvironmentRoleRequest {
  environmentId?: string;
  userId?: string;
  serviceUserId?: string;
  role?: EnvironmentRole | (string & {});
  roleStr?: string;
}
export const SetEnvironmentRoleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentId: S.optional(S.String),
    userId: S.optional(S.String),
    serviceUserId: S.optional(S.String),
    role: S.optional(EnvironmentRole),
    roleStr: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentRoleSet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SetEnvironmentRoleRequest",
}) as any as S.Schema<SetEnvironmentRoleRequest>;

export interface SetEnvironmentRoleResponse {}
export const SetEnvironmentRoleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "SetEnvironmentRoleResponse",
}) as any as S.Schema<SetEnvironmentRoleResponse>;

export interface UpdateEnvironmentRequest {
  currentName?: string;
  name?: string;
  webSuffix?: string;
  maxConcurrentTasks?: number;
  maxConcurrentGpus?: number;
}
export const UpdateEnvironmentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    currentName: S.optional(S.String),
    name: S.optional(S.String),
    webSuffix: S.optional(S.String),
    maxConcurrentTasks: S.optional(S.Number),
    maxConcurrentGpus: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EnvironmentUpdate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateEnvironmentRequest",
}) as any as S.Schema<UpdateEnvironmentRequest>;

export interface UpdateEnvironmentResponse {
  name?: string;
  webhookSuffix?: string;
  createdAt?: number;
  default?: boolean;
  isManaged?: boolean;
  environmentId?: string;
  maxConcurrentTasks?: number;
  maxConcurrentGpus?: number;
  currentConcurrentTasks?: number;
  currentConcurrentGpus?: number;
  cycleBudgetDollars?: number;
  /** manager-set */
  effectiveCycleSpendLimit?: number;
  currentCycleUsage?: number;
  spendLimitReached?: boolean;
  environmentType?: EnvironmentType;
  defaultMemberRole?: EnvironmentRole;
}
export const UpdateEnvironmentResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    webhookSuffix: S.optional(S.String),
    createdAt: S.optional(S.Number),
    default: S.optional(S.Boolean),
    isManaged: S.optional(S.Boolean),
    environmentId: S.optional(S.String),
    maxConcurrentTasks: S.optional(S.Number),
    maxConcurrentGpus: S.optional(S.Number),
    currentConcurrentTasks: S.optional(S.Number),
    currentConcurrentGpus: S.optional(S.Number),
    cycleBudgetDollars: S.optional(S.Number),
    effectiveCycleSpendLimit: S.optional(S.Number),
    currentCycleUsage: S.optional(S.Number),
    spendLimitReached: S.optional(S.Boolean),
    environmentType: S.optional(EnvironmentType),
    defaultMemberRole: S.optional(EnvironmentRole),
  }),
).annotate({
  identifier: "UpdateEnvironmentResponse",
}) as any as S.Schema<UpdateEnvironmentResponse>;

export type CreateEnvironmentError = ModalOpError;
export const createEnvironment: API.OperationMethod<
  CreateEnvironmentRequest,
  CreateEnvironmentResponse,
  CreateEnvironmentError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateEnvironmentRequest,
  output: CreateEnvironmentResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type DeleteEnvironmentError = ModalOpError;
export const deleteEnvironment: API.OperationMethod<
  DeleteEnvironmentRequest,
  DeleteEnvironmentResponse,
  DeleteEnvironmentError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteEnvironmentRequest,
  output: DeleteEnvironmentResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentBillingSummaryError = ModalOpError;
/** Environments */
export const environmentBillingSummary: API.OperationMethod<
  EnvironmentBillingSummaryRequest,
  EnvironmentBillingSummaryResponse,
  EnvironmentBillingSummaryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentBillingSummaryRequest,
  output: EnvironmentBillingSummaryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentGetBudgetError = ModalOpError;
export const environmentGetBudget: API.OperationMethod<
  EnvironmentGetBudgetRequest,
  EnvironmentGetBudgetResponse,
  EnvironmentGetBudgetError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentGetBudgetRequest,
  output: EnvironmentGetBudgetResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentGetManagedError = ModalOpError;
export const environmentGetManaged: API.OperationMethod<
  EnvironmentGetManagedRequest,
  EnvironmentGetManagedResponse,
  EnvironmentGetManagedError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentGetManagedRequest,
  output: EnvironmentGetManagedResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentGetOrCreateError = ModalOpError;
export const environmentGetOrCreate: API.OperationMethod<
  EnvironmentGetOrCreateRequest,
  EnvironmentGetOrCreateResponse,
  EnvironmentGetOrCreateError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentGetOrCreateRequest,
  output: EnvironmentGetOrCreateResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentGetRolesError = ModalOpError;
export const environmentGetRoles: API.OperationMethod<
  EnvironmentGetRolesRequest,
  EnvironmentGetRolesResponse,
  EnvironmentGetRolesError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentGetRolesRequest,
  output: EnvironmentGetRolesResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentSetBudgetError = ModalOpError;
export const environmentSetBudget: API.OperationMethod<
  EnvironmentSetBudgetRequest,
  EnvironmentSetBudgetResponse,
  EnvironmentSetBudgetError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentSetBudgetRequest,
  output: EnvironmentSetBudgetResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentSetDefaultMemberRoleError = ModalOpError;
export const environmentSetDefaultMemberRole: API.OperationMethod<
  EnvironmentSetDefaultMemberRoleRequest,
  EnvironmentSetDefaultMemberRoleResponse,
  EnvironmentSetDefaultMemberRoleError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentSetDefaultMemberRoleRequest,
  output: EnvironmentSetDefaultMemberRoleResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EnvironmentSetManagedError = ModalOpError;
export const environmentSetManaged: API.OperationMethod<
  EnvironmentSetManagedRequest,
  EnvironmentSetManagedResponse,
  EnvironmentSetManagedError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnvironmentSetManagedRequest,
  output: EnvironmentSetManagedResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListEnvironmentError = ModalOpError;
export const listEnvironment: API.OperationMethod<
  ListEnvironmentRequest,
  ListEnvironmentResponse,
  ListEnvironmentError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEnvironmentRequest,
  output: ListEnvironmentResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type SetEnvironmentRoleError = ModalOpError;
export const setEnvironmentRole: API.OperationMethod<
  SetEnvironmentRoleRequest,
  SetEnvironmentRoleResponse,
  SetEnvironmentRoleError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SetEnvironmentRoleRequest,
  output: SetEnvironmentRoleResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type UpdateEnvironmentError = ModalOpError;
export const updateEnvironment: API.OperationMethod<
  UpdateEnvironmentRequest,
  UpdateEnvironmentResponse,
  UpdateEnvironmentError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateEnvironmentRequest,
  output: UpdateEnvironmentResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
