// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface FlashContainerDeregisterRequest {
  serviceName?: string;
}
export const FlashContainerDeregisterRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/FlashContainerDeregister",
      code: 200,
    }),
  ),
).annotate({
  identifier: "FlashContainerDeregisterRequest",
}) as any as S.Schema<FlashContainerDeregisterRequest>;

export interface FlashContainerDeregisterResponse {}
export const FlashContainerDeregisterResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "FlashContainerDeregisterResponse",
}) as any as S.Schema<FlashContainerDeregisterResponse>;

export interface FlashSetTargetSlotsMetricsRequest {
  /** TODO(claudia): add other metrics to use in autoscaling decisions */
  functionId?: string;
  targetSlots?: number;
}
export const FlashSetTargetSlotsMetricsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionId: S.optional(S.String),
    targetSlots: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/FlashSetTargetSlotsMetrics",
      code: 200,
    }),
  ),
).annotate({
  identifier: "FlashSetTargetSlotsMetricsRequest",
}) as any as S.Schema<FlashSetTargetSlotsMetricsRequest>;

export interface FlashSetTargetSlotsMetricsResponse {}
export const FlashSetTargetSlotsMetricsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "FlashSetTargetSlotsMetricsResponse",
}) as any as S.Schema<FlashSetTargetSlotsMetricsResponse>;

export interface ListFlashContainerRequest {
  functionId?: string;
}
export const ListFlashContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionId: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/FlashContainerList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListFlashContainerRequest",
}) as any as S.Schema<ListFlashContainerRequest>;

export interface ListFlashContainerResponseContainer {
  taskId?: string;
  host?: string;
  port?: number;
}
export const ListFlashContainerResponseContainer = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String),
    host: S.optional(S.String),
    port: S.optional(S.Number),
  }),
).annotate({
  identifier: "ListFlashContainerResponseContainer",
}) as any as S.Schema<ListFlashContainerResponseContainer>;

export type ListFlashContainerResponseContainerList =
  Array<ListFlashContainerResponseContainer>;
export const ListFlashContainerResponseContainerList = /*@__PURE__*/ S.Array(
  ListFlashContainerResponseContainer,
) as any as S.Schema<ListFlashContainerResponseContainerList>;

export interface ListFlashContainerResponse {
  containers?: ListFlashContainerResponseContainerList;
}
export const ListFlashContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    containers: S.optional(ListFlashContainerResponseContainerList),
  }),
).annotate({
  identifier: "ListFlashContainerResponse",
}) as any as S.Schema<ListFlashContainerResponse>;

export interface RegisterFlashContainerRequest {
  serviceName?: string;
  /** not used? */
  priority?: number;
  weight?: number;
  host?: string;
  port?: number;
}
export const RegisterFlashContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.optional(S.String),
    priority: S.optional(S.Number),
    weight: S.optional(S.Number),
    host: S.optional(S.String),
    port: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/FlashContainerRegister",
      code: 200,
    }),
  ),
).annotate({
  identifier: "RegisterFlashContainerRequest",
}) as any as S.Schema<RegisterFlashContainerRequest>;

export interface RegisterFlashContainerResponse {
  url?: string;
}
export const RegisterFlashContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String),
  }),
).annotate({
  identifier: "RegisterFlashContainerResponse",
}) as any as S.Schema<RegisterFlashContainerResponse>;

export type FlashContainerDeregisterError = ModalOpError;
/** Modal Flash (experimental) */
export const flashContainerDeregister: API.OperationMethod<
  FlashContainerDeregisterRequest,
  FlashContainerDeregisterResponse,
  FlashContainerDeregisterError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: FlashContainerDeregisterRequest,
  output: FlashContainerDeregisterResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type FlashSetTargetSlotsMetricsError = ModalOpError;
export const flashSetTargetSlotsMetrics: API.OperationMethod<
  FlashSetTargetSlotsMetricsRequest,
  FlashSetTargetSlotsMetricsResponse,
  FlashSetTargetSlotsMetricsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: FlashSetTargetSlotsMetricsRequest,
  output: FlashSetTargetSlotsMetricsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListFlashContainerError = ModalOpError;
export const listFlashContainer: API.OperationMethod<
  ListFlashContainerRequest,
  ListFlashContainerResponse,
  ListFlashContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListFlashContainerRequest,
  output: ListFlashContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type RegisterFlashContainerError = ModalOpError;
export const registerFlashContainer: API.OperationMethod<
  RegisterFlashContainerRequest,
  RegisterFlashContainerResponse,
  RegisterFlashContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RegisterFlashContainerRequest,
  output: RegisterFlashContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
