// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-huggingface/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  HuggingFaceProtocol,
  type HuggingFaceOpError,
  type HuggingFaceOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { HuggingFaceOpError, HuggingFaceOpContext };

export interface GetBlogResourceGroupRequest {
  namespace: string;
  slug: string;
}
export const GetBlogResourceGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    namespace: S.String.pipe(T.Label()),
    slug: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/blog/{namespace}/{slug}/resource-group",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetBlogResourceGroupRequest",
}) as any as S.Schema<GetBlogResourceGroupRequest>;

export interface GetBlogResourceGroupResponse {
  id: string;
  name: string;
  numUsers?: number;
}
export const GetBlogResourceGroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    numUsers: S.optional(S.Number),
  }),
).annotate({
  identifier: "GetBlogResourceGroupResponse",
}) as any as S.Schema<GetBlogResourceGroupResponse>;

export interface SetBlogResourceGroupRequest {
  namespace: string;
  slug: string;
  /** The resource group to assign the blog to. If null, the blog is removed from any resource group. */
  resourceGroupId: string | null;
}
export const SetBlogResourceGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    namespace: S.String.pipe(T.Label()),
    slug: S.String.pipe(T.Label()),
    resourceGroupId: S.NullOr(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/blog/{namespace}/{slug}/resource-group",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SetBlogResourceGroupRequest",
}) as any as S.Schema<SetBlogResourceGroupRequest>;

export interface SetBlogResourceGroupResponse {
  resourceGroupId: string | null;
  id: string;
  slug: string;
  title: string;
  private: boolean;
  addedBy: string;
}
export const SetBlogResourceGroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    resourceGroupId: S.NullOr(S.String),
    id: S.String,
    slug: S.String,
    title: S.String,
    private: S.Boolean,
    addedBy: S.String,
  }),
).annotate({
  identifier: "SetBlogResourceGroupResponse",
}) as any as S.Schema<SetBlogResourceGroupResponse>;

export type GetBlogResourceGroupError = HuggingFaceOpError;
/** Get blog resource group */
export const getBlogResourceGroup: API.OperationMethod<
  GetBlogResourceGroupRequest,
  GetBlogResourceGroupResponse,
  GetBlogResourceGroupError,
  HuggingFaceOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetBlogResourceGroupRequest,
  output: GetBlogResourceGroupResponse,
  errors: [],
  protocol: HuggingFaceProtocol,
  retry: Retry.Retry,
}));

export type SetBlogResourceGroupError = HuggingFaceOpError;
/** Set blog resource group Assign, move, or unassign an organization-owned blog to a resource group. Pass null to unassign. User-owned blogs are not eligible. */
export const setBlogResourceGroup: API.OperationMethod<
  SetBlogResourceGroupRequest,
  SetBlogResourceGroupResponse,
  SetBlogResourceGroupError,
  HuggingFaceOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SetBlogResourceGroupRequest,
  output: SetBlogResourceGroupResponse,
  errors: [],
  protocol: HuggingFaceProtocol,
  retry: Retry.Retry,
}));
