// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-huggingface/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  HuggingFaceProtocol,
  type HuggingFaceOpError,
  type HuggingFaceOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { HuggingFaceOpError, HuggingFaceOpContext };

export type QuickSearchPostRequestLangCase0 =
  | "aa"
  | "ab"
  | "ae"
  | "af"
  | "ak"
  | "am"
  | "an"
  | "ar"
  | "as"
  | "av"
  | "ay"
  | "az"
  | "ba"
  | "be"
  | "bg"
  | "bh"
  | "bi"
  | "bm"
  | "bn"
  | "bo"
  | "br"
  | "bs"
  | "ca"
  | "ce"
  | "ch"
  | "co"
  | "cr"
  | "cs"
  | "cu"
  | "cv"
  | "cy"
  | "da"
  | "de"
  | "dv"
  | "dz"
  | "ee"
  | "el"
  | "en"
  | "eo"
  | "es"
  | "et"
  | "eu"
  | "fa"
  | "ff"
  | "fi"
  | "fj"
  | "fo"
  | "fr"
  | "fy"
  | "ga"
  | "gd"
  | "gl"
  | "gn"
  | "gu"
  | "gv"
  | "ha"
  | "he"
  | "hi"
  | "ho"
  | "hr"
  | "ht"
  | "hu"
  | "hy"
  | "hz"
  | "ia"
  | "id"
  | "ie"
  | "ig"
  | "ii"
  | "ik"
  | "io"
  | "is"
  | "it"
  | "iu"
  | "ja"
  | "jv"
  | "ka"
  | "kg"
  | "ki"
  | "kj"
  | "kk"
  | "kl"
  | "km"
  | "kn"
  | "ko"
  | "kr"
  | "ks"
  | "ku"
  | "kv"
  | "kw"
  | "ky"
  | "la"
  | "lb"
  | "lg"
  | "li"
  | "ln"
  | "lo"
  | "lt"
  | "lu"
  | "lv"
  | "mg"
  | "mh"
  | "mi"
  | "mk"
  | "ml"
  | "mn"
  | "mr"
  | "ms"
  | "mt"
  | "my"
  | "na"
  | "nb"
  | "nd"
  | "ne"
  | "ng"
  | "nl"
  | "nn"
  | "no"
  | "nr"
  | "nv"
  | "ny"
  | "oc"
  | "oj"
  | "om"
  | "or"
  | "os"
  | "pa"
  | "pi"
  | "pl"
  | "ps"
  | "pt"
  | "qu"
  | "rm"
  | "rn"
  | "ro"
  | "ru"
  | "rw"
  | "sa"
  | "sc"
  | "sd"
  | "se"
  | "sg"
  | "si"
  | "sk"
  | "sl"
  | "sm"
  | "sn"
  | "so"
  | "sq"
  | "sr"
  | "ss"
  | "st"
  | "su"
  | "sv"
  | "sw"
  | "ta"
  | "te"
  | "tg"
  | "th"
  | "ti"
  | "tk"
  | "tl"
  | "tn"
  | "to"
  | "tr"
  | "ts"
  | "tt"
  | "tw"
  | "ty"
  | "ug"
  | "uk"
  | "ur"
  | "uz"
  | "ve"
  | "vi"
  | "vo"
  | "wa"
  | "wo"
  | "xh"
  | "yi"
  | "yo"
  | "za"
  | "zh"
  | "zu";
export const QuickSearchPostRequestLangCase0 = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestLang =
  | QuickSearchPostRequestLangCase0
  | string;
export const QuickSearchPostRequestLang =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestLang>;

export type QuickSearchPostRequestLibraryCase0 =
  | "acestep"
  | "adapter-transformers"
  | "allennlp"
  | "anemoi"
  | "araclip"
  | "aviation-ner"
  | "asteroid"
  | "audiocraft"
  | "audioseal"
  | "bagel-mot"
  | "bboxmaskpose"
  | "ben2"
  | "bertopic"
  | "big_vision"
  | "bionemo"
  | "birder"
  | "birefnet"
  | "bm25s"
  | "boltzgen"
  | "cancertathomev2"
  | "cartesia_pytorch"
  | "cartesia_mlx"
  | "ccpfn"
  | "champ"
  | "chatterbox"
  | "chaossim"
  | "chat_tts"
  | "chexmix"
  | "chronos-forecasting"
  | "clara"
  | "clipscope"
  | "cloud-agents"
  | "collectorvision"
  | "colipri"
  | "cosyvoice"
  | "cotracker"
  | "colpali"
  | "comet"
  | "cortiq"
  | "cosmos"
  | "cxr-foundation"
  | "deepforest"
  | "depth-anything-v2"
  | "depth-pro"
  | "derm-foundation"
  | "describe-anything"
  | "dia-tts"
  | "dia2"
  | "diff-interpretation-tuning"
  | "diffree"
  | "diffusers"
  | "diffusionkit"
  | "docking-at-home"
  | "doctr"
  | "edsnlp"
  | "elm"
  | "encoderfile"
  | "espnet"
  | "eupe"
  | "fairseq"
  | "fastai"
  | "fastprint"
  | "fasttext"
  | "fixer"
  | "flair"
  | "flextab"
  | "fme"
  | "gemma.cpp"
  | "geometry-crafter"
  | "gliner"
  | "gliner2"
  | "glm-tts"
  | "glyph-byt5"
  | "granite-library"
  | "grok"
  | "habibi-tts"
  | "hallo"
  | "minimax-h3"
  | "hermes"
  | "holomotion"
  | "hezar"
  | "htrflow"
  | "hunyuan-dit"
  | "hunyuan3d-2"
  | "hunyuanworld-voyager"
  | "hy-worldplay"
  | "hy-world-2"
  | "image-matching-models"
  | "imstoucan"
  | "index-tts"
  | "infinitetalk"
  | "infinite-you"
  | "intellifold"
  | "ising-decoding"
  | "keras"
  | "tf-keras"
  | "keras-hub"
  | "zeromodels"
  | "kernels"
  | "kimi-audio"
  | "kittentts"
  | "kronos"
  | "k2"
  | "lyra-2.0"
  | "lagernvs"
  | "ltx"
  | "lightning-ir"
  | "litert"
  | "litert-lm"
  | "lerobot"
  | "lightglue"
  | "liveportrait"
  | "longcat-video-avatar-1.5"
  | "llama-cpp-python"
  | "mini-omni2"
  | "mindspore"
  | "magi-1"
  | "magenta-realtime"
  | "magenta-realtime-2"
  | "mamba-ssm"
  | "manas-1"
  | "mars5-tts"
  | "matanyone"
  | "memra"
  | "mesh-anything"
  | "merlin"
  | "medvae"
  | "mflux"
  | "mitie"
  | "ml-agents"
  | "ml-sharp"
  | "mlx"
  | "mlx-image"
  | "mlc-llm"
  | "model2vec"
  | "mobilint"
  | "montreal-forced-aligner"
  | "moshi"
  | "mtvcraft"
  | "multimolecule"
  | "nemo"
  | "ninfer"
  | "nobg"
  | "nv-medtech"
  | "open-oasis"
  | "open_clip"
  | "openasr"
  | "opendde"
  | "openpeerllm"
  | "open-sora"
  | "outetts"
  | "paddlenlp"
  | "PaddleOCR"
  | "peft"
  | "perception-encoder"
  | "phantom-wan"
  | "piper"
  | "pocket-tts"
  | "pruna-ai"
  | "pxia"
  | "pyannote-audio"
  | "py-feat"
  | "pythae"
  | "quantumpeer"
  | "qwen3_tts"
  | "recurrentgemma"
  | "relik"
  | "refiners"
  | "renderformer"
  | "reverb"
  | "rkllm"
  | "robo-orchard-lab"
  | "routee-powertrain"
  | "rwkv"
  | "saelens"
  | "scail-2"
  | "sam2"
  | "sam-3d-body"
  | "sam-3d-objects"
  | "same"
  | "sample-factory"
  | "sap-rpt-1-oss"
  | "sapiens"
  | "sapiens2"
  | "seedvr"
  | "self-forcing"
  | "sentence-transformers"
  | "setfit"
  | "shadow"
  | "sklearn"
  | "spacy"
  | "span-marker"
  | "speechbrain"
  | "ssr-speech"
  | "stable-audio-3"
  | "stable-audio-tools"
  | "monkeyocr"
  | "diffusion-single-file"
  | "seed-story"
  | "skala"
  | "soloaudio"
  | "songbloom"
  | "stable-baselines3"
  | "stanza"
  | "supertonic"
  | "swarmformer"
  | "synthefy-migas"
  | "f5-tts"
  | "genmo"
  | "tencent-song-generation"
  | "tensorflowtts"
  | "tensorrt"
  | "tabpfn"
  | "terratorch"
  | "tic-clip"
  | "timesfm"
  | "timee-ts"
  | "timm"
  | "tirex"
  | "tirex-2"
  | "torchgeo"
  | "transformers"
  | "transformers.js"
  | "trellis"
  | "trellis2"
  | "tunejury"
  | "ultralytics"
  | "univa"
  | "uni-3dar"
  | "unity-sentis"
  | "sana"
  | "videoprism"
  | "vfi-mamba"
  | "vismatch"
  | "lvface"
  | "voicecraft"
  | "voxcpm"
  | "vui"
  | "vibevoice"
  | "videox_fun"
  | "wan2.2"
  | "wham"
  | "whisperkit"
  | "yolov10"
  | "yolov26"
  | "zonos"
  | "3dtopia-xl";
export const QuickSearchPostRequestLibraryCase0 = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestLibrary =
  | QuickSearchPostRequestLibraryCase0
  | string;
export const QuickSearchPostRequestLibrary =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestLibrary>;

export type QuickSearchPostRequestTypeCase0Item =
  | "model"
  | "dataset"
  | "space"
  | "org"
  | "user"
  | "paper"
  | "collection"
  | "bucket"
  | "kernel"
  | "blog";
export const QuickSearchPostRequestTypeCase0Item = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestTypeCase0List = Array<
  QuickSearchPostRequestTypeCase0Item | (string & {})
>;
export const QuickSearchPostRequestTypeCase0List = /*@__PURE__*/ S.Array(
  QuickSearchPostRequestTypeCase0Item,
) as any as S.Schema<QuickSearchPostRequestTypeCase0List>;

export type QuickSearchPostRequestTypeCase1List = Array<string>;
export const QuickSearchPostRequestTypeCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<QuickSearchPostRequestTypeCase1List>;

export type QuickSearchPostRequestType =
  | QuickSearchPostRequestTypeCase0List
  | QuickSearchPostRequestTypeCase1List;
export const QuickSearchPostRequestType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestType>;

export type QuickSearchPostRequestOrgsFilterCase0Item = "own" | "unwatched";
export const QuickSearchPostRequestOrgsFilterCase0Item = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestOrgsFilterCase0List = Array<
  QuickSearchPostRequestOrgsFilterCase0Item | (string & {})
>;
export const QuickSearchPostRequestOrgsFilterCase0List = /*@__PURE__*/ S.Array(
  QuickSearchPostRequestOrgsFilterCase0Item,
) as any as S.Schema<QuickSearchPostRequestOrgsFilterCase0List>;

export type QuickSearchPostRequestOrgsFilterCase1List = Array<string>;
export const QuickSearchPostRequestOrgsFilterCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<QuickSearchPostRequestOrgsFilterCase1List>;

export type QuickSearchPostRequestOrgsFilter =
  | QuickSearchPostRequestOrgsFilterCase0List
  | QuickSearchPostRequestOrgsFilterCase1List;
export const QuickSearchPostRequestOrgsFilter =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestOrgsFilter>;

export type QuickSearchPostRequestReposFilterCase0Item =
  | "skip_disabled"
  | "skip_gated"
  | "own"
  | "own_orgs"
  | "granted_access";
export const QuickSearchPostRequestReposFilterCase0Item =
  /*@__PURE__*/ S.String;

export type QuickSearchPostRequestReposFilterCase0List = Array<
  QuickSearchPostRequestReposFilterCase0Item | (string & {})
>;
export const QuickSearchPostRequestReposFilterCase0List = /*@__PURE__*/ S.Array(
  QuickSearchPostRequestReposFilterCase0Item,
) as any as S.Schema<QuickSearchPostRequestReposFilterCase0List>;

export type QuickSearchPostRequestReposFilterCase1List = Array<string>;
export const QuickSearchPostRequestReposFilterCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<QuickSearchPostRequestReposFilterCase1List>;

export type QuickSearchPostRequestReposFilter =
  | QuickSearchPostRequestReposFilterCase0List
  | QuickSearchPostRequestReposFilterCase1List;
export const QuickSearchPostRequestReposFilter =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestReposFilter>;

export type QuickSearchPostRequestPipelinesCase0Item =
  | "text-classification"
  | "token-classification"
  | "table-question-answering"
  | "question-answering"
  | "zero-shot-classification"
  | "translation"
  | "summarization"
  | "feature-extraction"
  | "text-generation"
  | "fill-mask"
  | "sentence-similarity"
  | "text-to-speech"
  | "text-to-audio"
  | "automatic-speech-recognition"
  | "audio-to-audio"
  | "audio-classification"
  | "audio-text-to-text"
  | "voice-activity-detection"
  | "depth-estimation"
  | "image-classification"
  | "object-detection"
  | "image-segmentation"
  | "text-to-image"
  | "image-to-text"
  | "image-to-image"
  | "image-to-video"
  | "unconditional-image-generation"
  | "video-classification"
  | "reinforcement-learning"
  | "robotics"
  | "tabular-classification"
  | "tabular-regression"
  | "tabular-to-text"
  | "table-to-text"
  | "multiple-choice"
  | "text-ranking"
  | "text-retrieval"
  | "time-series-forecasting"
  | "text-to-video"
  | "image-text-to-text"
  | "image-text-to-image"
  | "image-text-to-video"
  | "visual-question-answering"
  | "document-question-answering"
  | "zero-shot-image-classification"
  | "graph-ml"
  | "mask-generation"
  | "zero-shot-object-detection"
  | "text-to-3d"
  | "image-to-3d"
  | "image-feature-extraction"
  | "video-text-to-text"
  | "keypoint-detection"
  | "visual-document-retrieval"
  | "any-to-any"
  | "video-to-video"
  | "other";
export const QuickSearchPostRequestPipelinesCase0Item = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestPipelinesCase0List = Array<
  QuickSearchPostRequestPipelinesCase0Item | (string & {})
>;
export const QuickSearchPostRequestPipelinesCase0List = /*@__PURE__*/ S.Array(
  QuickSearchPostRequestPipelinesCase0Item,
) as any as S.Schema<QuickSearchPostRequestPipelinesCase0List>;

export type QuickSearchPostRequestPipelinesCase1Case1List = Array<string>;
export const QuickSearchPostRequestPipelinesCase1Case1List =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<QuickSearchPostRequestPipelinesCase1Case1List>;

export type QuickSearchPostRequestPipelinesCase1 =
  | string
  | QuickSearchPostRequestPipelinesCase1Case1List;
export const QuickSearchPostRequestPipelinesCase1 =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestPipelinesCase1>;

/** Comma-separated or array of pipeline types */
export type QuickSearchPostRequestPipelines =
  | QuickSearchPostRequestPipelinesCase0List
  | QuickSearchPostRequestPipelinesCase1;
export const QuickSearchPostRequestPipelines =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestPipelines>;

/** Array of excluded resources: spaces/repo, models/repo, datasets/repo, papers/paperId, collections/collectionId, users/username, orgs/orgName, buckets/bucketName, kernels/repo, blog/blogSlug */
export type QuickSearchPostRequestExcludeList = Array<string>;
export const QuickSearchPostRequestExcludeList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<QuickSearchPostRequestExcludeList>;

export type QuickSearchPostRequestIncludeInvitees = boolean | unknown;
export const QuickSearchPostRequestIncludeInvitees =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestIncludeInvitees>;

export type QuickSearchPostRequestRepoTypeCase0 =
  | "dataset"
  | "model"
  | "space"
  | "bucket"
  | "kernel";
export const QuickSearchPostRequestRepoTypeCase0 = /*@__PURE__*/ S.String;

export type QuickSearchPostRequestRepoType =
  | QuickSearchPostRequestRepoTypeCase0
  | string;
export const QuickSearchPostRequestRepoType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<QuickSearchPostRequestRepoType>;

export type QuickSearchPostRequestSpacesTagsList = Array<string>;
export const QuickSearchPostRequestSpacesTagsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<QuickSearchPostRequestSpacesTagsList>;

export interface QuickSearchPostRequest {
  q?: string;
  limit?: number;
  lang?: QuickSearchPostRequestLang;
  library?: QuickSearchPostRequestLibrary;
  type?: QuickSearchPostRequestType;
  orgsFilter?: QuickSearchPostRequestOrgsFilter;
  reposFilter?: QuickSearchPostRequestReposFilter;
  pipelines?: QuickSearchPostRequestPipelines;
  exclude?: QuickSearchPostRequestExcludeList;
  namespace?: string;
  includeInvitees?: QuickSearchPostRequestIncludeInvitees;
  repoName?: string;
  repoType?: QuickSearchPostRequestRepoType;
  discussionId?: string;
  discussionCollectionName?: string;
  spacesTags?: QuickSearchPostRequestSpacesTagsList;
}
export const QuickSearchPostRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    q: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    lang: S.optional(QuickSearchPostRequestLang.pipe(T.Query())),
    library: S.optional(QuickSearchPostRequestLibrary.pipe(T.Query())),
    type: S.optional(QuickSearchPostRequestType.pipe(T.Query())),
    orgsFilter: S.optional(QuickSearchPostRequestOrgsFilter.pipe(T.Query())),
    reposFilter: S.optional(QuickSearchPostRequestReposFilter.pipe(T.Query())),
    pipelines: S.optional(QuickSearchPostRequestPipelines.pipe(T.Query())),
    exclude: S.optional(QuickSearchPostRequestExcludeList.pipe(T.Query())),
    namespace: S.optional(S.String.pipe(T.Query())),
    includeInvitees: S.optional(
      QuickSearchPostRequestIncludeInvitees.pipe(T.Query()),
    ),
    repoName: S.optional(S.String.pipe(T.Query())),
    repoType: S.optional(QuickSearchPostRequestRepoType.pipe(T.Query())),
    discussionId: S.optional(S.String.pipe(T.Query())),
    discussionCollectionName: S.optional(S.String.pipe(T.Query())),
    spacesTags: S.optional(
      QuickSearchPostRequestSpacesTagsList.pipe(T.Query()),
    ),
  }).pipe(T.Http({ method: "POST", uri: "/api/quicksearch", code: 200 })),
).annotate({
  identifier: "QuickSearchPostRequest",
}) as any as S.Schema<QuickSearchPostRequest>;

export interface QuickSearchPostResponseDatasetsItem {
  _id: string;
  id: string;
  private?: boolean;
  trendingWeight: number;
}
export const QuickSearchPostResponseDatasetsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    id: S.String,
    private: S.optional(S.Boolean),
    trendingWeight: S.Number,
  }),
).annotate({
  identifier: "QuickSearchPostResponseDatasetsItem",
}) as any as S.Schema<QuickSearchPostResponseDatasetsItem>;

export type QuickSearchPostResponseDatasetsList =
  Array<QuickSearchPostResponseDatasetsItem>;
export const QuickSearchPostResponseDatasetsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseDatasetsItem,
) as any as S.Schema<QuickSearchPostResponseDatasetsList>;

export type QuickSearchPostResponseModelsItem =
  QuickSearchPostResponseDatasetsItem;
export const QuickSearchPostResponseModelsItem =
  QuickSearchPostResponseDatasetsItem;

export type QuickSearchPostResponseModelsList =
  Array<QuickSearchPostResponseDatasetsItem>;
export const QuickSearchPostResponseModelsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseDatasetsItem,
) as any as S.Schema<QuickSearchPostResponseModelsList>;

export interface QuickSearchPostResponseOrgsItem {
  _id: string;
  avatarUrl: string;
  fullname: string;
  name: string;
}
export const QuickSearchPostResponseOrgsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    avatarUrl: S.String,
    fullname: S.String,
    name: S.String,
  }),
).annotate({
  identifier: "QuickSearchPostResponseOrgsItem",
}) as any as S.Schema<QuickSearchPostResponseOrgsItem>;

export type QuickSearchPostResponseOrgsList =
  Array<QuickSearchPostResponseOrgsItem>;
export const QuickSearchPostResponseOrgsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseOrgsItem,
) as any as S.Schema<QuickSearchPostResponseOrgsList>;

export interface QuickSearchPostResponseSpacesItem {
  _id: string;
  id: string;
  private?: boolean;
  emoji: string;
  trendingWeight: number;
}
export const QuickSearchPostResponseSpacesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    id: S.String,
    private: S.optional(S.Boolean),
    emoji: S.String,
    trendingWeight: S.Number,
  }),
).annotate({
  identifier: "QuickSearchPostResponseSpacesItem",
}) as any as S.Schema<QuickSearchPostResponseSpacesItem>;

export type QuickSearchPostResponseSpacesList =
  Array<QuickSearchPostResponseSpacesItem>;
export const QuickSearchPostResponseSpacesList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseSpacesItem,
) as any as S.Schema<QuickSearchPostResponseSpacesList>;

export interface QuickSearchPostResponseUsersItem {
  _id: string;
  avatarUrl: string;
  fullname: string;
  user: string;
}
export const QuickSearchPostResponseUsersItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    avatarUrl: S.String,
    fullname: S.String,
    user: S.String,
  }),
).annotate({
  identifier: "QuickSearchPostResponseUsersItem",
}) as any as S.Schema<QuickSearchPostResponseUsersItem>;

export type QuickSearchPostResponseUsersList =
  Array<QuickSearchPostResponseUsersItem>;
export const QuickSearchPostResponseUsersList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseUsersItem,
) as any as S.Schema<QuickSearchPostResponseUsersList>;

export interface QuickSearchPostResponsePapersItem {
  _id: string;
  id: string;
  private?: boolean;
}
export const QuickSearchPostResponsePapersItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    id: S.String,
    private: S.optional(S.Boolean),
  }),
).annotate({
  identifier: "QuickSearchPostResponsePapersItem",
}) as any as S.Schema<QuickSearchPostResponsePapersItem>;

export type QuickSearchPostResponsePapersList =
  Array<QuickSearchPostResponsePapersItem>;
export const QuickSearchPostResponsePapersList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<QuickSearchPostResponsePapersList>;

export interface QuickSearchPostResponseCollectionsItem {
  _id: string;
  title: string;
  description?: string;
}
export const QuickSearchPostResponseCollectionsItem = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      _id: S.String,
      title: S.String,
      description: S.optional(S.String),
    }),
).annotate({
  identifier: "QuickSearchPostResponseCollectionsItem",
}) as any as S.Schema<QuickSearchPostResponseCollectionsItem>;

export type QuickSearchPostResponseCollectionsList =
  Array<QuickSearchPostResponseCollectionsItem>;
export const QuickSearchPostResponseCollectionsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseCollectionsItem,
) as any as S.Schema<QuickSearchPostResponseCollectionsList>;

export type QuickSearchPostResponseBucketsItem =
  QuickSearchPostResponsePapersItem;
export const QuickSearchPostResponseBucketsItem =
  QuickSearchPostResponsePapersItem;

export type QuickSearchPostResponseBucketsList =
  Array<QuickSearchPostResponsePapersItem>;
export const QuickSearchPostResponseBucketsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<QuickSearchPostResponseBucketsList>;

export type QuickSearchPostResponseKernelsItem =
  QuickSearchPostResponsePapersItem;
export const QuickSearchPostResponseKernelsItem =
  QuickSearchPostResponsePapersItem;

export type QuickSearchPostResponseKernelsList =
  Array<QuickSearchPostResponsePapersItem>;
export const QuickSearchPostResponseKernelsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<QuickSearchPostResponseKernelsList>;

export interface QuickSearchPostResponseBlogsItem {
  _id: string;
  slug: string;
  title: string;
  private: boolean;
}
export const QuickSearchPostResponseBlogsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _id: S.String,
    slug: S.String,
    title: S.String,
    private: S.Boolean,
  }),
).annotate({
  identifier: "QuickSearchPostResponseBlogsItem",
}) as any as S.Schema<QuickSearchPostResponseBlogsItem>;

export type QuickSearchPostResponseBlogsList =
  Array<QuickSearchPostResponseBlogsItem>;
export const QuickSearchPostResponseBlogsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseBlogsItem,
) as any as S.Schema<QuickSearchPostResponseBlogsList>;

export interface QuickSearchPostResponse {
  datasets: QuickSearchPostResponseDatasetsList;
  datasetsCount: number;
  models: QuickSearchPostResponseModelsList;
  modelsCount: number;
  orgs: QuickSearchPostResponseOrgsList;
  q: string;
  spaces: QuickSearchPostResponseSpacesList;
  spacesCount: number;
  users: QuickSearchPostResponseUsersList;
  papers: QuickSearchPostResponsePapersList;
  papersCount: number;
  collections: QuickSearchPostResponseCollectionsList;
  collectionsCount: number;
  buckets: QuickSearchPostResponseBucketsList;
  bucketsCount: number;
  kernels: QuickSearchPostResponseKernelsList;
  kernelsCount: number;
  blogs: QuickSearchPostResponseBlogsList;
  blogsCount: number;
}
export const QuickSearchPostResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    datasets: QuickSearchPostResponseDatasetsList,
    datasetsCount: S.Number,
    models: QuickSearchPostResponseModelsList,
    modelsCount: S.Number,
    orgs: QuickSearchPostResponseOrgsList,
    q: S.String,
    spaces: QuickSearchPostResponseSpacesList,
    spacesCount: S.Number,
    users: QuickSearchPostResponseUsersList,
    papers: QuickSearchPostResponsePapersList,
    papersCount: S.Number,
    collections: QuickSearchPostResponseCollectionsList,
    collectionsCount: S.Number,
    buckets: QuickSearchPostResponseBucketsList,
    bucketsCount: S.Number,
    kernels: QuickSearchPostResponseKernelsList,
    kernelsCount: S.Number,
    blogs: QuickSearchPostResponseBlogsList,
    blogsCount: S.Number,
  }),
).annotate({
  identifier: "QuickSearchPostResponse",
}) as any as S.Schema<QuickSearchPostResponse>;

export type SearchQuickRequestLangCase0 =
  | "aa"
  | "ab"
  | "ae"
  | "af"
  | "ak"
  | "am"
  | "an"
  | "ar"
  | "as"
  | "av"
  | "ay"
  | "az"
  | "ba"
  | "be"
  | "bg"
  | "bh"
  | "bi"
  | "bm"
  | "bn"
  | "bo"
  | "br"
  | "bs"
  | "ca"
  | "ce"
  | "ch"
  | "co"
  | "cr"
  | "cs"
  | "cu"
  | "cv"
  | "cy"
  | "da"
  | "de"
  | "dv"
  | "dz"
  | "ee"
  | "el"
  | "en"
  | "eo"
  | "es"
  | "et"
  | "eu"
  | "fa"
  | "ff"
  | "fi"
  | "fj"
  | "fo"
  | "fr"
  | "fy"
  | "ga"
  | "gd"
  | "gl"
  | "gn"
  | "gu"
  | "gv"
  | "ha"
  | "he"
  | "hi"
  | "ho"
  | "hr"
  | "ht"
  | "hu"
  | "hy"
  | "hz"
  | "ia"
  | "id"
  | "ie"
  | "ig"
  | "ii"
  | "ik"
  | "io"
  | "is"
  | "it"
  | "iu"
  | "ja"
  | "jv"
  | "ka"
  | "kg"
  | "ki"
  | "kj"
  | "kk"
  | "kl"
  | "km"
  | "kn"
  | "ko"
  | "kr"
  | "ks"
  | "ku"
  | "kv"
  | "kw"
  | "ky"
  | "la"
  | "lb"
  | "lg"
  | "li"
  | "ln"
  | "lo"
  | "lt"
  | "lu"
  | "lv"
  | "mg"
  | "mh"
  | "mi"
  | "mk"
  | "ml"
  | "mn"
  | "mr"
  | "ms"
  | "mt"
  | "my"
  | "na"
  | "nb"
  | "nd"
  | "ne"
  | "ng"
  | "nl"
  | "nn"
  | "no"
  | "nr"
  | "nv"
  | "ny"
  | "oc"
  | "oj"
  | "om"
  | "or"
  | "os"
  | "pa"
  | "pi"
  | "pl"
  | "ps"
  | "pt"
  | "qu"
  | "rm"
  | "rn"
  | "ro"
  | "ru"
  | "rw"
  | "sa"
  | "sc"
  | "sd"
  | "se"
  | "sg"
  | "si"
  | "sk"
  | "sl"
  | "sm"
  | "sn"
  | "so"
  | "sq"
  | "sr"
  | "ss"
  | "st"
  | "su"
  | "sv"
  | "sw"
  | "ta"
  | "te"
  | "tg"
  | "th"
  | "ti"
  | "tk"
  | "tl"
  | "tn"
  | "to"
  | "tr"
  | "ts"
  | "tt"
  | "tw"
  | "ty"
  | "ug"
  | "uk"
  | "ur"
  | "uz"
  | "ve"
  | "vi"
  | "vo"
  | "wa"
  | "wo"
  | "xh"
  | "yi"
  | "yo"
  | "za"
  | "zh"
  | "zu";
export const SearchQuickRequestLangCase0 = /*@__PURE__*/ S.String;

export type SearchQuickRequestLang = SearchQuickRequestLangCase0 | string;
export const SearchQuickRequestLang =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestLang>;

export type SearchQuickRequestLibraryCase0 =
  | "acestep"
  | "adapter-transformers"
  | "allennlp"
  | "anemoi"
  | "araclip"
  | "aviation-ner"
  | "asteroid"
  | "audiocraft"
  | "audioseal"
  | "bagel-mot"
  | "bboxmaskpose"
  | "ben2"
  | "bertopic"
  | "big_vision"
  | "bionemo"
  | "birder"
  | "birefnet"
  | "bm25s"
  | "boltzgen"
  | "cancertathomev2"
  | "cartesia_pytorch"
  | "cartesia_mlx"
  | "ccpfn"
  | "champ"
  | "chatterbox"
  | "chaossim"
  | "chat_tts"
  | "chexmix"
  | "chronos-forecasting"
  | "clara"
  | "clipscope"
  | "cloud-agents"
  | "collectorvision"
  | "colipri"
  | "cosyvoice"
  | "cotracker"
  | "colpali"
  | "comet"
  | "cortiq"
  | "cosmos"
  | "cxr-foundation"
  | "deepforest"
  | "depth-anything-v2"
  | "depth-pro"
  | "derm-foundation"
  | "describe-anything"
  | "dia-tts"
  | "dia2"
  | "diff-interpretation-tuning"
  | "diffree"
  | "diffusers"
  | "diffusionkit"
  | "docking-at-home"
  | "doctr"
  | "edsnlp"
  | "elm"
  | "encoderfile"
  | "espnet"
  | "eupe"
  | "fairseq"
  | "fastai"
  | "fastprint"
  | "fasttext"
  | "fixer"
  | "flair"
  | "flextab"
  | "fme"
  | "gemma.cpp"
  | "geometry-crafter"
  | "gliner"
  | "gliner2"
  | "glm-tts"
  | "glyph-byt5"
  | "granite-library"
  | "grok"
  | "habibi-tts"
  | "hallo"
  | "minimax-h3"
  | "hermes"
  | "holomotion"
  | "hezar"
  | "htrflow"
  | "hunyuan-dit"
  | "hunyuan3d-2"
  | "hunyuanworld-voyager"
  | "hy-worldplay"
  | "hy-world-2"
  | "image-matching-models"
  | "imstoucan"
  | "index-tts"
  | "infinitetalk"
  | "infinite-you"
  | "intellifold"
  | "ising-decoding"
  | "keras"
  | "tf-keras"
  | "keras-hub"
  | "zeromodels"
  | "kernels"
  | "kimi-audio"
  | "kittentts"
  | "kronos"
  | "k2"
  | "lyra-2.0"
  | "lagernvs"
  | "ltx"
  | "lightning-ir"
  | "litert"
  | "litert-lm"
  | "lerobot"
  | "lightglue"
  | "liveportrait"
  | "longcat-video-avatar-1.5"
  | "llama-cpp-python"
  | "mini-omni2"
  | "mindspore"
  | "magi-1"
  | "magenta-realtime"
  | "magenta-realtime-2"
  | "mamba-ssm"
  | "manas-1"
  | "mars5-tts"
  | "matanyone"
  | "memra"
  | "mesh-anything"
  | "merlin"
  | "medvae"
  | "mflux"
  | "mitie"
  | "ml-agents"
  | "ml-sharp"
  | "mlx"
  | "mlx-image"
  | "mlc-llm"
  | "model2vec"
  | "mobilint"
  | "montreal-forced-aligner"
  | "moshi"
  | "mtvcraft"
  | "multimolecule"
  | "nemo"
  | "ninfer"
  | "nobg"
  | "nv-medtech"
  | "open-oasis"
  | "open_clip"
  | "openasr"
  | "opendde"
  | "openpeerllm"
  | "open-sora"
  | "outetts"
  | "paddlenlp"
  | "PaddleOCR"
  | "peft"
  | "perception-encoder"
  | "phantom-wan"
  | "piper"
  | "pocket-tts"
  | "pruna-ai"
  | "pxia"
  | "pyannote-audio"
  | "py-feat"
  | "pythae"
  | "quantumpeer"
  | "qwen3_tts"
  | "recurrentgemma"
  | "relik"
  | "refiners"
  | "renderformer"
  | "reverb"
  | "rkllm"
  | "robo-orchard-lab"
  | "routee-powertrain"
  | "rwkv"
  | "saelens"
  | "scail-2"
  | "sam2"
  | "sam-3d-body"
  | "sam-3d-objects"
  | "same"
  | "sample-factory"
  | "sap-rpt-1-oss"
  | "sapiens"
  | "sapiens2"
  | "seedvr"
  | "self-forcing"
  | "sentence-transformers"
  | "setfit"
  | "shadow"
  | "sklearn"
  | "spacy"
  | "span-marker"
  | "speechbrain"
  | "ssr-speech"
  | "stable-audio-3"
  | "stable-audio-tools"
  | "monkeyocr"
  | "diffusion-single-file"
  | "seed-story"
  | "skala"
  | "soloaudio"
  | "songbloom"
  | "stable-baselines3"
  | "stanza"
  | "supertonic"
  | "swarmformer"
  | "synthefy-migas"
  | "f5-tts"
  | "genmo"
  | "tencent-song-generation"
  | "tensorflowtts"
  | "tensorrt"
  | "tabpfn"
  | "terratorch"
  | "tic-clip"
  | "timesfm"
  | "timee-ts"
  | "timm"
  | "tirex"
  | "tirex-2"
  | "torchgeo"
  | "transformers"
  | "transformers.js"
  | "trellis"
  | "trellis2"
  | "tunejury"
  | "ultralytics"
  | "univa"
  | "uni-3dar"
  | "unity-sentis"
  | "sana"
  | "videoprism"
  | "vfi-mamba"
  | "vismatch"
  | "lvface"
  | "voicecraft"
  | "voxcpm"
  | "vui"
  | "vibevoice"
  | "videox_fun"
  | "wan2.2"
  | "wham"
  | "whisperkit"
  | "yolov10"
  | "yolov26"
  | "zonos"
  | "3dtopia-xl";
export const SearchQuickRequestLibraryCase0 = /*@__PURE__*/ S.String;

export type SearchQuickRequestLibrary = SearchQuickRequestLibraryCase0 | string;
export const SearchQuickRequestLibrary =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestLibrary>;

export type SearchQuickRequestTypeCase0Item =
  | "model"
  | "dataset"
  | "space"
  | "org"
  | "user"
  | "paper"
  | "collection"
  | "bucket"
  | "kernel"
  | "blog";
export const SearchQuickRequestTypeCase0Item = /*@__PURE__*/ S.String;

export type SearchQuickRequestTypeCase0List = Array<
  SearchQuickRequestTypeCase0Item | (string & {})
>;
export const SearchQuickRequestTypeCase0List = /*@__PURE__*/ S.Array(
  SearchQuickRequestTypeCase0Item,
) as any as S.Schema<SearchQuickRequestTypeCase0List>;

export type SearchQuickRequestTypeCase1List = Array<string>;
export const SearchQuickRequestTypeCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestTypeCase1List>;

export type SearchQuickRequestType =
  | SearchQuickRequestTypeCase0List
  | SearchQuickRequestTypeCase1List;
export const SearchQuickRequestType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestType>;

export type SearchQuickRequestOrgsFilterCase0Item = "own" | "unwatched";
export const SearchQuickRequestOrgsFilterCase0Item = /*@__PURE__*/ S.String;

export type SearchQuickRequestOrgsFilterCase0List = Array<
  SearchQuickRequestOrgsFilterCase0Item | (string & {})
>;
export const SearchQuickRequestOrgsFilterCase0List = /*@__PURE__*/ S.Array(
  SearchQuickRequestOrgsFilterCase0Item,
) as any as S.Schema<SearchQuickRequestOrgsFilterCase0List>;

export type SearchQuickRequestOrgsFilterCase1List = Array<string>;
export const SearchQuickRequestOrgsFilterCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestOrgsFilterCase1List>;

export type SearchQuickRequestOrgsFilter =
  | SearchQuickRequestOrgsFilterCase0List
  | SearchQuickRequestOrgsFilterCase1List;
export const SearchQuickRequestOrgsFilter =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestOrgsFilter>;

export type SearchQuickRequestReposFilterCase0Item =
  | "skip_disabled"
  | "skip_gated"
  | "own"
  | "own_orgs"
  | "granted_access";
export const SearchQuickRequestReposFilterCase0Item = /*@__PURE__*/ S.String;

export type SearchQuickRequestReposFilterCase0List = Array<
  SearchQuickRequestReposFilterCase0Item | (string & {})
>;
export const SearchQuickRequestReposFilterCase0List = /*@__PURE__*/ S.Array(
  SearchQuickRequestReposFilterCase0Item,
) as any as S.Schema<SearchQuickRequestReposFilterCase0List>;

export type SearchQuickRequestReposFilterCase1List = Array<string>;
export const SearchQuickRequestReposFilterCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestReposFilterCase1List>;

export type SearchQuickRequestReposFilter =
  | SearchQuickRequestReposFilterCase0List
  | SearchQuickRequestReposFilterCase1List;
export const SearchQuickRequestReposFilter =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestReposFilter>;

export type SearchQuickRequestPipelinesCase0Item =
  | "text-classification"
  | "token-classification"
  | "table-question-answering"
  | "question-answering"
  | "zero-shot-classification"
  | "translation"
  | "summarization"
  | "feature-extraction"
  | "text-generation"
  | "fill-mask"
  | "sentence-similarity"
  | "text-to-speech"
  | "text-to-audio"
  | "automatic-speech-recognition"
  | "audio-to-audio"
  | "audio-classification"
  | "audio-text-to-text"
  | "voice-activity-detection"
  | "depth-estimation"
  | "image-classification"
  | "object-detection"
  | "image-segmentation"
  | "text-to-image"
  | "image-to-text"
  | "image-to-image"
  | "image-to-video"
  | "unconditional-image-generation"
  | "video-classification"
  | "reinforcement-learning"
  | "robotics"
  | "tabular-classification"
  | "tabular-regression"
  | "tabular-to-text"
  | "table-to-text"
  | "multiple-choice"
  | "text-ranking"
  | "text-retrieval"
  | "time-series-forecasting"
  | "text-to-video"
  | "image-text-to-text"
  | "image-text-to-image"
  | "image-text-to-video"
  | "visual-question-answering"
  | "document-question-answering"
  | "zero-shot-image-classification"
  | "graph-ml"
  | "mask-generation"
  | "zero-shot-object-detection"
  | "text-to-3d"
  | "image-to-3d"
  | "image-feature-extraction"
  | "video-text-to-text"
  | "keypoint-detection"
  | "visual-document-retrieval"
  | "any-to-any"
  | "video-to-video"
  | "other";
export const SearchQuickRequestPipelinesCase0Item = /*@__PURE__*/ S.String;

export type SearchQuickRequestPipelinesCase0List = Array<
  SearchQuickRequestPipelinesCase0Item | (string & {})
>;
export const SearchQuickRequestPipelinesCase0List = /*@__PURE__*/ S.Array(
  SearchQuickRequestPipelinesCase0Item,
) as any as S.Schema<SearchQuickRequestPipelinesCase0List>;

export type SearchQuickRequestPipelinesCase1Case1List = Array<string>;
export const SearchQuickRequestPipelinesCase1Case1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestPipelinesCase1Case1List>;

export type SearchQuickRequestPipelinesCase1 =
  | string
  | SearchQuickRequestPipelinesCase1Case1List;
export const SearchQuickRequestPipelinesCase1 =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestPipelinesCase1>;

/** Comma-separated or array of pipeline types */
export type SearchQuickRequestPipelines =
  | SearchQuickRequestPipelinesCase0List
  | SearchQuickRequestPipelinesCase1;
export const SearchQuickRequestPipelines =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestPipelines>;

/** Array of excluded resources: spaces/repo, models/repo, datasets/repo, papers/paperId, collections/collectionId, users/username, orgs/orgName, buckets/bucketName, kernels/repo, blog/blogSlug */
export type SearchQuickRequestExcludeList = Array<string>;
export const SearchQuickRequestExcludeList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestExcludeList>;

export type SearchQuickRequestIncludeInvitees = boolean | unknown;
export const SearchQuickRequestIncludeInvitees =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestIncludeInvitees>;

export type SearchQuickRequestRepoTypeCase0 =
  | "dataset"
  | "model"
  | "space"
  | "bucket"
  | "kernel";
export const SearchQuickRequestRepoTypeCase0 = /*@__PURE__*/ S.String;

export type SearchQuickRequestRepoType =
  | SearchQuickRequestRepoTypeCase0
  | string;
export const SearchQuickRequestRepoType =
  /*@__PURE__*/ S.Unknown as any as S.Schema<SearchQuickRequestRepoType>;

export type SearchQuickRequestSpacesTagsList = Array<string>;
export const SearchQuickRequestSpacesTagsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SearchQuickRequestSpacesTagsList>;

export interface SearchQuickRequest {
  q?: string;
  limit?: number;
  lang?: SearchQuickRequestLang;
  library?: SearchQuickRequestLibrary;
  type?: SearchQuickRequestType;
  orgsFilter?: SearchQuickRequestOrgsFilter;
  reposFilter?: SearchQuickRequestReposFilter;
  pipelines?: SearchQuickRequestPipelines;
  exclude?: SearchQuickRequestExcludeList;
  namespace?: string;
  includeInvitees?: SearchQuickRequestIncludeInvitees;
  repoName?: string;
  repoType?: SearchQuickRequestRepoType;
  discussionId?: string;
  discussionCollectionName?: string;
  spacesTags?: SearchQuickRequestSpacesTagsList;
}
export const SearchQuickRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    q: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    lang: S.optional(SearchQuickRequestLang.pipe(T.Query())),
    library: S.optional(SearchQuickRequestLibrary.pipe(T.Query())),
    type: S.optional(SearchQuickRequestType.pipe(T.Query())),
    orgsFilter: S.optional(SearchQuickRequestOrgsFilter.pipe(T.Query())),
    reposFilter: S.optional(SearchQuickRequestReposFilter.pipe(T.Query())),
    pipelines: S.optional(SearchQuickRequestPipelines.pipe(T.Query())),
    exclude: S.optional(SearchQuickRequestExcludeList.pipe(T.Query())),
    namespace: S.optional(S.String.pipe(T.Query())),
    includeInvitees: S.optional(
      SearchQuickRequestIncludeInvitees.pipe(T.Query()),
    ),
    repoName: S.optional(S.String.pipe(T.Query())),
    repoType: S.optional(SearchQuickRequestRepoType.pipe(T.Query())),
    discussionId: S.optional(S.String.pipe(T.Query())),
    discussionCollectionName: S.optional(S.String.pipe(T.Query())),
    spacesTags: S.optional(SearchQuickRequestSpacesTagsList.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/api/quicksearch", code: 200 })),
).annotate({
  identifier: "SearchQuickRequest",
}) as any as S.Schema<SearchQuickRequest>;

export type SearchQuickResponseDatasetsItem =
  QuickSearchPostResponseDatasetsItem;
export const SearchQuickResponseDatasetsItem =
  QuickSearchPostResponseDatasetsItem;

export type SearchQuickResponseDatasetsList =
  Array<QuickSearchPostResponseDatasetsItem>;
export const SearchQuickResponseDatasetsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseDatasetsItem,
) as any as S.Schema<SearchQuickResponseDatasetsList>;

export type SearchQuickResponseModelsItem = QuickSearchPostResponseDatasetsItem;
export const SearchQuickResponseModelsItem =
  QuickSearchPostResponseDatasetsItem;

export type SearchQuickResponseModelsList =
  Array<QuickSearchPostResponseDatasetsItem>;
export const SearchQuickResponseModelsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseDatasetsItem,
) as any as S.Schema<SearchQuickResponseModelsList>;

export type SearchQuickResponseOrgsItem = QuickSearchPostResponseOrgsItem;
export const SearchQuickResponseOrgsItem = QuickSearchPostResponseOrgsItem;

export type SearchQuickResponseOrgsList =
  Array<QuickSearchPostResponseOrgsItem>;
export const SearchQuickResponseOrgsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseOrgsItem,
) as any as S.Schema<SearchQuickResponseOrgsList>;

export type SearchQuickResponseSpacesItem = QuickSearchPostResponseSpacesItem;
export const SearchQuickResponseSpacesItem = QuickSearchPostResponseSpacesItem;

export type SearchQuickResponseSpacesList =
  Array<QuickSearchPostResponseSpacesItem>;
export const SearchQuickResponseSpacesList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseSpacesItem,
) as any as S.Schema<SearchQuickResponseSpacesList>;

export type SearchQuickResponseUsersItem = QuickSearchPostResponseUsersItem;
export const SearchQuickResponseUsersItem = QuickSearchPostResponseUsersItem;

export type SearchQuickResponseUsersList =
  Array<QuickSearchPostResponseUsersItem>;
export const SearchQuickResponseUsersList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseUsersItem,
) as any as S.Schema<SearchQuickResponseUsersList>;

export type SearchQuickResponsePapersItem = QuickSearchPostResponsePapersItem;
export const SearchQuickResponsePapersItem = QuickSearchPostResponsePapersItem;

export type SearchQuickResponsePapersList =
  Array<QuickSearchPostResponsePapersItem>;
export const SearchQuickResponsePapersList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<SearchQuickResponsePapersList>;

export type SearchQuickResponseCollectionsItem =
  QuickSearchPostResponseCollectionsItem;
export const SearchQuickResponseCollectionsItem =
  QuickSearchPostResponseCollectionsItem;

export type SearchQuickResponseCollectionsList =
  Array<QuickSearchPostResponseCollectionsItem>;
export const SearchQuickResponseCollectionsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseCollectionsItem,
) as any as S.Schema<SearchQuickResponseCollectionsList>;

export type SearchQuickResponseBucketsItem = QuickSearchPostResponsePapersItem;
export const SearchQuickResponseBucketsItem = QuickSearchPostResponsePapersItem;

export type SearchQuickResponseBucketsList =
  Array<QuickSearchPostResponsePapersItem>;
export const SearchQuickResponseBucketsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<SearchQuickResponseBucketsList>;

export type SearchQuickResponseKernelsItem = QuickSearchPostResponsePapersItem;
export const SearchQuickResponseKernelsItem = QuickSearchPostResponsePapersItem;

export type SearchQuickResponseKernelsList =
  Array<QuickSearchPostResponsePapersItem>;
export const SearchQuickResponseKernelsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponsePapersItem,
) as any as S.Schema<SearchQuickResponseKernelsList>;

export type SearchQuickResponseBlogsItem = QuickSearchPostResponseBlogsItem;
export const SearchQuickResponseBlogsItem = QuickSearchPostResponseBlogsItem;

export type SearchQuickResponseBlogsList =
  Array<QuickSearchPostResponseBlogsItem>;
export const SearchQuickResponseBlogsList = /*@__PURE__*/ S.Array(
  QuickSearchPostResponseBlogsItem,
) as any as S.Schema<SearchQuickResponseBlogsList>;

export interface SearchQuickResponse {
  datasets: SearchQuickResponseDatasetsList;
  datasetsCount: number;
  models: SearchQuickResponseModelsList;
  modelsCount: number;
  orgs: SearchQuickResponseOrgsList;
  q: string;
  spaces: SearchQuickResponseSpacesList;
  spacesCount: number;
  users: SearchQuickResponseUsersList;
  papers: SearchQuickResponsePapersList;
  papersCount: number;
  collections: SearchQuickResponseCollectionsList;
  collectionsCount: number;
  buckets: SearchQuickResponseBucketsList;
  bucketsCount: number;
  kernels: SearchQuickResponseKernelsList;
  kernelsCount: number;
  blogs: SearchQuickResponseBlogsList;
  blogsCount: number;
}
export const SearchQuickResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    datasets: SearchQuickResponseDatasetsList,
    datasetsCount: S.Number,
    models: SearchQuickResponseModelsList,
    modelsCount: S.Number,
    orgs: SearchQuickResponseOrgsList,
    q: S.String,
    spaces: SearchQuickResponseSpacesList,
    spacesCount: S.Number,
    users: SearchQuickResponseUsersList,
    papers: SearchQuickResponsePapersList,
    papersCount: S.Number,
    collections: SearchQuickResponseCollectionsList,
    collectionsCount: S.Number,
    buckets: SearchQuickResponseBucketsList,
    bucketsCount: S.Number,
    kernels: SearchQuickResponseKernelsList,
    kernelsCount: S.Number,
    blogs: SearchQuickResponseBlogsList,
    blogsCount: S.Number,
  }),
).annotate({
  identifier: "SearchQuickResponse",
}) as any as S.Schema<SearchQuickResponse>;

export type QuickSearchPostError = HuggingFaceOpError;
/** Quick search Quick search for models, datasets, spaces, orgs, users, papers, collections, and buckets */
export const quickSearchPost: API.OperationMethod<
  QuickSearchPostRequest,
  QuickSearchPostResponse,
  QuickSearchPostError,
  HuggingFaceOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: QuickSearchPostRequest,
  output: QuickSearchPostResponse,
  errors: [],
  protocol: HuggingFaceProtocol,
  retry: Retry.Retry,
}));

export type SearchQuickError = HuggingFaceOpError;
/** Quick search Quick search for models, datasets, spaces, orgs, users, papers, collections, and buckets */
export const searchQuick: API.OperationMethod<
  SearchQuickRequest,
  SearchQuickResponse,
  SearchQuickError,
  HuggingFaceOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchQuickRequest,
  output: SearchQuickResponse,
  errors: [],
  protocol: HuggingFaceProtocol,
  retry: Retry.Retry,
}));
