// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** * `full_refresh` - full_refresh * `incremental` - incremental * `append` - append * `webhook` - webhook * `cdc` - cdc * `xmin` - xmin */
export type ExternalDataSchemaSyncTypeEnum =
  | "full_refresh"
  | "incremental"
  | "append"
  | "webhook"
  | "cdc"
  | "xmin";
export const ExternalDataSchemaSyncTypeEnum = S.String;

/** * `integer` - integer * `numeric` - numeric * `datetime` - datetime * `date` - date * `timestamp` - timestamp * `objectid` - objectid * `xid` - xid */
export type IncrementalFieldTypeEnum =
  | "integer"
  | "numeric"
  | "datetime"
  | "date"
  | "timestamp"
  | "objectid"
  | "xid";
export const IncrementalFieldTypeEnum = S.String;

/** * `never` - never * `5min` - 5min * `15min` - 15min * `30min` - 30min * `1hour` - 1hour * `6hour` - 6hour * `12hour` - 12hour * `24hour` - 24hour * `7day` - 7day * `30day` - 30day */
export type ExternalDataSchemaSyncFrequencyEnum =
  | "never"
  | "5min"
  | "15min"
  | "30min"
  | "1hour"
  | "6hour"
  | "12hour"
  | "24hour"
  | "7day"
  | "30day";
export const ExternalDataSchemaSyncFrequencyEnum = S.String;

/** Column names for primary key deduplication. */
export type CreateExternalDataSchemasIncrementalFieldRequestPrimaryKeyColumnsList =
  Array<string>;
export const CreateExternalDataSchemasIncrementalFieldRequestPrimaryKeyColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldRequestPrimaryKeyColumnsList>;

/** * `consolidated` - consolidated * `cdc_only` - cdc_only * `both` - both */
export type CdcTableModeEnum = "consolidated" | "cdc_only" | "both";
export const CdcTableModeEnum = S.String;

/** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
export type CreateExternalDataSchemasIncrementalFieldRequestEnabledColumnsList =
  Array<string>;
export const CreateExternalDataSchemasIncrementalFieldRequestEnabledColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldRequestEnabledColumnsList>;

export interface CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem {
  column: string;
  /** One of: > >= < <= = != IN "NOT IN". */
  operator: string;
  /** Comparison value; must match the column's type. For `IN` / `NOT IN`, a comma-separated list (e.g. `1, 2, 3` or `'a','b'`). */
  value: unknown;
}
export const CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      column: S.String,
      operator: S.String,
      value: S.Unknown,
    }),
  ).annotate({
    identifier:
      "CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem",
  }) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem>;

/** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
export type CreateExternalDataSchemasIncrementalFieldRequestRowFiltersList =
  Array<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem>;
export const CreateExternalDataSchemasIncrementalFieldRequestRowFiltersList =
  /*@__PURE__*/ S.Array(
    CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem,
  ) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersList>;

export interface CreateExternalDataSchemasIncrementalFieldRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
  should_sync?: boolean;
  /** Sync strategy: incremental, full_refresh, append, cdc, or xmin. * `full_refresh` - full_refresh * `incremental` - incremental * `append` - append * `webhook` - webhook * `cdc` - cdc * `xmin` - xmin */
  sync_type?: ExternalDataSchemaSyncTypeEnum | (string & {}) | null;
  /** Column name used to track sync progress. */
  incremental_field?: string | null;
  /** Data type of the incremental field. * `integer` - integer * `numeric` - numeric * `datetime` - datetime * `date` - date * `timestamp` - timestamp * `objectid` - objectid * `xid` - xid */
  incremental_field_type?: IncrementalFieldTypeEnum | (string & {}) | null;
  /** Seconds to subtract from the stored incremental watermark at sync time, so each incremental run re-reads a rolling overlap window and catches late or backdated rows. Applies to timestamp/date incremental fields only. The stored watermark is unchanged. Maximum 5184000 (60 days). */
  incremental_field_lookback_seconds?: number | null;
  /** How often to sync. The fastest sync frequency is 5 minutes. * `never` - never * `5min` - 5min * `15min` - 15min * `30min` - 30min * `1hour` - 1hour * `6hour` - 6hour * `12hour` - 12hour * `24hour` - 24hour * `7day` - 7day * `30day` - 30day */
  sync_frequency?: ExternalDataSchemaSyncFrequencyEnum | (string & {}) | null;
  /** UTC time of day to run the sync (HH:MM:SS). */
  sync_time_of_day?: string | null;
  /** Column names for primary key deduplication. */
  primary_key_columns?: CreateExternalDataSchemasIncrementalFieldRequestPrimaryKeyColumnsList | null;
  /** For CDC syncs: consolidated, cdc_only, or both. * `consolidated` - consolidated * `cdc_only` - cdc_only * `both` - both */
  cdc_table_mode?: CdcTableModeEnum | (string & {}) | null;
  /** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
  enabled_columns?: CreateExternalDataSchemasIncrementalFieldRequestEnabledColumnsList | null;
  /** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
  row_filters?: CreateExternalDataSchemasIncrementalFieldRequestRowFiltersList | null;
  /** Vendor API version override for this schema. `null` (default) syncs on the source's pinned version. Must be one of the source type's supported versions. User-managed: version-migration tooling never changes it. Not available for webhook-sync schemas. */
  api_version?: string | null;
}
export const CreateExternalDataSchemasIncrementalFieldRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      should_sync: S.optional(S.Boolean),
      sync_type: S.optional(S.NullOr(ExternalDataSchemaSyncTypeEnum)),
      incremental_field: S.optional(S.NullOr(S.String)),
      incremental_field_type: S.optional(S.NullOr(IncrementalFieldTypeEnum)),
      incremental_field_lookback_seconds: S.optional(S.NullOr(S.Number)),
      sync_frequency: S.optional(S.NullOr(ExternalDataSchemaSyncFrequencyEnum)),
      sync_time_of_day: S.optional(S.NullOr(S.String)),
      primary_key_columns: S.optional(
        S.NullOr(
          CreateExternalDataSchemasIncrementalFieldRequestPrimaryKeyColumnsList,
        ),
      ),
      cdc_table_mode: S.optional(S.NullOr(CdcTableModeEnum)),
      enabled_columns: S.optional(
        S.NullOr(
          CreateExternalDataSchemasIncrementalFieldRequestEnabledColumnsList,
        ),
      ),
      row_filters: S.optional(
        S.NullOr(
          CreateExternalDataSchemasIncrementalFieldRequestRowFiltersList,
        ),
      ),
      api_version: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/incremental_fields/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "CreateExternalDataSchemasIncrementalFieldRequest",
  }) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldRequest>;

export interface CreateExternalDataSchemasIncrementalFieldResponse {}
export const CreateExternalDataSchemasIncrementalFieldResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "CreateExternalDataSchemasIncrementalFieldResponse",
  }) as any as S.Schema<CreateExternalDataSchemasIncrementalFieldResponse>;

export interface CreateExternalDataSchemasReloadRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const CreateExternalDataSchemasReloadRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/reload/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateExternalDataSchemasReloadRequest",
}) as any as S.Schema<CreateExternalDataSchemasReloadRequest>;

export interface CreateExternalDataSchemasReloadResponse {}
export const CreateExternalDataSchemasReloadResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "CreateExternalDataSchemasReloadResponse",
}) as any as S.Schema<CreateExternalDataSchemasReloadResponse>;

export interface CreateExternalDataSchemasResyncRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const CreateExternalDataSchemasResyncRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/resync/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateExternalDataSchemasResyncRequest",
}) as any as S.Schema<CreateExternalDataSchemasResyncRequest>;

export interface CreateExternalDataSchemasResyncResponse {}
export const CreateExternalDataSchemasResyncResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "CreateExternalDataSchemasResyncResponse",
}) as any as S.Schema<CreateExternalDataSchemasResyncResponse>;

export interface DeleteExternalDataSchemaDataDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const DeleteExternalDataSchemaDataDestroyRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/delete_data/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "DeleteExternalDataSchemaDataDestroyRequest",
  }) as any as S.Schema<DeleteExternalDataSchemaDataDestroyRequest>;

export interface DeleteExternalDataSchemaDataDestroyResponse {}
export const DeleteExternalDataSchemaDataDestroyResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "DeleteExternalDataSchemaDataDestroyResponse",
  }) as any as S.Schema<DeleteExternalDataSchemaDataDestroyResponse>;

export interface ExternalDataSchemasCancelCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const ExternalDataSchemasCancelCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/cancel/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "ExternalDataSchemasCancelCreateRequest",
}) as any as S.Schema<ExternalDataSchemasCancelCreateRequest>;

export interface ExternalDataSchemasCancelCreateResponse {
  detail?: string;
}
export const ExternalDataSchemasCancelCreateResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      detail: S.optional(S.String),
    }),
).annotate({
  identifier: "ExternalDataSchemasCancelCreateResponse",
}) as any as S.Schema<ExternalDataSchemasCancelCreateResponse>;

export interface ExternalDataSchemasDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const ExternalDataSchemasDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/external_data_schemas/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ExternalDataSchemasDestroyRequest",
}) as any as S.Schema<ExternalDataSchemasDestroyRequest>;

export interface ExternalDataSchemasDestroyResponse {}
export const ExternalDataSchemasDestroyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "ExternalDataSchemasDestroyResponse",
}) as any as S.Schema<ExternalDataSchemasDestroyResponse>;

export interface GetExternalDataSchemaRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const GetExternalDataSchemaRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/external_data_schemas/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetExternalDataSchemaRequest",
}) as any as S.Schema<GetExternalDataSchemaRequest>;

export type ExternalDataSchemaTableMap = { [key: string]: unknown | undefined };
export const ExternalDataSchemaTableMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<ExternalDataSchemaTableMap>;

/** Column names for primary key deduplication. */
export type ExternalDataSchemaPrimaryKeyColumnsList = Array<string>;
export const ExternalDataSchemaPrimaryKeyColumnsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ExternalDataSchemaPrimaryKeyColumnsList>;

/** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
export type ExternalDataSchemaEnabledColumnsList = Array<string>;
export const ExternalDataSchemaEnabledColumnsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ExternalDataSchemaEnabledColumnsList>;

export type ExternalDataSchemaRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;
export const ExternalDataSchemaRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;

/** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
export type ExternalDataSchemaRowFiltersList =
  Array<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem>;
export const ExternalDataSchemaRowFiltersList = /*@__PURE__*/ S.Array(
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem,
) as any as S.Schema<ExternalDataSchemaRowFiltersList>;

export interface ExternalDataSchemaAvailableColumnsItem {
  name: string;
  data_type?: string;
  is_nullable?: boolean;
}
export const ExternalDataSchemaAvailableColumnsItem = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      name: S.String,
      data_type: S.optional(S.String),
      is_nullable: S.optional(S.Boolean),
    }),
).annotate({
  identifier: "ExternalDataSchemaAvailableColumnsItem",
}) as any as S.Schema<ExternalDataSchemaAvailableColumnsItem>;

/** Column metadata (name, data type, nullable) for this schema. For SQL sources this is the source-side schema discovered via `refresh_schemas`; for other sources (and once synced) it falls back to the synced table's columns. Empty only before the first successful sync/refresh. */
export type ExternalDataSchemaAvailableColumnsList =
  Array<ExternalDataSchemaAvailableColumnsItem>;
export const ExternalDataSchemaAvailableColumnsList = /*@__PURE__*/ S.Array(
  ExternalDataSchemaAvailableColumnsItem,
) as any as S.Schema<ExternalDataSchemaAvailableColumnsList>;

export type ExternalDataSchemaSourceSupportedApiVersionsList = Array<string>;
export const ExternalDataSchemaSourceSupportedApiVersionsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ExternalDataSchemaSourceSupportedApiVersionsList>;

/** Lightweight parent-source summary (id, source_type, access_method, column-selection support, the requesting user's access level). Only populated on the single-schema retrieve endpoint — `null` elsewhere — so read-only views can render without fetching the full source and all its schemas. */
export interface ExternalDataSchemaSource {
  id?: string;
  source_type?: string;
  access_method?: string;
  supports_column_selection?: boolean;
  supports_row_filters?: boolean;
  requires_exact_column_metadata?: boolean;
  user_access_level?: string | null;
  api_version?: string | null;
  supported_api_versions?: ExternalDataSchemaSourceSupportedApiVersionsList;
}
export const ExternalDataSchemaSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    source_type: S.optional(S.String),
    access_method: S.optional(S.String),
    supports_column_selection: S.optional(S.Boolean),
    supports_row_filters: S.optional(S.Boolean),
    requires_exact_column_metadata: S.optional(S.Boolean),
    user_access_level: S.optional(S.NullOr(S.String)),
    api_version: S.optional(S.NullOr(S.String)),
    supported_api_versions: S.optional(
      ExternalDataSchemaSourceSupportedApiVersionsList,
    ),
  }),
).annotate({
  identifier: "ExternalDataSchemaSource",
}) as any as S.Schema<ExternalDataSchemaSource>;

export interface ExternalDataSourceApiVersionDeprecation {
  /** The deprecated vendor API version this source is pinned to. */
  version: string;
  /** Date the vendor stops serving this version; null if not announced. */
  sunset_at: string | null;
  /** The source's current default vendor API version — the migration target. */
  default_version: string;
}
export const ExternalDataSourceApiVersionDeprecation = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      version: S.String,
      sunset_at: S.NullOr(S.String),
      default_version: S.String,
    }),
).annotate({
  identifier: "ExternalDataSourceApiVersionDeprecation",
}) as any as S.Schema<ExternalDataSourceApiVersionDeprecation>;

/** A schema of an external data source: its sync configuration and the warehouse table it syncs into. */
export interface ExternalDataSchema {
  id?: string;
  name?: string;
  label?: string | null;
  table?: ExternalDataSchemaTableMap | null;
  should_sync?: boolean;
  last_synced_at?: string | null;
  /** The latest error that occurred when syncing this schema. */
  latest_error?: string | null;
  incremental?: boolean;
  status?: string | null;
  /** Sync strategy: incremental, full_refresh, append, cdc, or xmin. * `full_refresh` - full_refresh * `incremental` - incremental * `append` - append * `webhook` - webhook * `cdc` - cdc * `xmin` - xmin */
  sync_type?: ExternalDataSchemaSyncTypeEnum | null;
  /** Column name used to track sync progress. */
  incremental_field?: string | null;
  /** Data type of the incremental field. * `integer` - integer * `numeric` - numeric * `datetime` - datetime * `date` - date * `timestamp` - timestamp * `objectid` - objectid * `xid` - xid */
  incremental_field_type?: IncrementalFieldTypeEnum | null;
  /** Seconds to subtract from the stored incremental watermark at sync time, so each incremental run re-reads a rolling overlap window and catches late or backdated rows. Applies to timestamp/date incremental fields only. The stored watermark is unchanged. Maximum 5184000 (60 days). */
  incremental_field_lookback_seconds?: number | null;
  /** How often to sync. The fastest sync frequency is 5 minutes. * `never` - never * `5min` - 5min * `15min` - 15min * `30min` - 30min * `1hour` - 1hour * `6hour` - 6hour * `12hour` - 12hour * `24hour` - 24hour * `7day` - 7day * `30day` - 30day */
  sync_frequency?: ExternalDataSchemaSyncFrequencyEnum | null;
  /** UTC time of day to run the sync (HH:MM:SS). */
  sync_time_of_day?: string | null;
  description?: string | null;
  /** Column names for primary key deduplication. */
  primary_key_columns?: ExternalDataSchemaPrimaryKeyColumnsList | null;
  /** For CDC syncs: consolidated, cdc_only, or both. * `consolidated` - consolidated * `cdc_only` - cdc_only * `both` - both */
  cdc_table_mode?: CdcTableModeEnum | null;
  /** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
  enabled_columns?: ExternalDataSchemaEnabledColumnsList | null;
  /** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
  row_filters?: ExternalDataSchemaRowFiltersList | null;
  /** Column metadata (name, data type, nullable) for this schema. For SQL sources this is the source-side schema discovered via `refresh_schemas`; for other sources (and once synced) it falls back to the synced table's columns. Empty only before the first successful sync/refresh. */
  available_columns?: ExternalDataSchemaAvailableColumnsList;
  /** Whether exact source-side column metadata is available for safe source-query projection. */
  source_column_metadata_available?: boolean;
  /** Lightweight parent-source summary (id, source_type, access_method, column-selection support, the requesting user's access level). Only populated on the single-schema retrieve endpoint — `null` elsewhere — so read-only views can render without fetching the full source and all its schemas. */
  source?: ExternalDataSchemaSource | null;
  /** Vendor API version override for this schema. `null` (default) syncs on the source's pinned version. Must be one of the source type's supported versions. User-managed: version-migration tooling never changes it. Not available for webhook-sync schemas. */
  api_version?: string | null;
  /** Set when this schema's version override is deprecated by the vendor; null when there is no override or it is not deprecated. The source-level field covers the source pin. */
  api_version_deprecation?: ExternalDataSourceApiVersionDeprecation | null;
  /** The effective access level the user has for this object */
  user_access_level?: string | null;
}
export const ExternalDataSchema = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    label: S.optional(S.NullOr(S.String)),
    table: S.optional(S.NullOr(ExternalDataSchemaTableMap)),
    should_sync: S.optional(S.Boolean),
    last_synced_at: S.optional(S.NullOr(S.String)),
    latest_error: S.optional(S.NullOr(S.String)),
    incremental: S.optional(S.Boolean),
    status: S.optional(S.NullOr(S.String)),
    sync_type: S.optional(S.NullOr(ExternalDataSchemaSyncTypeEnum)),
    incremental_field: S.optional(S.NullOr(S.String)),
    incremental_field_type: S.optional(S.NullOr(IncrementalFieldTypeEnum)),
    incremental_field_lookback_seconds: S.optional(S.NullOr(S.Number)),
    sync_frequency: S.optional(S.NullOr(ExternalDataSchemaSyncFrequencyEnum)),
    sync_time_of_day: S.optional(S.NullOr(S.String)),
    description: S.optional(S.NullOr(S.String)),
    primary_key_columns: S.optional(
      S.NullOr(ExternalDataSchemaPrimaryKeyColumnsList),
    ),
    cdc_table_mode: S.optional(S.NullOr(CdcTableModeEnum)),
    enabled_columns: S.optional(S.NullOr(ExternalDataSchemaEnabledColumnsList)),
    row_filters: S.optional(S.NullOr(ExternalDataSchemaRowFiltersList)),
    available_columns: S.optional(ExternalDataSchemaAvailableColumnsList),
    source_column_metadata_available: S.optional(S.Boolean),
    source: S.optional(S.NullOr(ExternalDataSchemaSource)),
    api_version: S.optional(S.NullOr(S.String)),
    api_version_deprecation: S.optional(
      S.NullOr(ExternalDataSourceApiVersionDeprecation),
    ),
    user_access_level: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ExternalDataSchema",
}) as any as S.Schema<ExternalDataSchema>;

export interface GetExternalDataSchemasDestinationRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
}
export const GetExternalDataSchemasDestinationRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/destinations/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetExternalDataSchemasDestinationRequest",
}) as any as S.Schema<GetExternalDataSchemasDestinationRequest>;

/** The table's own destinations, or null when it follows its source. */
export type SchemaDestinationsDestinationIdsList = Array<string>;
export const SchemaDestinationsDestinationIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SchemaDestinationsDestinationIdsList>;

/** Where the table actually syncs, after inheritance is resolved. */
export type SchemaDestinationsEffectiveDestinationIdsList = Array<string>;
export const SchemaDestinationsEffectiveDestinationIdsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<SchemaDestinationsEffectiveDestinationIdsList>;

/** Response shape for a table's destination override. */
export interface SchemaDestinations {
  /** The table's own destinations, or null when it follows its source. */
  destination_ids: SchemaDestinationsDestinationIdsList | null;
  /** Whether this table follows its source rather than having its own destinations. */
  inherits_from_source: boolean;
  /** Where the table actually syncs, after inheritance is resolved. */
  effective_destination_ids?: SchemaDestinationsEffectiveDestinationIdsList;
}
export const SchemaDestinations = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    destination_ids: S.NullOr(SchemaDestinationsDestinationIdsList),
    inherits_from_source: S.Boolean,
    effective_destination_ids: S.optional(
      SchemaDestinationsEffectiveDestinationIdsList,
    ),
  }),
).annotate({
  identifier: "SchemaDestinations",
}) as any as S.Schema<SchemaDestinations>;

export interface GetExternalDataSchemasLogRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
  /** Only return entries after this ISO 8601 timestamp. Defaults to 7 days ago; pass an explicit value to read further back. */
  after?: string;
  /** Only return entries before this ISO 8601 timestamp. */
  before?: string;
  /** Filter logs to a specific execution instance. */
  instance_id?: string;
  /** Comma-separated log levels to include, e.g. 'WARN,ERROR'. Valid levels: DEBUG, LOG, INFO, WARN, ERROR. */
  level?: string;
  /** Maximum number of log entries to return (1-500, default 50). */
  limit?: number;
  /** Case-insensitive substring search across log messages. */
  search?: string;
}
export const GetExternalDataSchemasLogRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    after: S.optional(S.String.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    instance_id: S.optional(S.String.pipe(T.Query())),
    level: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/external_data_schemas/{id}/logs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetExternalDataSchemasLogRequest",
}) as any as S.Schema<GetExternalDataSchemasLogRequest>;

export interface GetExternalDataSchemasLogResponse {}
export const GetExternalDataSchemasLogResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GetExternalDataSchemasLogResponse",
}) as any as S.Schema<GetExternalDataSchemasLogResponse>;

export interface ListExternalDataSchemasRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** A search term. */
  search?: string;
}
export const ListExternalDataSchemasRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/external_data_schemas/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListExternalDataSchemasRequest",
}) as any as S.Schema<ListExternalDataSchemasRequest>;

export type PaginatedExternalDataSchemaListResultsList =
  Array<ExternalDataSchema>;
export const PaginatedExternalDataSchemaListResultsList = /*@__PURE__*/ S.Array(
  ExternalDataSchema,
) as any as S.Schema<PaginatedExternalDataSchemaListResultsList>;

export interface PaginatedExternalDataSchemaList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedExternalDataSchemaListResultsList;
}
export const PaginatedExternalDataSchemaList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedExternalDataSchemaListResultsList),
  }),
).annotate({
  identifier: "PaginatedExternalDataSchemaList",
}) as any as S.Schema<PaginatedExternalDataSchemaList>;

/** Column names for primary key deduplication. */
export type UpdateExternalDataSchemaRequestPrimaryKeyColumnsList =
  Array<string>;
export const UpdateExternalDataSchemaRequestPrimaryKeyColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateExternalDataSchemaRequestPrimaryKeyColumnsList>;

/** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
export type UpdateExternalDataSchemaRequestEnabledColumnsList = Array<string>;
export const UpdateExternalDataSchemaRequestEnabledColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateExternalDataSchemaRequestEnabledColumnsList>;

export type UpdateExternalDataSchemaRequestRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;
export const UpdateExternalDataSchemaRequestRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;

/** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
export type UpdateExternalDataSchemaRequestRowFiltersList =
  Array<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem>;
export const UpdateExternalDataSchemaRequestRowFiltersList =
  /*@__PURE__*/ S.Array(
    CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem,
  ) as any as S.Schema<UpdateExternalDataSchemaRequestRowFiltersList>;

export interface UpdateExternalDataSchemaRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
  should_sync?: boolean;
  /** Sync strategy: incremental, full_refresh, append, cdc, or xmin. * `full_refresh` - full_refresh * `incremental` - incremental * `append` - append * `webhook` - webhook * `cdc` - cdc * `xmin` - xmin */
  sync_type?: ExternalDataSchemaSyncTypeEnum | (string & {}) | null;
  /** Column name used to track sync progress. */
  incremental_field?: string | null;
  /** Data type of the incremental field. * `integer` - integer * `numeric` - numeric * `datetime` - datetime * `date` - date * `timestamp` - timestamp * `objectid` - objectid * `xid` - xid */
  incremental_field_type?: IncrementalFieldTypeEnum | (string & {}) | null;
  /** Seconds to subtract from the stored incremental watermark at sync time, so each incremental run re-reads a rolling overlap window and catches late or backdated rows. Applies to timestamp/date incremental fields only. The stored watermark is unchanged. Maximum 5184000 (60 days). */
  incremental_field_lookback_seconds?: number | null;
  /** How often to sync. The fastest sync frequency is 5 minutes. * `never` - never * `5min` - 5min * `15min` - 15min * `30min` - 30min * `1hour` - 1hour * `6hour` - 6hour * `12hour` - 12hour * `24hour` - 24hour * `7day` - 7day * `30day` - 30day */
  sync_frequency?: ExternalDataSchemaSyncFrequencyEnum | (string & {}) | null;
  /** UTC time of day to run the sync (HH:MM:SS). */
  sync_time_of_day?: string | null;
  /** Column names for primary key deduplication. */
  primary_key_columns?: UpdateExternalDataSchemaRequestPrimaryKeyColumnsList | null;
  /** For CDC syncs: consolidated, cdc_only, or both. * `consolidated` - consolidated * `cdc_only` - cdc_only * `both` - both */
  cdc_table_mode?: CdcTableModeEnum | (string & {}) | null;
  /** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
  enabled_columns?: UpdateExternalDataSchemaRequestEnabledColumnsList | null;
  /** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
  row_filters?: UpdateExternalDataSchemaRequestRowFiltersList | null;
  /** Vendor API version override for this schema. `null` (default) syncs on the source's pinned version. Must be one of the source type's supported versions. User-managed: version-migration tooling never changes it. Not available for webhook-sync schemas. */
  api_version?: string | null;
}
export const UpdateExternalDataSchemaRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    should_sync: S.optional(S.Boolean),
    sync_type: S.optional(S.NullOr(ExternalDataSchemaSyncTypeEnum)),
    incremental_field: S.optional(S.NullOr(S.String)),
    incremental_field_type: S.optional(S.NullOr(IncrementalFieldTypeEnum)),
    incremental_field_lookback_seconds: S.optional(S.NullOr(S.Number)),
    sync_frequency: S.optional(S.NullOr(ExternalDataSchemaSyncFrequencyEnum)),
    sync_time_of_day: S.optional(S.NullOr(S.String)),
    primary_key_columns: S.optional(
      S.NullOr(UpdateExternalDataSchemaRequestPrimaryKeyColumnsList),
    ),
    cdc_table_mode: S.optional(S.NullOr(CdcTableModeEnum)),
    enabled_columns: S.optional(
      S.NullOr(UpdateExternalDataSchemaRequestEnabledColumnsList),
    ),
    row_filters: S.optional(
      S.NullOr(UpdateExternalDataSchemaRequestRowFiltersList),
    ),
    api_version: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/api/projects/{project_id}/external_data_schemas/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateExternalDataSchemaRequest",
}) as any as S.Schema<UpdateExternalDataSchemaRequest>;

/** Destinations to sync to. On a table, null clears the override so the table follows its source again. */
export type UpdateExternalDataSchemasDestinationsPartialRequestDestinationIdsList =
  Array<string>;
export const UpdateExternalDataSchemasDestinationsPartialRequestDestinationIdsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateExternalDataSchemasDestinationsPartialRequestDestinationIdsList>;

export interface UpdateExternalDataSchemasDestinationsPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
  /** Destinations to sync to. On a table, null clears the override so the table follows its source again. */
  destination_ids?: UpdateExternalDataSchemasDestinationsPartialRequestDestinationIdsList | null;
}
export const UpdateExternalDataSchemasDestinationsPartialRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      destination_ids: S.optional(
        S.NullOr(
          UpdateExternalDataSchemasDestinationsPartialRequestDestinationIdsList,
        ),
      ),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/destinations/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "UpdateExternalDataSchemasDestinationsPartialRequest",
  }) as any as S.Schema<UpdateExternalDataSchemasDestinationsPartialRequest>;

/** Column names for primary key deduplication. */
export type UpdateExternalDataSchemasPartialRequestPrimaryKeyColumnsList =
  Array<string>;
export const UpdateExternalDataSchemasPartialRequestPrimaryKeyColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateExternalDataSchemasPartialRequestPrimaryKeyColumnsList>;

/** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
export type UpdateExternalDataSchemasPartialRequestEnabledColumnsList =
  Array<string>;
export const UpdateExternalDataSchemasPartialRequestEnabledColumnsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<UpdateExternalDataSchemasPartialRequestEnabledColumnsList>;

export type UpdateExternalDataSchemasPartialRequestRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;
export const UpdateExternalDataSchemasPartialRequestRowFiltersItem =
  CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem;

/** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
export type UpdateExternalDataSchemasPartialRequestRowFiltersList =
  Array<CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem>;
export const UpdateExternalDataSchemasPartialRequestRowFiltersList =
  /*@__PURE__*/ S.Array(
    CreateExternalDataSchemasIncrementalFieldRequestRowFiltersItem,
  ) as any as S.Schema<UpdateExternalDataSchemasPartialRequestRowFiltersList>;

export interface UpdateExternalDataSchemasPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this external data schema. */
  id: string;
  should_sync?: boolean;
  /** Sync strategy: incremental, full_refresh, append, cdc, or xmin. * `full_refresh` - full_refresh * `incremental` - incremental * `append` - append * `webhook` - webhook * `cdc` - cdc * `xmin` - xmin */
  sync_type?: ExternalDataSchemaSyncTypeEnum | (string & {}) | null;
  /** Column name used to track sync progress. */
  incremental_field?: string | null;
  /** Data type of the incremental field. * `integer` - integer * `numeric` - numeric * `datetime` - datetime * `date` - date * `timestamp` - timestamp * `objectid` - objectid * `xid` - xid */
  incremental_field_type?: IncrementalFieldTypeEnum | (string & {}) | null;
  /** Seconds to subtract from the stored incremental watermark at sync time, so each incremental run re-reads a rolling overlap window and catches late or backdated rows. Applies to timestamp/date incremental fields only. The stored watermark is unchanged. Maximum 5184000 (60 days). */
  incremental_field_lookback_seconds?: number | null;
  /** How often to sync. The fastest sync frequency is 5 minutes. * `never` - never * `5min` - 5min * `15min` - 15min * `30min` - 30min * `1hour` - 1hour * `6hour` - 6hour * `12hour` - 12hour * `24hour` - 24hour * `7day` - 7day * `30day` - 30day */
  sync_frequency?: ExternalDataSchemaSyncFrequencyEnum | (string & {}) | null;
  /** UTC time of day to run the sync (HH:MM:SS). */
  sync_time_of_day?: string | null;
  /** Column names for primary key deduplication. */
  primary_key_columns?: UpdateExternalDataSchemasPartialRequestPrimaryKeyColumnsList | null;
  /** For CDC syncs: consolidated, cdc_only, or both. * `consolidated` - consolidated * `cdc_only` - cdc_only * `both` - both */
  cdc_table_mode?: CdcTableModeEnum | (string & {}) | null;
  /** Names of source columns to sync. `null` (default) syncs all columns. Primary-key columns and the active incremental field are always retained, even if not listed here. */
  enabled_columns?: UpdateExternalDataSchemasPartialRequestEnabledColumnsList | null;
  /** Predicates ANDed onto the source query so only matching rows sync. Each is `{column, operator, value}`; `null`/empty (default) syncs all rows. The operator must be one of `> >= < <= = != IN "NOT IN"` and the value must match the column's type (for `IN`/`NOT IN`, a comma-separated list like `1, 2, 3` or `'a','b'`). Applied on the next sync — not retroactive to already-synced rows. */
  row_filters?: UpdateExternalDataSchemasPartialRequestRowFiltersList | null;
  /** Vendor API version override for this schema. `null` (default) syncs on the source's pinned version. Must be one of the source type's supported versions. User-managed: version-migration tooling never changes it. Not available for webhook-sync schemas. */
  api_version?: string | null;
}
export const UpdateExternalDataSchemasPartialRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      should_sync: S.optional(S.Boolean),
      sync_type: S.optional(S.NullOr(ExternalDataSchemaSyncTypeEnum)),
      incremental_field: S.optional(S.NullOr(S.String)),
      incremental_field_type: S.optional(S.NullOr(IncrementalFieldTypeEnum)),
      incremental_field_lookback_seconds: S.optional(S.NullOr(S.Number)),
      sync_frequency: S.optional(S.NullOr(ExternalDataSchemaSyncFrequencyEnum)),
      sync_time_of_day: S.optional(S.NullOr(S.String)),
      primary_key_columns: S.optional(
        S.NullOr(UpdateExternalDataSchemasPartialRequestPrimaryKeyColumnsList),
      ),
      cdc_table_mode: S.optional(S.NullOr(CdcTableModeEnum)),
      enabled_columns: S.optional(
        S.NullOr(UpdateExternalDataSchemasPartialRequestEnabledColumnsList),
      ),
      row_filters: S.optional(
        S.NullOr(UpdateExternalDataSchemasPartialRequestRowFiltersList),
      ),
      api_version: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/api/projects/{project_id}/external_data_schemas/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "UpdateExternalDataSchemasPartialRequest",
}) as any as S.Schema<UpdateExternalDataSchemasPartialRequest>;

export type CreateExternalDataSchemasIncrementalFieldError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const createExternalDataSchemasIncrementalField: API.OperationMethod<
  CreateExternalDataSchemasIncrementalFieldRequest,
  CreateExternalDataSchemasIncrementalFieldResponse,
  CreateExternalDataSchemasIncrementalFieldError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateExternalDataSchemasIncrementalFieldRequest,
  output: CreateExternalDataSchemasIncrementalFieldResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateExternalDataSchemasReloadError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const createExternalDataSchemasReload: API.OperationMethod<
  CreateExternalDataSchemasReloadRequest,
  CreateExternalDataSchemasReloadResponse,
  CreateExternalDataSchemasReloadError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateExternalDataSchemasReloadRequest,
  output: CreateExternalDataSchemasReloadResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateExternalDataSchemasResyncError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const createExternalDataSchemasResync: API.OperationMethod<
  CreateExternalDataSchemasResyncRequest,
  CreateExternalDataSchemasResyncResponse,
  CreateExternalDataSchemasResyncError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateExternalDataSchemasResyncRequest,
  output: CreateExternalDataSchemasResyncResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type DeleteExternalDataSchemaDataDestroyError =
  | Forbidden
  | NotFound
  | PosthogOpError;
export const deleteExternalDataSchemaDataDestroy: API.OperationMethod<
  DeleteExternalDataSchemaDataDestroyRequest,
  DeleteExternalDataSchemaDataDestroyResponse,
  DeleteExternalDataSchemaDataDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteExternalDataSchemaDataDestroyRequest,
  output: DeleteExternalDataSchemaDataDestroyResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ExternalDataSchemasCancelCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const externalDataSchemasCancelCreate: API.OperationMethod<
  ExternalDataSchemasCancelCreateRequest,
  ExternalDataSchemasCancelCreateResponse,
  ExternalDataSchemasCancelCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ExternalDataSchemasCancelCreateRequest,
  output: ExternalDataSchemasCancelCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ExternalDataSchemasDestroyError =
  | Forbidden
  | NotFound
  | PosthogOpError;
export const externalDataSchemasDestroy: API.OperationMethod<
  ExternalDataSchemasDestroyRequest,
  ExternalDataSchemasDestroyResponse,
  ExternalDataSchemasDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ExternalDataSchemasDestroyRequest,
  output: ExternalDataSchemasDestroyResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetExternalDataSchemaError = Forbidden | NotFound | PosthogOpError;
export const getExternalDataSchema: API.OperationMethod<
  GetExternalDataSchemaRequest,
  ExternalDataSchema,
  GetExternalDataSchemaError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetExternalDataSchemaRequest,
  output: ExternalDataSchema,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetExternalDataSchemasDestinationError = PosthogOpError;
/** Read or replace this table's destination override. Send `destination_ids: null` to clear the override so the table follows its source again. */
export const getExternalDataSchemasDestination: API.OperationMethod<
  GetExternalDataSchemasDestinationRequest,
  SchemaDestinations,
  GetExternalDataSchemasDestinationError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetExternalDataSchemasDestinationRequest,
  output: SchemaDestinations,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetExternalDataSchemasLogError = PosthogOpError;
export const getExternalDataSchemasLog: API.OperationMethod<
  GetExternalDataSchemasLogRequest,
  GetExternalDataSchemasLogResponse,
  GetExternalDataSchemasLogError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetExternalDataSchemasLogRequest,
  output: GetExternalDataSchemasLogResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListExternalDataSchemasError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const listExternalDataSchemas: API.OperationMethod<
  ListExternalDataSchemasRequest,
  PaginatedExternalDataSchemaList,
  ListExternalDataSchemasError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListExternalDataSchemasRequest,
  output: PaginatedExternalDataSchemaList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateExternalDataSchemaError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const updateExternalDataSchema: API.OperationMethod<
  UpdateExternalDataSchemaRequest,
  ExternalDataSchema,
  UpdateExternalDataSchemaError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateExternalDataSchemaRequest,
  output: ExternalDataSchema,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateExternalDataSchemasDestinationsPartialError = PosthogOpError;
/** Read or replace this table's destination override. Send `destination_ids: null` to clear the override so the table follows its source again. */
export const updateExternalDataSchemasDestinationsPartial: API.OperationMethod<
  UpdateExternalDataSchemasDestinationsPartialRequest,
  SchemaDestinations,
  UpdateExternalDataSchemasDestinationsPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateExternalDataSchemasDestinationsPartialRequest,
  output: SchemaDestinations,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateExternalDataSchemasPartialError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const updateExternalDataSchemasPartial: API.OperationMethod<
  UpdateExternalDataSchemasPartialRequest,
  ExternalDataSchema,
  UpdateExternalDataSchemasPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateExternalDataSchemasPartialRequest,
  output: ExternalDataSchema,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
