// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  PosthogProtocol,
  type PosthogOpError,
  type PosthogOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface CreateVisualReviewReposRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_full_name?: string;
  repo_external_id?: number | null;
}
export const CreateVisualReviewReposRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_full_name: S.optional(S.String),
    repo_external_id: S.optional(S.NullOr(S.Number)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/visual_review/repos/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateVisualReviewReposRequest",
}) as any as S.Schema<CreateVisualReviewReposRequest>;

export type RepoBaselineFilePathsMap = { [key: string]: string | undefined };
export const RepoBaselineFilePathsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<RepoBaselineFilePathsMap>;

export interface Repo {
  id?: string;
  team_id?: number;
  repo_external_id?: number;
  repo_full_name?: string;
  baseline_file_paths?: RepoBaselineFilePathsMap;
  enable_pr_comments?: boolean;
  created_at?: string;
}
export const Repo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    team_id: S.optional(S.Number),
    repo_external_id: S.optional(S.Number),
    repo_full_name: S.optional(S.String),
    baseline_file_paths: S.optional(RepoBaselineFilePathsMap),
    enable_pr_comments: S.optional(S.Boolean),
    created_at: S.optional(S.String),
  }),
).annotate({ identifier: "Repo" }) as any as S.Schema<Repo>;

export interface CreateVisualReviewReposQuarantineRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  run_type: string;
  /** Snapshot identifier to quarantine. */
  identifier?: string;
  /** Why this snapshot is being quarantined. */
  reason?: string;
  /** Optional pointer to the run whose failing snapshot prompted this quarantine — used to surface a 'view the failing run' link later. */
  source_run_id?: string | null;
  expires_at?: string | null;
}
export const CreateVisualReviewReposQuarantineRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.optional(S.String),
      reason: S.optional(S.String),
      source_run_id: S.optional(S.NullOr(S.String)),
      expires_at: S.optional(S.NullOr(S.String)),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/{run_type}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateVisualReviewReposQuarantineRequest",
}) as any as S.Schema<CreateVisualReviewReposQuarantineRequest>;

export interface UserBasicInfo {
  id?: number;
  first_name?: string;
  email?: string;
}
export const UserBasicInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    first_name: S.optional(S.String),
    email: S.optional(S.String),
  }),
).annotate({ identifier: "UserBasicInfo" }) as any as S.Schema<UserBasicInfo>;

export interface QuarantineSourceRun {
  id: string;
  branch: string;
  commit_sha: string;
  created_at: string;
  pr_number?: number | null;
}
export const QuarantineSourceRun = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    branch: S.String,
    commit_sha: S.String,
    created_at: S.String,
    pr_number: S.optional(S.NullOr(S.Number)),
  }),
).annotate({
  identifier: "QuarantineSourceRun",
}) as any as S.Schema<QuarantineSourceRun>;

export interface QuarantinedIdentifierEntry {
  created_by?: UserBasicInfo | null;
  /** Run whose failing snapshot prompted this quarantine. Null when quarantine was created without run context. */
  source_run?: QuarantineSourceRun | null;
  id?: string;
  identifier?: string;
  run_type?: string;
  reason?: string;
  source?: string;
  expires_at?: string | null;
  created_at?: string;
  updated_at?: string;
}
export const QuarantinedIdentifierEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_by: S.optional(S.NullOr(UserBasicInfo)),
    source_run: S.optional(S.NullOr(QuarantineSourceRun)),
    id: S.optional(S.String),
    identifier: S.optional(S.String),
    run_type: S.optional(S.String),
    reason: S.optional(S.String),
    source: S.optional(S.String),
    expires_at: S.optional(S.NullOr(S.String)),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
  }),
).annotate({
  identifier: "QuarantinedIdentifierEntry",
}) as any as S.Schema<QuarantinedIdentifierEntry>;

export interface CreateVisualReviewReposQuarantineExpireRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  run_type: string;
  /** Snapshot identifier to unquarantine */
  identifier: string;
}
export const CreateVisualReviewReposQuarantineExpireRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.String,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/{run_type}/expire/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "CreateVisualReviewReposQuarantineExpireRequest",
  }) as any as S.Schema<CreateVisualReviewReposQuarantineExpireRequest>;

export interface CreateVisualReviewReposQuarantineExpireResponse {}
export const CreateVisualReviewReposQuarantineExpireResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "CreateVisualReviewReposQuarantineExpireResponse",
  }) as any as S.Schema<CreateVisualReviewReposQuarantineExpireResponse>;

export type SnapshotManifestItemMetadataMap = {
  [key: string]: unknown | undefined;
};
export const SnapshotManifestItemMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<SnapshotManifestItemMetadataMap>;

export interface SnapshotManifestItem {
  identifier?: string;
  content_hash?: string;
  width?: number | null;
  height?: number | null;
  metadata?: SnapshotManifestItemMetadataMap;
}
export const SnapshotManifestItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifier: S.optional(S.String),
    content_hash: S.optional(S.String),
    width: S.optional(S.NullOr(S.Number)),
    height: S.optional(S.NullOr(S.Number)),
    metadata: S.optional(SnapshotManifestItemMetadataMap),
  }),
).annotate({
  identifier: "SnapshotManifestItem",
}) as any as S.Schema<SnapshotManifestItem>;

export type CreateVisualReviewRunRequestSnapshotsList =
  Array<SnapshotManifestItem>;
export const CreateVisualReviewRunRequestSnapshotsList = /*@__PURE__*/ S.Array(
  SnapshotManifestItem,
) as any as S.Schema<CreateVisualReviewRunRequestSnapshotsList>;

export type CreateVisualReviewRunRequestBaselineHashesMap = {
  [key: string]: string | undefined;
};
export const CreateVisualReviewRunRequestBaselineHashesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CreateVisualReviewRunRequestBaselineHashesMap>;

export type CreateVisualReviewRunRequestRemovedIdentifiersList = Array<string>;
export const CreateVisualReviewRunRequestRemovedIdentifiersList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateVisualReviewRunRequestRemovedIdentifiersList>;

export type CreateVisualReviewRunRequestMetadataMap = {
  [key: string]: unknown | undefined;
};
export const CreateVisualReviewRunRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<CreateVisualReviewRunRequestMetadataMap>;

export interface CreateVisualReviewRunRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id?: string;
  run_type?: string;
  commit_sha?: string;
  branch?: string;
  snapshots?: CreateVisualReviewRunRequestSnapshotsList;
  pr_number?: number | null;
  baseline_hashes?: CreateVisualReviewRunRequestBaselineHashesMap;
  unchanged_count?: number;
  removed_identifiers?: CreateVisualReviewRunRequestRemovedIdentifiersList;
  purpose?: string;
  metadata?: CreateVisualReviewRunRequestMetadataMap;
  is_partial?: boolean;
}
export const CreateVisualReviewRunRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_id: S.optional(S.String),
    run_type: S.optional(S.String),
    commit_sha: S.optional(S.String),
    branch: S.optional(S.String),
    snapshots: S.optional(CreateVisualReviewRunRequestSnapshotsList),
    pr_number: S.optional(S.NullOr(S.Number)),
    baseline_hashes: S.optional(CreateVisualReviewRunRequestBaselineHashesMap),
    unchanged_count: S.optional(S.Number),
    removed_identifiers: S.optional(
      CreateVisualReviewRunRequestRemovedIdentifiersList,
    ),
    purpose: S.optional(S.String),
    metadata: S.optional(CreateVisualReviewRunRequestMetadataMap),
    is_partial: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/visual_review/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateVisualReviewRunRequest",
}) as any as S.Schema<CreateVisualReviewRunRequest>;

export type UploadTargetFieldsMap = { [key: string]: string | undefined };
export const UploadTargetFieldsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UploadTargetFieldsMap>;

export interface UploadTarget {
  content_hash?: string;
  url?: string;
  fields?: UploadTargetFieldsMap;
}
export const UploadTarget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    content_hash: S.optional(S.String),
    url: S.optional(S.String),
    fields: S.optional(UploadTargetFieldsMap),
  }),
).annotate({ identifier: "UploadTarget" }) as any as S.Schema<UploadTarget>;

export type CreateRunResultUploadsList = Array<UploadTarget>;
export const CreateRunResultUploadsList = /*@__PURE__*/ S.Array(
  UploadTarget,
) as any as S.Schema<CreateRunResultUploadsList>;

export interface CreateRunResult {
  run_id?: string;
  uploads?: CreateRunResultUploadsList;
}
export const CreateRunResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run_id: S.optional(S.String),
    uploads: S.optional(CreateRunResultUploadsList),
  }),
).annotate({
  identifier: "CreateRunResult",
}) as any as S.Schema<CreateRunResult>;

export interface CreateVisualReviewRunsCompleteRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const CreateVisualReviewRunsCompleteRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/complete/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateVisualReviewRunsCompleteRequest",
}) as any as S.Schema<CreateVisualReviewRunsCompleteRequest>;

export type SearchMatchTypeEnum = "exact" | "similar";
export const SearchMatchTypeEnum = /*@__PURE__*/ S.String;

export interface RunSummary {
  total?: number;
  changed?: number;
  new?: number;
  removed?: number;
  unchanged?: number;
  unresolved?: number;
  tolerated_matched?: number;
}
export const RunSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    total: S.optional(S.Number),
    changed: S.optional(S.Number),
    new: S.optional(S.Number),
    removed: S.optional(S.Number),
    unchanged: S.optional(S.Number),
    unresolved: S.optional(S.Number),
    tolerated_matched: S.optional(S.Number),
  }),
).annotate({ identifier: "RunSummary" }) as any as S.Schema<RunSummary>;

export type RunMetadataMap = { [key: string]: unknown | undefined };
export const RunMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<RunMetadataMap>;

export interface Run {
  approved_by?: UserBasicInfo | null;
  /** How this row matched the `search` query parameter: `exact` (the term is a case-insensitive substring of branch/run type, a commit SHA prefix, or an exact PR number) or `similar` (a fuzzy trigram match, returned only when no exact match exists). Null when the list is not filtered by `search`. * `exact` - exact * `similar` - similar */
  search_match_type?: SearchMatchTypeEnum | null;
  id?: string;
  repo_id?: string;
  status?: string;
  run_type?: string;
  commit_sha?: string;
  branch?: string;
  pr_number?: number | null;
  approved?: boolean;
  approved_at?: string | null;
  summary?: RunSummary;
  error_message?: string | null;
  created_at?: string;
  completed_at?: string | null;
  is_stale?: boolean;
  superseded_by_id?: string | null;
  metadata?: RunMetadataMap;
}
export const Run = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    approved_by: S.optional(S.NullOr(UserBasicInfo)),
    search_match_type: S.optional(S.NullOr(SearchMatchTypeEnum)),
    id: S.optional(S.String),
    repo_id: S.optional(S.String),
    status: S.optional(S.String),
    run_type: S.optional(S.String),
    commit_sha: S.optional(S.String),
    branch: S.optional(S.String),
    pr_number: S.optional(S.NullOr(S.Number)),
    approved: S.optional(S.Boolean),
    approved_at: S.optional(S.NullOr(S.String)),
    summary: S.optional(RunSummary),
    error_message: S.optional(S.NullOr(S.String)),
    created_at: S.optional(S.String),
    completed_at: S.optional(S.NullOr(S.String)),
    is_stale: S.optional(S.Boolean),
    superseded_by_id: S.optional(S.NullOr(S.String)),
    metadata: S.optional(RunMetadataMap),
  }),
).annotate({ identifier: "Run" }) as any as S.Schema<Run>;

export interface CreateVisualReviewRunsFinalizeRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Approve every still-pending changed and new snapshot before finalizing (tolerated snapshots are left untouched). Leave false to finalize a run you've already reviewed — finalizing fails if any changed/new snapshot is still unreviewed. */
  approve_all?: boolean;
  /** Whether the server commits the approved baseline to the PR branch and greens the gate (the normal path — leave true). Set false only for tooling that commits the baseline itself: the server skips the commit and returns the signed YAML in `baseline_content` instead. With false, the gate is NOT greened and `metadata.baseline_commit_sha` is absent. */
  commit_to_github?: boolean;
  /** Whether to embed the before/after snapshot images in the post-approval PR comment. The comment itself is always posted (when the run was initiated from a GitHub review prompt and the repo has PR comments enabled); this flag only controls the images. Defaults false — the comment stays a text summary unless the reviewer opts in to attach the snapshots. */
  add_images_to_comment_on_pr?: boolean;
}
export const CreateVisualReviewRunsFinalizeRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      approve_all: S.optional(S.Boolean),
      commit_to_github: S.optional(S.Boolean),
      add_images_to_comment_on_pr: S.optional(S.Boolean),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/finalize/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateVisualReviewRunsFinalizeRequest",
}) as any as S.Schema<CreateVisualReviewRunsFinalizeRequest>;

export interface FinalizeResult {
  run: Run;
  baseline_content: string;
}
export const FinalizeResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run: Run,
    baseline_content: S.String,
  }),
).annotate({ identifier: "FinalizeResult" }) as any as S.Schema<FinalizeResult>;

export interface CreateVisualReviewRunsRecomputeRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const CreateVisualReviewRunsRecomputeRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/recompute/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateVisualReviewRunsRecomputeRequest",
}) as any as S.Schema<CreateVisualReviewRunsRecomputeRequest>;

export interface RecomputeResult {
  run?: Run;
  counts_changed?: boolean;
  unresolved?: number;
  ci_rerun_triggered?: boolean;
  ci_rerun_error?: string | null;
}
export const RecomputeResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run: S.optional(Run),
    counts_changed: S.optional(S.Boolean),
    unresolved: S.optional(S.Number),
    ci_rerun_triggered: S.optional(S.Boolean),
    ci_rerun_error: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "RecomputeResult",
}) as any as S.Schema<RecomputeResult>;

export interface CreateVisualReviewRunsTolerateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** UUID of the changed snapshot to mark as a known tolerated alternate. Future runs that produce the same alternate hash for this identifier will not be flagged as changes. */
  snapshot_id?: string;
}
export const CreateVisualReviewRunsTolerateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshot_id: S.optional(S.String),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/tolerate/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "CreateVisualReviewRunsTolerateRequest",
}) as any as S.Schema<CreateVisualReviewRunsTolerateRequest>;

export interface Artifact {
  id?: string;
  content_hash?: string;
  width?: number | null;
  height?: number | null;
  download_url?: string | null;
}
export const Artifact = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    content_hash: S.optional(S.String),
    width: S.optional(S.NullOr(S.Number)),
    height: S.optional(S.NullOr(S.Number)),
    download_url: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "Artifact" }) as any as S.Schema<Artifact>;

export interface DiffCluster {
  x: number;
  y: number;
  width: number;
  height: number;
  pixel_count: number;
  centroid_x: number;
  centroid_y: number;
}
export const DiffCluster = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    x: S.Number,
    y: S.Number,
    width: S.Number,
    height: S.Number,
    pixel_count: S.Number,
    centroid_x: S.Number,
    centroid_y: S.Number,
  }),
).annotate({ identifier: "DiffCluster" }) as any as S.Schema<DiffCluster>;

export type ClusterSummaryItemsList = Array<DiffCluster>;
export const ClusterSummaryItemsList = /*@__PURE__*/ S.Array(
  DiffCluster,
) as any as S.Schema<ClusterSummaryItemsList>;

export interface ClusterSummary {
  items: ClusterSummaryItemsList;
  total: number;
  truncated: boolean;
}
export const ClusterSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: ClusterSummaryItemsList,
    total: S.Number,
    truncated: S.Boolean,
  }),
).annotate({ identifier: "ClusterSummary" }) as any as S.Schema<ClusterSummary>;

export type SnapshotMetadataMap = { [key: string]: unknown | undefined };
export const SnapshotMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<SnapshotMetadataMap>;

export interface Snapshot {
  current_artifact?: Artifact | null;
  baseline_artifact?: Artifact | null;
  diff_artifact?: Artifact | null;
  reviewed_by?: UserBasicInfo | null;
  cluster_summary?: ClusterSummary | null;
  id?: string;
  run_id?: string;
  identifier?: string;
  result?: string;
  classification_reason?: string;
  diff_percentage?: number | null;
  diff_pixel_count?: number | null;
  review_state?: string;
  reviewed_at?: string | null;
  approved_hash?: string;
  tolerated_hash_id?: string | null;
  is_quarantined?: boolean;
  metadata?: SnapshotMetadataMap;
  ssim_score?: number | null;
  change_kind?: string;
  size_mismatch?: boolean;
}
export const Snapshot = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    current_artifact: S.optional(S.NullOr(Artifact)),
    baseline_artifact: S.optional(S.NullOr(Artifact)),
    diff_artifact: S.optional(S.NullOr(Artifact)),
    reviewed_by: S.optional(S.NullOr(UserBasicInfo)),
    cluster_summary: S.optional(S.NullOr(ClusterSummary)),
    id: S.optional(S.String),
    run_id: S.optional(S.String),
    identifier: S.optional(S.String),
    result: S.optional(S.String),
    classification_reason: S.optional(S.String),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    diff_pixel_count: S.optional(S.NullOr(S.Number)),
    review_state: S.optional(S.String),
    reviewed_at: S.optional(S.NullOr(S.String)),
    approved_hash: S.optional(S.String),
    tolerated_hash_id: S.optional(S.NullOr(S.String)),
    is_quarantined: S.optional(S.Boolean),
    metadata: S.optional(SnapshotMetadataMap),
    ssim_score: S.optional(S.NullOr(S.Number)),
    change_kind: S.optional(S.String),
    size_mismatch: S.optional(S.Boolean),
  }),
).annotate({ identifier: "Snapshot" }) as any as S.Schema<Snapshot>;

export interface GetVisualReviewReposRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetVisualReviewReposRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetVisualReviewReposRequest",
}) as any as S.Schema<GetVisualReviewReposRequest>;

export interface GetVisualReviewReposBaselineRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetVisualReviewReposBaselineRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/{id}/baselines/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetVisualReviewReposBaselineRequest",
}) as any as S.Schema<GetVisualReviewReposBaselineRequest>;

export interface BaselineQuarantineSummary {
  created_by?: UserBasicInfo | null;
  source_run?: QuarantineSourceRun | null;
  id: string;
  reason: string;
  source: string;
  expires_at: string | null;
  created_at: string;
}
export const BaselineQuarantineSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_by: S.optional(S.NullOr(UserBasicInfo)),
    source_run: S.optional(S.NullOr(QuarantineSourceRun)),
    id: S.String,
    reason: S.String,
    source: S.String,
    expires_at: S.NullOr(S.String),
    created_at: S.String,
  }),
).annotate({
  identifier: "BaselineQuarantineSummary",
}) as any as S.Schema<BaselineQuarantineSummary>;

export interface BaselineEntry {
  /** Active quarantine details when `is_quarantined` is true. Null otherwise. */
  quarantine?: BaselineQuarantineSummary | null;
  identifier: string;
  run_type: string;
  browser: string | null;
  thumbnail_hash: string | null;
  width: number | null;
  height: number | null;
  tolerate_count_30d: number;
  tolerate_count_90d: number;
  is_quarantined: boolean;
  last_run_at: string;
  baseline_change_count: number;
  recent_drift_avg: number | null;
}
export const BaselineEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    quarantine: S.optional(S.NullOr(BaselineQuarantineSummary)),
    identifier: S.String,
    run_type: S.String,
    browser: S.NullOr(S.String),
    thumbnail_hash: S.NullOr(S.String),
    width: S.NullOr(S.Number),
    height: S.NullOr(S.Number),
    tolerate_count_30d: S.Number,
    tolerate_count_90d: S.Number,
    is_quarantined: S.Boolean,
    last_run_at: S.String,
    baseline_change_count: S.Number,
    recent_drift_avg: S.NullOr(S.Number),
  }),
).annotate({ identifier: "BaselineEntry" }) as any as S.Schema<BaselineEntry>;

export type BaselineOverviewEntriesList = Array<BaselineEntry>;
export const BaselineOverviewEntriesList = /*@__PURE__*/ S.Array(
  BaselineEntry,
) as any as S.Schema<BaselineOverviewEntriesList>;

export type BaselineTotalsByRunTypeMap = { [key: string]: number | undefined };
export const BaselineTotalsByRunTypeMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<BaselineTotalsByRunTypeMap>;

export interface BaselineTotals {
  by_run_type: BaselineTotalsByRunTypeMap;
  all_snapshots: number;
  recently_tolerated: number;
  frequently_tolerated: number;
  currently_quarantined: number;
}
export const BaselineTotals = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    by_run_type: BaselineTotalsByRunTypeMap,
    all_snapshots: S.Number,
    recently_tolerated: S.Number,
    frequently_tolerated: S.Number,
    currently_quarantined: S.Number,
  }),
).annotate({ identifier: "BaselineTotals" }) as any as S.Schema<BaselineTotals>;

export interface BaselineOverview {
  entries: BaselineOverviewEntriesList;
  totals: BaselineTotals;
  truncated: boolean;
  generated_at: string;
}
export const BaselineOverview = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entries: BaselineOverviewEntriesList,
    totals: BaselineTotals,
    truncated: S.Boolean,
    generated_at: S.String,
  }),
).annotate({
  identifier: "BaselineOverview",
}) as any as S.Schema<BaselineOverview>;

export interface GetVisualReviewReposFlakinessRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetVisualReviewReposFlakinessRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/flakiness/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetVisualReviewReposFlakinessRequest",
}) as any as S.Schema<GetVisualReviewReposFlakinessRequest>;

/** Gate-failing runs per day over the last 30 days, oldest first. Always that length, so a fixed time axis can be rendered. */
export type FlakinessEntryDailyHardCountsList = Array<number>;
export const FlakinessEntryDailyHardCountsList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<FlakinessEntryDailyHardCountsList>;

/** Absorbed runs per day over the same 30 days, oldest first. */
export type FlakinessEntryDailySoftCountsList = Array<number>;
export const FlakinessEntryDailySoftCountsList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<FlakinessEntryDailySoftCountsList>;

/** * `broken` - broken * `unstable` - unstable * `at_risk` - at_risk * `noisy` - noisy * `clean` - clean */
export type FlakinessStateEnum =
  | "broken"
  | "unstable"
  | "at_risk"
  | "noisy"
  | "clean";
export const FlakinessStateEnum = /*@__PURE__*/ S.String;

export interface FlakinessEntry {
  /** Distinct alternate hashes the classifier can still match for this snapshot's current baseline. Reads as how many different images this snapshot is currently allowed to produce. Resets when the baseline moves, because tolerations recorded against an old baseline hash can never match again. */
  variant_count: number;
  /** Default-branch runs in the last 7 days where this snapshot failed the gate, so somebody could not merge until it was resolved. Counts every result that is not `unchanged`: a diff over a threshold, a baseline that was never committed or was dropped, and a baseline whose story no longer renders. */
  hard_count: number;
  /** Default-branch runs in the last 7 days where this snapshot rendered differently from its baseline and a toleration absorbed it, blocking nobody. */
  soft_count: number;
  /** Completed default-branch runs of this run type in the last 7 days. The rate denominator, so a reader can tell 2 failures out of 3 runs from 2 out of 300. */
  window_runs: number;
  /** `hard_count` over `window_runs`. The denominator counts every run of this run type, so a snapshot that only started rendering partway through the window reads lower than it is. */
  hard_rate: number;
  /** `soft_count` over `window_runs`. */
  soft_rate: number;
  /** Last default-branch run in the last 30 days that rendered this snapshot differently from its baseline, whether the gate failed or a toleration absorbed it. Reads over the full window rather than the rate span, so a snapshot that stopped failing still reports when it last did. Null when nothing happened at all. */
  last_flaked_at?: string | null;
  /** Mean fraction of pixels that differed across the live variants. Separates sub-pixel noise from a small but real rendering change. */
  avg_diff_percentage?: number | null;
  /** Largest pixel diff any absorbed run in the last 30 days produced. Reads the full window rather than the rate span, because it asks for the worst case a snapshot can produce and more days are better evidence of that. Null when nothing was absorbed. */
  worst_soft_diff_percentage?: number | null;
  /** Fraction of the 2.5% pixel threshold that `worst_soft_diff_percentage` leaves free. A snapshot is absorbed only while it stays under the threshold, so this is what says whether it will keep doing so: 1.0 means it rendered identically every time it was absorbed, 0.0 means it reached the line and only luck kept it on the passing side. Null when nothing was absorbed, which is not the same as full headroom. */
  headroom?: number | null;
  /** Days since the first default-branch run that compared against the current baseline, which is when that baseline took effect. Reads too new for a `broken` snapshot, which records a change against an unmoved baseline on every run. */
  baseline_age_days?: number | null;
  /** Gate-failing runs per day over the last 30 days, oldest first. Always that length, so a fixed time axis can be rendered. */
  daily_hard_counts: FlakinessEntryDailyHardCountsList;
  /** Absorbed runs per day over the same 30 days, oldest first. */
  daily_soft_counts: FlakinessEntryDailySoftCountsList;
  /** Index into the daily series where the baseline moved. Null when it moved before the window opened, which is the common case. */
  baseline_moved_day_index?: number | null;
  /** An urgency ladder, where each rung asks for a different fix. `broken` fails nearly every run, so its baseline is wrong and quarantining it only hides that. `unstable` fails some runs and not others, the classic flake. `at_risk` never fails, but its worst absorbed diff is already touching the threshold, so the next unrelated change turns it red. `noisy` renders variants and absorbs them with room to spare. `clean` matched its baseline on every run in the window. * `broken` - broken * `unstable` - unstable * `at_risk` - at_risk * `noisy` - noisy * `clean` - clean */
  flakiness_state: FlakinessStateEnum;
  /** True when an active quarantine has run out, is about to, or covers a snapshot that has stopped failing the gate. All three mean a human has to extend it or lift it. */
  needs_decision: boolean;
  /** Active quarantine details when `is_quarantined` is true. Null otherwise. */
  quarantine?: BaselineQuarantineSummary | null;
  identifier: string;
  run_type: string;
  browser: string | null;
  thumbnail_hash: string | null;
  width: number | null;
  height: number | null;
  is_quarantined: boolean;
}
export const FlakinessEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    variant_count: S.Number,
    hard_count: S.Number,
    soft_count: S.Number,
    window_runs: S.Number,
    hard_rate: S.Number,
    soft_rate: S.Number,
    last_flaked_at: S.optional(S.NullOr(S.String)),
    avg_diff_percentage: S.optional(S.NullOr(S.Number)),
    worst_soft_diff_percentage: S.optional(S.NullOr(S.Number)),
    headroom: S.optional(S.NullOr(S.Number)),
    baseline_age_days: S.optional(S.NullOr(S.Number)),
    daily_hard_counts: FlakinessEntryDailyHardCountsList,
    daily_soft_counts: FlakinessEntryDailySoftCountsList,
    baseline_moved_day_index: S.optional(S.NullOr(S.Number)),
    flakiness_state: FlakinessStateEnum,
    needs_decision: S.Boolean,
    quarantine: S.optional(S.NullOr(BaselineQuarantineSummary)),
    identifier: S.String,
    run_type: S.String,
    browser: S.NullOr(S.String),
    thumbnail_hash: S.NullOr(S.String),
    width: S.NullOr(S.Number),
    height: S.NullOr(S.Number),
    is_quarantined: S.Boolean,
  }),
).annotate({ identifier: "FlakinessEntry" }) as any as S.Schema<FlakinessEntry>;

export type FlakinessOverviewEntriesList = Array<FlakinessEntry>;
export const FlakinessOverviewEntriesList = /*@__PURE__*/ S.Array(
  FlakinessEntry,
) as any as S.Schema<FlakinessOverviewEntriesList>;

/** Listed identifiers per run type, so one suite's noise can be told from another's. */
export type FlakinessTotalsByRunTypeMap = { [key: string]: number | undefined };
export const FlakinessTotalsByRunTypeMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<FlakinessTotalsByRunTypeMap>;

export interface FlakinessTotals {
  /** Identifiers with an entry in `entries`. */
  listed: number;
  /** Identifiers with a current baseline, listed or not. The denominator that says how much of the repo renders consistently. */
  tracked: number;
  /** Identifiers whose `flakiness_state` is `broken`. */
  broken: number;
  /** Identifiers whose `flakiness_state` is `unstable`. */
  unstable: number;
  /** Identifiers whose `flakiness_state` is `at_risk`. */
  at_risk: number;
  /** Identifiers whose `flakiness_state` is `noisy`. */
  noisy: number;
  /** Identifiers whose `flakiness_state` is `clean`. They are listed because they carry live variants or older history, and reported here so every listed entry is reachable. */
  clean: number;
  /** Listed identifiers per run type, so one suite's noise can be told from another's. */
  by_run_type: FlakinessTotalsByRunTypeMap;
  quarantined: number;
  needs_decision: number;
}
export const FlakinessTotals = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    listed: S.Number,
    tracked: S.Number,
    broken: S.Number,
    unstable: S.Number,
    at_risk: S.Number,
    noisy: S.Number,
    clean: S.Number,
    by_run_type: FlakinessTotalsByRunTypeMap,
    quarantined: S.Number,
    needs_decision: S.Number,
  }),
).annotate({
  identifier: "FlakinessTotals",
}) as any as S.Schema<FlakinessTotals>;

export interface FlakinessOverview {
  entries: FlakinessOverviewEntriesList;
  totals: FlakinessTotals;
  truncated: boolean;
  generated_at: string;
}
export const FlakinessOverview = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entries: FlakinessOverviewEntriesList,
    totals: FlakinessTotals,
    truncated: S.Boolean,
    generated_at: S.String,
  }),
).annotate({
  identifier: "FlakinessOverview",
}) as any as S.Schema<FlakinessOverview>;

export interface GetVisualReviewReposRunsCountRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
}
export const GetVisualReviewReposRunsCountRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      repo_id: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/runs/counts/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetVisualReviewReposRunsCountRequest",
}) as any as S.Schema<GetVisualReviewReposRunsCountRequest>;

export interface ReviewStateCounts {
  needs_review?: number;
  clean?: number;
  processing?: number;
  stale?: number;
}
export const ReviewStateCounts = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    needs_review: S.optional(S.Number),
    clean: S.optional(S.Number),
    processing: S.optional(S.Number),
    stale: S.optional(S.Number),
  }),
).annotate({
  identifier: "ReviewStateCounts",
}) as any as S.Schema<ReviewStateCounts>;

export interface GetVisualReviewReposThumbnailRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  identifier: string;
  /** Narrow the lookup to one run type. The same identifier under two run types is two different images, so omit this only when the caller shows one run type. */
  run_type?: string;
}
export const GetVisualReviewReposThumbnailRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Label()),
      run_type: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/thumbnails/{identifier}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "GetVisualReviewReposThumbnailRequest",
}) as any as S.Schema<GetVisualReviewReposThumbnailRequest>;

export interface GetVisualReviewReposThumbnailResponse {}
export const GetVisualReviewReposThumbnailResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "GetVisualReviewReposThumbnailResponse",
}) as any as S.Schema<GetVisualReviewReposThumbnailResponse>;

export interface GetVisualReviewRunRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetVisualReviewRunRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/runs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetVisualReviewRunRequest",
}) as any as S.Schema<GetVisualReviewRunRequest>;

export interface GetVisualReviewRunsCountRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const GetVisualReviewRunsCountRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/runs/counts/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetVisualReviewRunsCountRequest",
}) as any as S.Schema<GetVisualReviewRunsCountRequest>;

export interface ListVisualReviewReposRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListVisualReviewReposRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListVisualReviewReposRequest",
}) as any as S.Schema<ListVisualReviewReposRequest>;

export type PaginatedRepoListResultsList = Array<Repo>;
export const PaginatedRepoListResultsList = /*@__PURE__*/ S.Array(
  Repo,
) as any as S.Schema<PaginatedRepoListResultsList>;

export interface PaginatedRepoList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedRepoListResultsList;
}
export const PaginatedRepoList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedRepoListResultsList),
  }),
).annotate({
  identifier: "PaginatedRepoList",
}) as any as S.Schema<PaginatedRepoList>;

export interface ListVisualReviewReposQuarantineRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Filter by identifier (returns full history) */
  identifier?: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by run type */
  run_type?: string;
}
export const ListVisualReviewReposQuarantineRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.optional(S.String.pipe(T.Query())),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
      run_type: S.optional(S.String.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/quarantine/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "ListVisualReviewReposQuarantineRequest",
}) as any as S.Schema<ListVisualReviewReposQuarantineRequest>;

export type PaginatedQuarantinedIdentifierEntryListResultsList =
  Array<QuarantinedIdentifierEntry>;
export const PaginatedQuarantinedIdentifierEntryListResultsList =
  /*@__PURE__*/ S.Array(
    QuarantinedIdentifierEntry,
  ) as any as S.Schema<PaginatedQuarantinedIdentifierEntryListResultsList>;

export interface PaginatedQuarantinedIdentifierEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedQuarantinedIdentifierEntryListResultsList;
}
export const PaginatedQuarantinedIdentifierEntryList = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      count: S.optional(S.Number),
      next: S.optional(S.NullOr(S.String)),
      previous: S.optional(S.NullOr(S.String)),
      results: S.optional(PaginatedQuarantinedIdentifierEntryListResultsList),
    }),
).annotate({
  identifier: "PaginatedQuarantinedIdentifierEntryList",
}) as any as S.Schema<PaginatedQuarantinedIdentifierEntryList>;

export interface ListVisualReviewReposRunsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by review state */
  review_state?: string;
  /** Free-text search over branch, commit SHA, run type, and PR number */
  search?: string;
}
export const ListVisualReviewReposRunsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repo_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    review_state: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListVisualReviewReposRunsRequest",
}) as any as S.Schema<ListVisualReviewReposRunsRequest>;

export type PaginatedRunListResultsList = Array<Run>;
export const PaginatedRunListResultsList = /*@__PURE__*/ S.Array(
  Run,
) as any as S.Schema<PaginatedRunListResultsList>;

export interface PaginatedRunList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedRunListResultsList;
}
export const PaginatedRunList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedRunListResultsList),
  }),
).annotate({
  identifier: "PaginatedRunList",
}) as any as S.Schema<PaginatedRunList>;

export interface ListVisualReviewReposSnapshotsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  repo_id: string;
  /** Run type (storybook, playwright) */
  run_type: string;
  /** Snapshot identifier; clients must percent-encode before sending */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListVisualReviewReposSnapshotsRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      repo_id: S.String.pipe(T.Label()),
      run_type: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Label()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/repos/{repo_id}/snapshots/{run_type}/{identifier}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "ListVisualReviewReposSnapshotsRequest",
}) as any as S.Schema<ListVisualReviewReposSnapshotsRequest>;

export interface SnapshotHistoryEntry {
  current_artifact?: Artifact | null;
  run_id?: string;
  snapshot_id?: string;
  result?: string;
  branch?: string;
  commit_sha?: string;
  created_at?: string;
  pr_number?: number | null;
  diff_percentage?: number | null;
  review_state?: string;
  ssim_score?: number | null;
  change_kind?: string;
  size_mismatch?: boolean;
}
export const SnapshotHistoryEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    current_artifact: S.optional(S.NullOr(Artifact)),
    run_id: S.optional(S.String),
    snapshot_id: S.optional(S.String),
    result: S.optional(S.String),
    branch: S.optional(S.String),
    commit_sha: S.optional(S.String),
    created_at: S.optional(S.String),
    pr_number: S.optional(S.NullOr(S.Number)),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    review_state: S.optional(S.String),
    ssim_score: S.optional(S.NullOr(S.Number)),
    change_kind: S.optional(S.String),
    size_mismatch: S.optional(S.Boolean),
  }),
).annotate({
  identifier: "SnapshotHistoryEntry",
}) as any as S.Schema<SnapshotHistoryEntry>;

export type PaginatedSnapshotHistoryEntryListResultsList =
  Array<SnapshotHistoryEntry>;
export const PaginatedSnapshotHistoryEntryListResultsList =
  /*@__PURE__*/ S.Array(
    SnapshotHistoryEntry,
  ) as any as S.Schema<PaginatedSnapshotHistoryEntryListResultsList>;

export interface PaginatedSnapshotHistoryEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSnapshotHistoryEntryListResultsList;
}
export const PaginatedSnapshotHistoryEntryList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSnapshotHistoryEntryListResultsList),
  }),
).annotate({
  identifier: "PaginatedSnapshotHistoryEntryList",
}) as any as S.Schema<PaginatedSnapshotHistoryEntryList>;

export interface ListVisualReviewRunsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Filter by branch name */
  branch?: string;
  /** Filter by full commit SHA */
  commit_sha?: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by GitHub PR number */
  pr_number?: number;
  /** Filter by review state */
  review_state?: string;
  /** Free-text search over branch, commit SHA, run type, and PR number */
  search?: string;
}
export const ListVisualReviewRunsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    branch: S.optional(S.String.pipe(T.Query())),
    commit_sha: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    pr_number: S.optional(S.Number.pipe(T.Query())),
    review_state: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/visual_review/runs/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListVisualReviewRunsRequest",
}) as any as S.Schema<ListVisualReviewRunsRequest>;

export interface ListVisualReviewRunsSnapshotHistoryRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshot identifier */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListVisualReviewRunsSnapshotHistoryRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Query()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/snapshot-history/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "ListVisualReviewRunsSnapshotHistoryRequest",
  }) as any as S.Schema<ListVisualReviewRunsSnapshotHistoryRequest>;

export interface ListVisualReviewRunsSnapshotsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Whether to include snapshots whose identifier is currently quarantined. Defaults to false: quarantined snapshots are excluded from results and reported in quarantined_count instead, since they are noise when reviewing real changes. */
  include_quarantined?: boolean;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListVisualReviewRunsSnapshotsRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      include_quarantined: S.optional(S.Boolean.pipe(T.Query())),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/snapshots/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "ListVisualReviewRunsSnapshotsRequest",
}) as any as S.Schema<ListVisualReviewRunsSnapshotsRequest>;

export type PaginatedSnapshotListResultsList = Array<Snapshot>;
export const PaginatedSnapshotListResultsList = /*@__PURE__*/ S.Array(
  Snapshot,
) as any as S.Schema<PaginatedSnapshotListResultsList>;

export interface PaginatedSnapshotList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSnapshotListResultsList;
  /** Count of this run's snapshots whose identifier is currently quarantined. Excluded from results unless include_quarantined=true is passed. */
  quarantined_count?: number;
}
export const PaginatedSnapshotList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSnapshotListResultsList),
    quarantined_count: S.optional(S.Number),
  }),
).annotate({
  identifier: "PaginatedSnapshotList",
}) as any as S.Schema<PaginatedSnapshotList>;

export interface ListVisualReviewRunsToleratedHashesRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshot identifier */
  identifier: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListVisualReviewRunsToleratedHashesRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      identifier: S.String.pipe(T.Query()),
      limit: S.optional(S.Number.pipe(T.Query())),
      offset: S.optional(S.Number.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/tolerated-hashes/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "ListVisualReviewRunsToleratedHashesRequest",
  }) as any as S.Schema<ListVisualReviewRunsToleratedHashesRequest>;

export interface ToleratedHashEntry {
  id?: string;
  alternate_hash?: string;
  baseline_hash?: string;
  reason?: string;
  diff_percentage?: number | null;
  created_at?: string;
  source_run_id?: string | null;
}
export const ToleratedHashEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    alternate_hash: S.optional(S.String),
    baseline_hash: S.optional(S.String),
    reason: S.optional(S.String),
    diff_percentage: S.optional(S.NullOr(S.Number)),
    created_at: S.optional(S.String),
    source_run_id: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "ToleratedHashEntry",
}) as any as S.Schema<ToleratedHashEntry>;

export type PaginatedToleratedHashEntryListResultsList =
  Array<ToleratedHashEntry>;
export const PaginatedToleratedHashEntryListResultsList = /*@__PURE__*/ S.Array(
  ToleratedHashEntry,
) as any as S.Schema<PaginatedToleratedHashEntryListResultsList>;

export interface PaginatedToleratedHashEntryList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedToleratedHashEntryListResultsList;
}
export const PaginatedToleratedHashEntryList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedToleratedHashEntryListResultsList),
  }),
).annotate({
  identifier: "PaginatedToleratedHashEntryList",
}) as any as S.Schema<PaginatedToleratedHashEntryList>;

export type UpdateVisualReviewReposPartialRequestBaselineFilePathsMap = {
  [key: string]: string | undefined;
};
export const UpdateVisualReviewReposPartialRequestBaselineFilePathsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<UpdateVisualReviewReposPartialRequestBaselineFilePathsMap>;

export interface UpdateVisualReviewReposPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  baseline_file_paths?: UpdateVisualReviewReposPartialRequestBaselineFilePathsMap | null;
  enable_pr_comments?: boolean | null;
}
export const UpdateVisualReviewReposPartialRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      baseline_file_paths: S.optional(
        S.NullOr(UpdateVisualReviewReposPartialRequestBaselineFilePathsMap),
      ),
      enable_pr_comments: S.optional(S.NullOr(S.Boolean)),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/api/projects/{project_id}/visual_review/repos/{id}/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "UpdateVisualReviewReposPartialRequest",
}) as any as S.Schema<UpdateVisualReviewReposPartialRequest>;

export type VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList =
  Array<SnapshotManifestItem>;
export const VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList =
  /*@__PURE__*/ S.Array(
    SnapshotManifestItem,
  ) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList>;

export type VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap = {
  [key: string]: string | undefined;
};
export const VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap>;

export interface VisualReviewRunsAddSnapshotsCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  snapshots?: VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList;
  baseline_hashes?: VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap;
}
export const VisualReviewRunsAddSnapshotsCreateRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshots: S.optional(
        VisualReviewRunsAddSnapshotsCreateRequestSnapshotsList,
      ),
      baseline_hashes: S.optional(
        VisualReviewRunsAddSnapshotsCreateRequestBaselineHashesMap,
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/add-snapshots/",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "VisualReviewRunsAddSnapshotsCreateRequest",
  }) as any as S.Schema<VisualReviewRunsAddSnapshotsCreateRequest>;

export type AddSnapshotsResultUploadsList = Array<UploadTarget>;
export const AddSnapshotsResultUploadsList = /*@__PURE__*/ S.Array(
  UploadTarget,
) as any as S.Schema<AddSnapshotsResultUploadsList>;

export interface AddSnapshotsResult {
  added?: number;
  uploads?: AddSnapshotsResultUploadsList;
}
export const AddSnapshotsResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    added: S.optional(S.Number),
    uploads: S.optional(AddSnapshotsResultUploadsList),
  }),
).annotate({
  identifier: "AddSnapshotsResult",
}) as any as S.Schema<AddSnapshotsResult>;

export interface ApproveSnapshotInput {
  /** The snapshot identifier to approve (e.g. Storybook story id plus theme). */
  identifier?: string;
  /** The content hash of the new baseline image to record for this identifier. */
  new_hash?: string;
}
export const ApproveSnapshotInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifier: S.optional(S.String),
    new_hash: S.optional(S.String),
  }),
).annotate({
  identifier: "ApproveSnapshotInput",
}) as any as S.Schema<ApproveSnapshotInput>;

/** Snapshots to mark reviewed, each with `identifier` and `new_hash`. This only records the review in the database (the per-snapshot "Accept change" action) — it does not change the baseline or the GitHub gate. Commit the baseline and green the gate with the finalize endpoint. */
export type VisualReviewRunsApproveCreateRequestSnapshotsList =
  Array<ApproveSnapshotInput>;
export const VisualReviewRunsApproveCreateRequestSnapshotsList =
  /*@__PURE__*/ S.Array(
    ApproveSnapshotInput,
  ) as any as S.Schema<VisualReviewRunsApproveCreateRequestSnapshotsList>;

export interface VisualReviewRunsApproveCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Snapshots to mark reviewed, each with `identifier` and `new_hash`. This only records the review in the database (the per-snapshot "Accept change" action) — it does not change the baseline or the GitHub gate. Commit the baseline and green the gate with the finalize endpoint. */
  snapshots: VisualReviewRunsApproveCreateRequestSnapshotsList;
}
export const VisualReviewRunsApproveCreateRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      project_id: S.String.pipe(T.Label()),
      id: S.String.pipe(T.Label()),
      snapshots: VisualReviewRunsApproveCreateRequestSnapshotsList,
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/api/projects/{project_id}/visual_review/runs/{id}/approve/",
        code: 200,
      }),
    ),
).annotate({
  identifier: "VisualReviewRunsApproveCreateRequest",
}) as any as S.Schema<VisualReviewRunsApproveCreateRequest>;

export type CreateVisualReviewReposError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Create a new repo. */
export const createVisualReviewRepos: API.OperationMethod<
  CreateVisualReviewReposRequest,
  Repo,
  CreateVisualReviewReposError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewReposRequest,
  output: Repo,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewReposQuarantineError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Quarantine a snapshot identifier for a specific run type. */
export const createVisualReviewReposQuarantine: API.OperationMethod<
  CreateVisualReviewReposQuarantineRequest,
  QuarantinedIdentifierEntry,
  CreateVisualReviewReposQuarantineError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewReposQuarantineRequest,
  output: QuarantinedIdentifierEntry,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewReposQuarantineExpireError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Expire all active quarantine entries for an identifier. */
export const createVisualReviewReposQuarantineExpire: API.OperationMethod<
  CreateVisualReviewReposQuarantineExpireRequest,
  CreateVisualReviewReposQuarantineExpireResponse,
  CreateVisualReviewReposQuarantineExpireError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewReposQuarantineExpireRequest,
  output: CreateVisualReviewReposQuarantineExpireResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewRunError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Create a new run from a CI manifest. */
export const createVisualReviewRun: API.OperationMethod<
  CreateVisualReviewRunRequest,
  CreateRunResult,
  CreateVisualReviewRunError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewRunRequest,
  output: CreateRunResult,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewRunsCompleteError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Complete a run: detect removals, verify uploads, trigger diff processing. */
export const createVisualReviewRunsComplete: API.OperationMethod<
  CreateVisualReviewRunsCompleteRequest,
  Run,
  CreateVisualReviewRunsCompleteError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewRunsCompleteRequest,
  output: Run,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewRunsFinalizeError = PosthogOpError;
/** Finalize a fully-reviewed run: commit the approved baseline and green the gate. Commits exactly the snapshots approved in the DB (tolerated ones keep their baseline) and only succeeds once every changed/new snapshot is resolved. With approve_all=true, any still-pending changed/new snapshot is approved first; quarantined snapshots are skipped, but a quarantined NEW snapshot approved by identifier is still committed. With commit_to_github=false the server returns the signed baseline YAML instead of committing it. */
export const createVisualReviewRunsFinalize: API.OperationMethod<
  CreateVisualReviewRunsFinalizeRequest,
  FinalizeResult,
  CreateVisualReviewRunsFinalizeError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewRunsFinalizeRequest,
  output: FinalizeResult,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewRunsRecomputeError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Re-evaluate quarantine and counts, update commit status, and optionally rerun the CI job. */
export const createVisualReviewRunsRecompute: API.OperationMethod<
  CreateVisualReviewRunsRecomputeRequest,
  RecomputeResult,
  CreateVisualReviewRunsRecomputeError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewRunsRecomputeRequest,
  output: RecomputeResult,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateVisualReviewRunsTolerateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Mark a changed snapshot as a known tolerated alternate. */
export const createVisualReviewRunsTolerate: API.OperationMethod<
  CreateVisualReviewRunsTolerateRequest,
  Snapshot,
  CreateVisualReviewRunsTolerateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVisualReviewRunsTolerateRequest,
  output: Snapshot,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewReposError = Forbidden | NotFound | PosthogOpError;
/** Get a repo by ID. */
export const getVisualReviewRepos: API.OperationMethod<
  GetVisualReviewReposRequest,
  Repo,
  GetVisualReviewReposError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewReposRequest,
  output: Repo,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewReposBaselineError = PosthogOpError;
/** Snapshots overview for a repo: every identifier with a current baseline (latest non-superseded master/main run per run_type), plus tolerate counts, active quarantine state, and a 30-day stability sparkline. Capped at 5000 entries — sets `truncated` and returns the most recently active when exceeded. Filtering / faceting / search are all done client-side; this endpoint takes no filter query params. */
export const getVisualReviewReposBaseline: API.OperationMethod<
  GetVisualReviewReposBaselineRequest,
  BaselineOverview,
  GetVisualReviewReposBaselineError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewReposBaselineRequest,
  output: BaselineOverview,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewReposFlakinessError = PosthogOpError;
/** Snapshots in a repo whose rendering cannot be trusted: those that failed the gate or were absorbed by a toleration on a recent default-branch run, and those under an active quarantine. Everything else is omitted, so this is far smaller than the baselines universe; `totals.tracked` gives the full denominator. Each entry carries the share of the last 7 days of default-branch runs that failed the gate (`hard_rate`) and the share a toleration absorbed (`soft_rate`), plus `headroom`, the fraction of the diff threshold its worst absorbed run leaves free. Capped at 2000 entries, which sets `truncated`. Filtering, faceting and search are done client-side; this endpoint takes no filter query params. */
export const getVisualReviewReposFlakiness: API.OperationMethod<
  GetVisualReviewReposFlakinessRequest,
  FlakinessOverview,
  GetVisualReviewReposFlakinessError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewReposFlakinessRequest,
  output: FlakinessOverview,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewReposRunsCountError = PosthogOpError;
/** Review state counts for runs in this repo. */
export const getVisualReviewReposRunsCount: API.OperationMethod<
  GetVisualReviewReposRunsCountRequest,
  ReviewStateCounts,
  GetVisualReviewReposRunsCountError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewReposRunsCountRequest,
  output: ReviewStateCounts,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewReposThumbnailError = PosthogOpError;
/** Serve a snapshot thumbnail by identifier. Returns WebP with ETag caching. */
export const getVisualReviewReposThumbnail: API.OperationMethod<
  GetVisualReviewReposThumbnailRequest,
  GetVisualReviewReposThumbnailResponse,
  GetVisualReviewReposThumbnailError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewReposThumbnailRequest,
  output: GetVisualReviewReposThumbnailResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewRunError = Forbidden | NotFound | PosthogOpError;
/** Get run status and summary. */
export const getVisualReviewRun: API.OperationMethod<
  GetVisualReviewRunRequest,
  Run,
  GetVisualReviewRunError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewRunRequest,
  output: Run,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetVisualReviewRunsCountError =
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Review state counts for the runs list. */
export const getVisualReviewRunsCount: API.OperationMethod<
  GetVisualReviewRunsCountRequest,
  ReviewStateCounts,
  GetVisualReviewRunsCountError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVisualReviewRunsCountRequest,
  output: ReviewStateCounts,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewReposError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List all projects for the team. */
export const listVisualReviewRepos: API.OperationMethod<
  ListVisualReviewReposRequest,
  PaginatedRepoList,
  ListVisualReviewReposError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewReposRequest,
  output: PaginatedRepoList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewReposQuarantineError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List quarantined identifiers. Without filter: active only. With identifier: full history. */
export const listVisualReviewReposQuarantine: API.OperationMethod<
  ListVisualReviewReposQuarantineRequest,
  PaginatedQuarantinedIdentifierEntryList,
  ListVisualReviewReposQuarantineError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewReposQuarantineRequest,
  output: PaginatedQuarantinedIdentifierEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewReposRunsError = PosthogOpError;
/** List runs in this repo, optionally filtered by review state and free-text search. */
export const listVisualReviewReposRuns: API.OperationMethod<
  ListVisualReviewReposRunsRequest,
  PaginatedRunList,
  ListVisualReviewReposRunsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewReposRunsRequest,
  output: PaginatedRunList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewReposSnapshotsError = PosthogOpError;
/** Deduped baseline timeline for a snapshot identity. Newest first. */
export const listVisualReviewReposSnapshots: API.OperationMethod<
  ListVisualReviewReposSnapshotsRequest,
  PaginatedSnapshotHistoryEntryList,
  ListVisualReviewReposSnapshotsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewReposSnapshotsRequest,
  output: PaginatedSnapshotHistoryEntryList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewRunsError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List runs for the team, optionally filtered by review state, PR number, commit SHA, branch, or free-text search. */
export const listVisualReviewRuns: API.OperationMethod<
  ListVisualReviewRunsRequest,
  PaginatedRunList,
  ListVisualReviewRunsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewRunsRequest,
  output: PaginatedRunList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewRunsSnapshotHistoryError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Recent change history for a snapshot identifier across runs. */
export const listVisualReviewRunsSnapshotHistory: API.OperationMethod<
  ListVisualReviewRunsSnapshotHistoryRequest,
  PaginatedSnapshotHistoryEntryList,
  ListVisualReviewRunsSnapshotHistoryError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewRunsSnapshotHistoryRequest,
  output: PaginatedSnapshotHistoryEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewRunsSnapshotsError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Get a run's snapshots with diff results, excluding quarantined ones by default. */
export const listVisualReviewRunsSnapshots: API.OperationMethod<
  ListVisualReviewRunsSnapshotsRequest,
  PaginatedSnapshotList,
  ListVisualReviewRunsSnapshotsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewRunsSnapshotsRequest,
  output: PaginatedSnapshotList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListVisualReviewRunsToleratedHashesError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** List known tolerated hashes for a snapshot identifier. */
export const listVisualReviewRunsToleratedHashes: API.OperationMethod<
  ListVisualReviewRunsToleratedHashesRequest,
  PaginatedToleratedHashEntryList,
  ListVisualReviewRunsToleratedHashesError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVisualReviewRunsToleratedHashesRequest,
  output: PaginatedToleratedHashEntryList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateVisualReviewReposPartialError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Update a repo's settings. */
export const updateVisualReviewReposPartial: API.OperationMethod<
  UpdateVisualReviewReposPartialRequest,
  Repo,
  UpdateVisualReviewReposPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateVisualReviewReposPartialRequest,
  output: Repo,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsAddSnapshotsCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Add a batch of snapshots to a pending run (shard-based flow). */
export const visualReviewRunsAddSnapshotsCreate: API.OperationMethod<
  VisualReviewRunsAddSnapshotsCreateRequest,
  AddSnapshotsResult,
  VisualReviewRunsAddSnapshotsCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsAddSnapshotsCreateRequest,
  output: AddSnapshotsResult,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type VisualReviewRunsApproveCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Mark snapshots reviewed (DB only). Records the per-snapshot "Accept change" decision. Does not commit the baseline or change the GitHub gate — call finalize to ship the run. Works on a quarantined snapshot too: a quarantined NEW snapshot approved here is committed by finalize, which gives a quarantined story a baseline entry without lifting the quarantine. */
export const visualReviewRunsApproveCreate: API.OperationMethod<
  VisualReviewRunsApproveCreateRequest,
  Run,
  VisualReviewRunsApproveCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VisualReviewRunsApproveCreateRequest,
  output: Run,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
