// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-vercel/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  VercelProtocol,
  type VercelOpError,
  type VercelOpContext,
} from "../protocol.ts";
import * as Retry from "../retry.ts";

export type { VercelOpError, VercelOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** Field to sort by. */
export type GetSandboxesRequestSortBy =
  | "createdAt"
  | "name"
  | "statusUpdatedAt"
  | "currentSnapshotId";
export const GetSandboxesRequestSortBy = /*@__PURE__*/ S.String;

/** Sort direction. Defaults to desc. */
export type GetSandboxesRequestSortOrder = "asc" | "desc";
export const GetSandboxesRequestSortOrder = /*@__PURE__*/ S.String;

/** Filter named sandboxes by status. Only valid when sortBy is createdAt. */
export type GetSandboxesRequestStatus = "running" | "stopping" | "stopped";
export const GetSandboxesRequestStatus = /*@__PURE__*/ S.String;

export type GetSandboxesRequestTagsCase1List = Array<string>;
export const GetSandboxesRequestTagsCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<GetSandboxesRequestTagsCase1List>;

/** Filter sandboxes by tag. Format: \"key:value\". Only one tag filter is supported at a time. */
export type GetSandboxesRequestTags = string | GetSandboxesRequestTagsCase1List;
export const GetSandboxesRequestTags =
  /*@__PURE__*/ S.Unknown as any as S.Schema<GetSandboxesRequestTags>;

export interface GetSandboxesRequest {
  /** The unique identifier or name of the project to list named sandboxes for. */
  project?: string;
  /** Maximum number of named sandboxes to return in the response. Used for pagination. */
  limit?: number;
  /** Field to sort by. */
  sortBy?: GetSandboxesRequestSortBy | (string & {});
  /** Filter named sandboxes whose name starts with this prefix. Only valid when sortBy=name. */
  namePrefix?: string;
  /** Opaque pagination cursor from a previous response. */
  cursor?: string;
  /** Sort direction. Defaults to desc. */
  sortOrder?: GetSandboxesRequestSortOrder | (string & {});
  /** Filter named sandboxes by status. Only valid when sortBy is createdAt. */
  status?: GetSandboxesRequestStatus | (string & {});
  /** Filter sandboxes by tag. Format: \"key:value\". Only one tag filter is supported at a time. */
  tags?: GetSandboxesRequestTags;
}
export const GetSandboxesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    sortBy: S.optional(GetSandboxesRequestSortBy.pipe(T.Query())),
    namePrefix: S.optional(S.String.pipe(T.Query())),
    cursor: S.optional(S.String.pipe(T.Query())),
    sortOrder: S.optional(GetSandboxesRequestSortOrder.pipe(T.Query())),
    status: S.optional(GetSandboxesRequestStatus.pipe(T.Query())),
    tags: S.optional(GetSandboxesRequestTags.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/sandboxes", code: 200 })),
).annotate({
  identifier: "GetSandboxesRequest",
}) as any as S.Schema<GetSandboxesRequest>;

/** The status of the current sandbox. */
export type NamedSandboxStatus = "running" | "stopped" | "stopping";
export const NamedSandboxStatus = /*@__PURE__*/ S.String;

/** The regions the sandbox fails over to. Empty when it does not fail over. */
export type NamedSandboxFailoverRegionsItem =
  | "arn1"
  | "bom1"
  | "cdg1"
  | "cle1"
  | "cpt1"
  | "dub1"
  | "fra1"
  | "gru1"
  | "hkg1"
  | "hnd1"
  | "iad1"
  | "icn1"
  | "kix1"
  | "lhr1"
  | "pdx1"
  | "sfo1"
  | "sin1"
  | "syd1"
  | "yul1";
export const NamedSandboxFailoverRegionsItem = /*@__PURE__*/ S.String;

/** The regions the sandbox fails over to. Empty when it does not fail over. */
export type NamedSandboxFailoverRegionsList =
  Array<NamedSandboxFailoverRegionsItem>;
export const NamedSandboxFailoverRegionsList = /*@__PURE__*/ S.Array(
  NamedSandboxFailoverRegionsItem,
) as any as S.Schema<NamedSandboxFailoverRegionsList>;

/** Keep-last snapshot configuration. */
export interface NamedSandboxKeepLastSnapshots {
  /** Number of most recent snapshots to keep. */
  count: number;
  /** Expiration time in milliseconds for kept snapshots. */
  expiration?: number;
  /** Whether to immediately delete evicted snapshots. */
  deleteEvicted: boolean;
}
export const NamedSandboxKeepLastSnapshots = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    expiration: S.optional(S.Number),
    deleteEvicted: S.Boolean,
  }),
).annotate({
  identifier: "NamedSandboxKeepLastSnapshots",
}) as any as S.Schema<NamedSandboxKeepLastSnapshots>;

export type NamedSandboxNetworkPolicyMode =
  | "allow-all"
  | "custom"
  | "default-allow"
  | "default-deny"
  | "deny-all";
export const NamedSandboxNetworkPolicyMode = /*@__PURE__*/ S.String;

export type NamedSandboxNetworkPolicyAllowedDomainsList = Array<string>;
export const NamedSandboxNetworkPolicyAllowedDomainsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<NamedSandboxNetworkPolicyAllowedDomainsList>;

export type NamedSandboxNetworkPolicyAllowedCIDRsList = Array<string>;
export const NamedSandboxNetworkPolicyAllowedCIDRsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<NamedSandboxNetworkPolicyAllowedCIDRsList>;

export type NamedSandboxNetworkPolicyDeniedCIDRsList = Array<string>;
export const NamedSandboxNetworkPolicyDeniedCIDRsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<NamedSandboxNetworkPolicyDeniedCIDRsList>;

/** Network policy configuration. */
export interface NamedSandboxNetworkPolicy {
  mode: NamedSandboxNetworkPolicyMode;
  allowedDomains?: NamedSandboxNetworkPolicyAllowedDomainsList;
  allowedCIDRs?: NamedSandboxNetworkPolicyAllowedCIDRsList;
  deniedCIDRs?: NamedSandboxNetworkPolicyDeniedCIDRsList;
  s3Key?: string;
}
export const NamedSandboxNetworkPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    mode: NamedSandboxNetworkPolicyMode,
    allowedDomains: S.optional(NamedSandboxNetworkPolicyAllowedDomainsList),
    allowedCIDRs: S.optional(NamedSandboxNetworkPolicyAllowedCIDRsList),
    deniedCIDRs: S.optional(NamedSandboxNetworkPolicyDeniedCIDRsList),
    s3Key: S.optional(S.String),
  }),
).annotate({
  identifier: "NamedSandboxNetworkPolicy",
}) as any as S.Schema<NamedSandboxNetworkPolicy>;

/** Key-value tags attached to the named sandbox. */
export type NamedSandboxTagsMap = { [key: string]: string | undefined };
export const NamedSandboxTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<NamedSandboxTagsMap>;

export type NamedSandboxMountsValueMode = "read-only" | "read-write";
export const NamedSandboxMountsValueMode = /*@__PURE__*/ S.String;

/** Key-value pairs of mount path and drive. */
export interface NamedSandboxMountsValue {
  drive: string;
  mode?: NamedSandboxMountsValueMode;
}
export const NamedSandboxMountsValue = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    drive: S.String,
    mode: S.optional(NamedSandboxMountsValueMode),
  }),
).annotate({
  identifier: "NamedSandboxMountsValue",
}) as any as S.Schema<NamedSandboxMountsValue>;

/** Key-value pairs of mount path and drive. */
export type NamedSandboxMountsMap = {
  [key: string]: NamedSandboxMountsValue | undefined;
};
export const NamedSandboxMountsMap = /*@__PURE__*/ S.Record(
  S.String,
  NamedSandboxMountsValue,
) as any as S.Schema<NamedSandboxMountsMap>;

/** This object contains information related to a Vercel NamedSandbox. */
export interface NamedSandbox {
  /** The unique identifier of the sandbox. */
  name: string;
  /** Current snapshot ID that the named sandbox is pointing to. */
  currentSnapshotId?: string;
  /** Current session ID the sandbox is pointing to. */
  currentSessionId: string;
  /** The status of the current sandbox. */
  status: NamedSandboxStatus;
  /** The time when the sandbox status was last updated, in milliseconds since the epoch. */
  statusUpdatedAt: number;
  /** Whether the sandbox persists its state across restarts via automatic snapshots. */
  persistent: boolean;
  /** The region the sandbox is pinned to: the region stored on the sandbox, otherwise the platform default. Where a running session actually landed is reported by `session.region`. */
  region?: string;
  /** The regions the sandbox fails over to. Empty when it does not fail over. */
  failoverRegions?: NamedSandboxFailoverRegionsList;
  /** Number of virtual CPUs allocated. */
  vcpus?: number;
  /** Memory allocated in MB. */
  memory?: number;
  /** Runtime identifier. */
  runtime?: string;
  /** Digest-pinned reference of the container image the sandbox was created from, when it was created from an image ("{repository}@{manifestDigest}"). */
  image?: string;
  /** Timeout in milliseconds. */
  timeout?: number;
  /** Default snapshot expiration time in milliseconds. 0 means no expiration. */
  snapshotExpiration?: number;
  /** Keep-last snapshot configuration. */
  keepLastSnapshots?: NamedSandboxKeepLastSnapshots;
  /** Network policy configuration. */
  networkPolicy?: NamedSandboxNetworkPolicy;
  /** Cumulative egress bytes across all sandbox runs. */
  totalEgressBytes?: number;
  /** Cumulative ingress bytes across all sandbox runs. */
  totalIngressBytes?: number;
  /** Cumulative active CPU duration in milliseconds across all sandbox runs. */
  totalActiveCpuDurationMs?: number;
  /** Cumulative wall-clock duration in milliseconds across all sandbox runs. */
  totalDurationMs?: number;
  /** The working directory of the sandbox. */
  cwd?: string;
  /** Key-value tags attached to the named sandbox. */
  tags?: NamedSandboxTagsMap;
  /** Key-value pairs of mount path and drive. */
  mounts?: NamedSandboxMountsMap;
  /** The time when the named sandbox was created, in milliseconds since the epoch. */
  createdAt: number;
  /** The time when the named sandbox was last updated, in milliseconds since the epoch. */
  updatedAt: number;
  /** The time at which the currently running sandbox will time out, in milliseconds since the epoch. Only present while a session is running. */
  expiresAt?: number;
}
export const NamedSandbox = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    currentSnapshotId: S.optional(S.String),
    currentSessionId: S.String,
    status: NamedSandboxStatus,
    statusUpdatedAt: S.Number,
    persistent: S.Boolean,
    region: S.optional(S.String),
    failoverRegions: S.optional(NamedSandboxFailoverRegionsList),
    vcpus: S.optional(S.Number),
    memory: S.optional(S.Number),
    runtime: S.optional(S.String),
    image: S.optional(S.String),
    timeout: S.optional(S.Number),
    snapshotExpiration: S.optional(S.Number),
    keepLastSnapshots: S.optional(NamedSandboxKeepLastSnapshots),
    networkPolicy: S.optional(NamedSandboxNetworkPolicy),
    totalEgressBytes: S.optional(S.Number),
    totalIngressBytes: S.optional(S.Number),
    totalActiveCpuDurationMs: S.optional(S.Number),
    totalDurationMs: S.optional(S.Number),
    cwd: S.optional(S.String),
    tags: S.optional(NamedSandboxTagsMap),
    mounts: S.optional(NamedSandboxMountsMap),
    createdAt: S.Number,
    updatedAt: S.Number,
    expiresAt: S.optional(S.Number),
  }),
).annotate({ identifier: "NamedSandbox" }) as any as S.Schema<NamedSandbox>;

export type GetSandboxesResponseSandboxesList = Array<NamedSandbox>;
export const GetSandboxesResponseSandboxesList = /*@__PURE__*/ S.Array(
  NamedSandbox,
) as any as S.Schema<GetSandboxesResponseSandboxesList>;

export interface GetSandboxesResponsePagination {
  count: number;
  next: string | null;
}
export const GetSandboxesResponsePagination = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.NullOr(S.String),
  }),
).annotate({
  identifier: "GetSandboxesResponsePagination",
}) as any as S.Schema<GetSandboxesResponsePagination>;

export interface GetSandboxesResponse {
  sandboxes: GetSandboxesResponseSandboxesList;
  pagination: GetSandboxesResponsePagination;
}
export const GetSandboxesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    sandboxes: GetSandboxesResponseSandboxesList,
    pagination: GetSandboxesResponsePagination,
  }),
).annotate({
  identifier: "GetSandboxesResponse",
}) as any as S.Schema<GetSandboxesResponse>;

export type GetSandboxesError =
  | BadRequest
  | Forbidden
  | NotFound
  | VercelOpError;
export const getSandboxes: API.OperationMethod<
  GetSandboxesRequest,
  GetSandboxesResponse,
  GetSandboxesError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSandboxesRequest,
  output: GetSandboxesResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));
