// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/azure-rest-api-specs). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  AzureProtocol,
  type AzureOpError,
  type AzureOpContext,
} from "../protocol.ts";
import { UnknownAzureError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { AzureOpError, AzureOpContext };

/** Resource tags. */
export type CreateAzureBareMetalStorageInstanceRequestTagsMap = {
  [key: string]: string | undefined;
};
export const CreateAzureBareMetalStorageInstanceRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CreateAzureBareMetalStorageInstanceRequestTagsMap>;

/** State of provisioning of the AzureBareMetalStorageInstance */
export type StoragePropertiesProvisioningState =
  | "Accepted"
  | "Creating"
  | "Updating"
  | "Failed"
  | "Succeeded"
  | "Deleting"
  | "Canceled"
  | "Migrating";
export const StoragePropertiesProvisioningState = S.String;

/** Describes the billing related details of the AzureBareMetalStorageInstance. */
export interface StorageBillingProperties {
  /** the billing mode for the storage instance */
  billingMode?: string;
  /** the SKU type that is provisioned */
  azureBareMetalStorageInstanceSize?: string;
}
export const StorageBillingProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    billingMode: S.optional(S.String),
    azureBareMetalStorageInstanceSize: S.optional(S.String),
  }),
).annotate({
  identifier: "StorageBillingProperties",
}) as any as S.Schema<StorageBillingProperties>;

/** described the storage properties of the azure baremetalstorage instance */
export interface StorageProperties {
  /** State of provisioning of the AzureBareMetalStorageInstance */
  provisioningState?: StoragePropertiesProvisioningState | (string & {});
  /** the offering type for which the resource is getting provisioned */
  offeringType?: string;
  /** the storage protocol for which the resource is getting provisioned */
  storageType?: string;
  /** the kind of storage instance */
  generation?: string;
  /** the hardware type of the storage instance */
  hardwareType?: string;
  /** the workload for which the resource is getting provisioned */
  workloadType?: string;
  /** the billing related information for the resource */
  storageBillingProperties?: StorageBillingProperties;
}
export const StorageProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    provisioningState: S.optional(StoragePropertiesProvisioningState),
    offeringType: S.optional(S.String),
    storageType: S.optional(S.String),
    generation: S.optional(S.String),
    hardwareType: S.optional(S.String),
    workloadType: S.optional(S.String),
    storageBillingProperties: S.optional(StorageBillingProperties),
  }),
).annotate({
  identifier: "StorageProperties",
}) as any as S.Schema<StorageProperties>;

/** Describes the properties of an AzureBareMetalStorageInstance. */
export interface AzureBareMetalStorageInstanceProperties {
  /** Specifies the AzureBareMetaStorageInstance unique ID. */
  azureBareMetalStorageInstanceUniqueIdentifier?: string;
  /** Specifies the storage properties for the AzureBareMetalStorage instance. */
  storageProperties?: StorageProperties;
}
export const AzureBareMetalStorageInstanceProperties = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      azureBareMetalStorageInstanceUniqueIdentifier: S.optional(S.String),
      storageProperties: S.optional(StorageProperties),
    }),
).annotate({
  identifier: "AzureBareMetalStorageInstanceProperties",
}) as any as S.Schema<AzureBareMetalStorageInstanceProperties>;

export interface CreateAzureBareMetalStorageInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the AzureBareMetalStorage on Azure instance. */
  azureBareMetalStorageInstanceName: string;
  /** Resource tags. */
  tags?: CreateAzureBareMetalStorageInstanceRequestTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetalStorageInstance properties */
  properties?: AzureBareMetalStorageInstanceProperties;
}
export const CreateAzureBareMetalStorageInstanceRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureBareMetalStorageInstanceName: S.String.pipe(T.Label()),
      tags: S.optional(CreateAzureBareMetalStorageInstanceRequestTagsMap),
      location: S.String,
      properties: S.optional(AzureBareMetalStorageInstanceProperties),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances/{azureBareMetalStorageInstanceName}",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "CreateAzureBareMetalStorageInstanceRequest",
  }) as any as S.Schema<CreateAzureBareMetalStorageInstanceRequest>;

/** Resource tags. */
export type CreateAzureBareMetalStorageInstanceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CreateAzureBareMetalStorageInstanceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CreateAzureBareMetalStorageInstanceResponseTagsMap>;

/** The type of identity that created the resource. */
export type CreateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const CreateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  S.String;

/** The type of identity that last modified the resource. */
export type CreateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const CreateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface CreateAzureBareMetalStorageInstanceResponseSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: CreateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: CreateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const CreateAzureBareMetalStorageInstanceResponseSystemData =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        CreateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        CreateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
  ).annotate({
    identifier: "CreateAzureBareMetalStorageInstanceResponseSystemData",
  }) as any as S.Schema<CreateAzureBareMetalStorageInstanceResponseSystemData>;

export interface CreateAzureBareMetalStorageInstanceResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: CreateAzureBareMetalStorageInstanceResponseTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetalStorageInstance properties */
  properties?: AzureBareMetalStorageInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: CreateAzureBareMetalStorageInstanceResponseSystemData;
}
export const CreateAzureBareMetalStorageInstanceResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      tags: S.optional(CreateAzureBareMetalStorageInstanceResponseTagsMap),
      location: S.String,
      properties: S.optional(AzureBareMetalStorageInstanceProperties),
      systemData: S.optional(
        CreateAzureBareMetalStorageInstanceResponseSystemData,
      ),
    }),
  ).annotate({
    identifier: "CreateAzureBareMetalStorageInstanceResponse",
  }) as any as S.Schema<CreateAzureBareMetalStorageInstanceResponse>;

export interface DeleteAzureBareMetalStorageInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the AzureBareMetalStorage on Azure instance. */
  azureBareMetalStorageInstanceName: string;
}
export const DeleteAzureBareMetalStorageInstanceRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureBareMetalStorageInstanceName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances/{azureBareMetalStorageInstanceName}",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "DeleteAzureBareMetalStorageInstanceRequest",
  }) as any as S.Schema<DeleteAzureBareMetalStorageInstanceRequest>;

export interface DeleteAzureBareMetalStorageInstanceResponse {}
export const DeleteAzureBareMetalStorageInstanceResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "DeleteAzureBareMetalStorageInstanceResponse",
  }) as any as S.Schema<DeleteAzureBareMetalStorageInstanceResponse>;

export interface GetAzureBareMetalInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the Azure BareMetal on Azure instance. */
  azureBareMetalInstanceName: string;
}
export const GetAzureBareMetalInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureBareMetalInstanceName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalInstances/{azureBareMetalInstanceName}",
      code: 200,
      apiVersion: "2023-04-06",
    }),
  ),
).annotate({
  identifier: "GetAzureBareMetalInstanceRequest",
}) as any as S.Schema<GetAzureBareMetalInstanceRequest>;

/** Resource tags. */
export type GetAzureBareMetalInstanceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const GetAzureBareMetalInstanceResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<GetAzureBareMetalInstanceResponseTagsMap>;

/** Name of the hardware type (vendor and/or their product name) */
export type HardwareProfileHardwareType = "Cisco_UCS" | "HPE";
export const HardwareProfileHardwareType = S.String;

/** Specifies the AzureBareMetal instance SKU. */
export type HardwareProfileAzureBareMetalInstanceSize =
  | "S72m"
  | "S144m"
  | "S72"
  | "S144"
  | "S192"
  | "S192m"
  | "S192xm"
  | "S96"
  | "S112"
  | "S224"
  | "S224m"
  | "S224om"
  | "S224oo"
  | "S224oom"
  | "S224ooo"
  | "S384"
  | "S384m"
  | "S384xm"
  | "S384xxm"
  | "S448"
  | "S448m"
  | "S448om"
  | "S448oo"
  | "S448oom"
  | "S448ooo"
  | "S576m"
  | "S576xm"
  | "S672"
  | "S672m"
  | "S672om"
  | "S672oo"
  | "S672oom"
  | "S672ooo"
  | "S768"
  | "S768m"
  | "S768xm"
  | "S896"
  | "S896m"
  | "S896om"
  | "S896oo"
  | "S896oom"
  | "S896ooo"
  | "S960m";
export const HardwareProfileAzureBareMetalInstanceSize = S.String;

/** Specifies the hardware settings for the AzureBareMetal instance. */
export interface HardwareProfile {
  /** Name of the hardware type (vendor and/or their product name) */
  hardwareType?: HardwareProfileHardwareType;
  /** Specifies the AzureBareMetal instance SKU. */
  azureBareMetalInstanceSize?: HardwareProfileAzureBareMetalInstanceSize;
}
export const HardwareProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    hardwareType: S.optional(HardwareProfileHardwareType),
    azureBareMetalInstanceSize: S.optional(
      HardwareProfileAzureBareMetalInstanceSize,
    ),
  }),
).annotate({
  identifier: "HardwareProfile",
}) as any as S.Schema<HardwareProfile>;

/** Specifies the disk information fo the AzureBareMetal instance */
export interface Disk {
  /** The disk name. */
  name?: string;
  /** Specifies the size of an empty data disk in gigabytes. */
  diskSizeGB?: number;
  /** Specifies the logical unit number of the data disk. This value is used to identify data disks within the VM and therefore must be unique for each data disk attached to a VM. */
  lun?: number;
}
export const Disk = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    diskSizeGB: S.optional(S.Number),
    lun: S.optional(S.Number),
  }),
).annotate({ identifier: "Disk" }) as any as S.Schema<Disk>;

/** Specifies information about the operating system disk used by baremetal instance. */
export type StorageProfileOsDisksList = Array<Disk>;
export const StorageProfileOsDisksList = /*@__PURE__*/ S.Array(
  Disk,
) as any as S.Schema<StorageProfileOsDisksList>;

/** Specifies the storage settings for the AzureBareMetal instance disks. */
export interface StorageProfile {
  /** IP Address to connect to storage. */
  nfsIpAddress?: string;
  /** Specifies information about the operating system disk used by baremetal instance. */
  osDisks?: StorageProfileOsDisksList;
}
export const StorageProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    nfsIpAddress: S.optional(S.String),
    osDisks: S.optional(StorageProfileOsDisksList),
  }),
).annotate({ identifier: "StorageProfile" }) as any as S.Schema<StorageProfile>;

/** Specifies the operating system settings for the AzureBareMetal instance. */
export interface OSProfile {
  /** Specifies the host OS name of the AzureBareMetal instance. */
  computerName?: string;
  /** This property allows you to specify the type of the OS. */
  osType?: string;
  /** Specifies version of operating system. */
  version?: string;
  /** Specifies the SSH public key used to access the operating system. */
  sshPublicKey?: string;
}
export const OSProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    computerName: S.optional(S.String),
    osType: S.optional(S.String),
    version: S.optional(S.String),
    sshPublicKey: S.optional(S.String),
  }),
).annotate({ identifier: "OSProfile" }) as any as S.Schema<OSProfile>;

/** Specifies the IP address of the network interface. */
export interface IpAddress {
  /** Specifies the IP address of the network interface. */
  ipAddress?: string;
}
export const IpAddress = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ipAddress: S.optional(S.String),
  }),
).annotate({ identifier: "IpAddress" }) as any as S.Schema<IpAddress>;

/** Specifies the network interfaces for the AzureBareMetal instance. */
export type NetworkProfileNetworkInterfacesList = Array<IpAddress>;
export const NetworkProfileNetworkInterfacesList = /*@__PURE__*/ S.Array(
  IpAddress,
) as any as S.Schema<NetworkProfileNetworkInterfacesList>;

/** Specifies the network settings for the AzureBareMetal instance disks. */
export interface NetworkProfile {
  /** Specifies the network interfaces for the AzureBareMetal instance. */
  networkInterfaces?: NetworkProfileNetworkInterfacesList;
  /** Specifies the circuit id for connecting to express route. */
  circuitId?: string;
}
export const NetworkProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    networkInterfaces: S.optional(NetworkProfileNetworkInterfacesList),
    circuitId: S.optional(S.String),
  }),
).annotate({ identifier: "NetworkProfile" }) as any as S.Schema<NetworkProfile>;

/** Resource power state */
export type AzureBareMetalInstancePropertiesPowerState =
  | "starting"
  | "started"
  | "stopping"
  | "stopped"
  | "restarting"
  | "unknown";
export const AzureBareMetalInstancePropertiesPowerState = S.String;

/** State of provisioning of the AzureBareMetalInstance */
export type AzureBareMetalInstancePropertiesProvisioningState =
  | "Accepted"
  | "Creating"
  | "Updating"
  | "Failed"
  | "Succeeded"
  | "Deleting"
  | "Migrating";
export const AzureBareMetalInstancePropertiesProvisioningState = S.String;

/** Describes the properties of an AzureBareMetal instance. */
export interface AzureBareMetalInstanceProperties {
  /** Specifies the hardware settings for the AzureBareMetal instance. */
  hardwareProfile?: HardwareProfile;
  /** Specifies the storage settings for the AzureBareMetal instance disks. */
  storageProfile?: StorageProfile;
  /** Specifies the operating system settings for the AzureBareMetal instance. */
  osProfile?: OSProfile;
  /** Specifies the network settings for the AzureBareMetal instance. */
  networkProfile?: NetworkProfile;
  /** Specifies the AzureBareMetal instance unique ID. */
  azureBareMetalInstanceId?: string;
  /** Resource power state */
  powerState?: AzureBareMetalInstancePropertiesPowerState;
  /** Resource proximity placement group */
  proximityPlacementGroup?: string;
  /** Hardware revision of an AzureBareMetal instance */
  hwRevision?: string;
  /** ARM ID of another AzureBareMetalInstance that will share a network with this AzureBareMetalInstance */
  partnerNodeId?: string;
  /** State of provisioning of the AzureBareMetalInstance */
  provisioningState?: AzureBareMetalInstancePropertiesProvisioningState;
}
export const AzureBareMetalInstanceProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    hardwareProfile: S.optional(HardwareProfile),
    storageProfile: S.optional(StorageProfile),
    osProfile: S.optional(OSProfile),
    networkProfile: S.optional(NetworkProfile),
    azureBareMetalInstanceId: S.optional(S.String),
    powerState: S.optional(AzureBareMetalInstancePropertiesPowerState),
    proximityPlacementGroup: S.optional(S.String),
    hwRevision: S.optional(S.String),
    partnerNodeId: S.optional(S.String),
    provisioningState: S.optional(
      AzureBareMetalInstancePropertiesProvisioningState,
    ),
  }),
).annotate({
  identifier: "AzureBareMetalInstanceProperties",
}) as any as S.Schema<AzureBareMetalInstanceProperties>;

/** The type of identity that created the resource. */
export type GetAzureBareMetalInstanceResponseSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const GetAzureBareMetalInstanceResponseSystemDataCreatedByType =
  S.String;

/** The type of identity that last modified the resource. */
export type GetAzureBareMetalInstanceResponseSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const GetAzureBareMetalInstanceResponseSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface GetAzureBareMetalInstanceResponseSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: GetAzureBareMetalInstanceResponseSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: GetAzureBareMetalInstanceResponseSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const GetAzureBareMetalInstanceResponseSystemData =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        GetAzureBareMetalInstanceResponseSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        GetAzureBareMetalInstanceResponseSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
  ).annotate({
    identifier: "GetAzureBareMetalInstanceResponseSystemData",
  }) as any as S.Schema<GetAzureBareMetalInstanceResponseSystemData>;

export interface GetAzureBareMetalInstanceResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: GetAzureBareMetalInstanceResponseTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetal instance properties */
  properties?: AzureBareMetalInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: GetAzureBareMetalInstanceResponseSystemData;
}
export const GetAzureBareMetalInstanceResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    tags: S.optional(GetAzureBareMetalInstanceResponseTagsMap),
    location: S.String,
    properties: S.optional(AzureBareMetalInstanceProperties),
    systemData: S.optional(GetAzureBareMetalInstanceResponseSystemData),
  }),
).annotate({
  identifier: "GetAzureBareMetalInstanceResponse",
}) as any as S.Schema<GetAzureBareMetalInstanceResponse>;

export interface GetAzureBareMetalStorageInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the AzureBareMetalStorage on Azure instance. */
  azureBareMetalStorageInstanceName: string;
}
export const GetAzureBareMetalStorageInstanceRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureBareMetalStorageInstanceName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances/{azureBareMetalStorageInstanceName}",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
).annotate({
  identifier: "GetAzureBareMetalStorageInstanceRequest",
}) as any as S.Schema<GetAzureBareMetalStorageInstanceRequest>;

/** Resource tags. */
export type GetAzureBareMetalStorageInstanceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const GetAzureBareMetalStorageInstanceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<GetAzureBareMetalStorageInstanceResponseTagsMap>;

/** The type of identity that created the resource. */
export type GetAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const GetAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  S.String;

/** The type of identity that last modified the resource. */
export type GetAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const GetAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface GetAzureBareMetalStorageInstanceResponseSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: GetAzureBareMetalStorageInstanceResponseSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: GetAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const GetAzureBareMetalStorageInstanceResponseSystemData =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        GetAzureBareMetalStorageInstanceResponseSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        GetAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
  ).annotate({
    identifier: "GetAzureBareMetalStorageInstanceResponseSystemData",
  }) as any as S.Schema<GetAzureBareMetalStorageInstanceResponseSystemData>;

export interface GetAzureBareMetalStorageInstanceResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: GetAzureBareMetalStorageInstanceResponseTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetalStorageInstance properties */
  properties?: AzureBareMetalStorageInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: GetAzureBareMetalStorageInstanceResponseSystemData;
}
export const GetAzureBareMetalStorageInstanceResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      tags: S.optional(GetAzureBareMetalStorageInstanceResponseTagsMap),
      location: S.String,
      properties: S.optional(AzureBareMetalStorageInstanceProperties),
      systemData: S.optional(
        GetAzureBareMetalStorageInstanceResponseSystemData,
      ),
    }),
).annotate({
  identifier: "GetAzureBareMetalStorageInstanceResponse",
}) as any as S.Schema<GetAzureBareMetalStorageInstanceResponse>;

export interface ListAzureBareMetalInstanceByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListAzureBareMetalInstanceByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalInstances",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "ListAzureBareMetalInstanceByResourceGroupRequest",
  }) as any as S.Schema<ListAzureBareMetalInstanceByResourceGroupRequest>;

/** Resource tags. */
export type AzureBareMetalInstanceTagsMap = {
  [key: string]: string | undefined;
};
export const AzureBareMetalInstanceTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<AzureBareMetalInstanceTagsMap>;

/** The type of identity that created the resource. */
export type AzureBareMetalInstanceSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const AzureBareMetalInstanceSystemDataCreatedByType = S.String;

/** The type of identity that last modified the resource. */
export type AzureBareMetalInstanceSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const AzureBareMetalInstanceSystemDataLastModifiedByType = S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface AzureBareMetalInstanceSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: AzureBareMetalInstanceSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: AzureBareMetalInstanceSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const AzureBareMetalInstanceSystemData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdBy: S.optional(S.String),
    createdByType: S.optional(AzureBareMetalInstanceSystemDataCreatedByType),
    createdAt: S.optional(S.String),
    lastModifiedBy: S.optional(S.String),
    lastModifiedByType: S.optional(
      AzureBareMetalInstanceSystemDataLastModifiedByType,
    ),
    lastModifiedAt: S.optional(S.String),
  }),
).annotate({
  identifier: "AzureBareMetalInstanceSystemData",
}) as any as S.Schema<AzureBareMetalInstanceSystemData>;

/** AzureBareMetal instance info on Azure (ARM properties and AzureBareMetal properties) */
export interface AzureBareMetalInstance {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: AzureBareMetalInstanceTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetal instance properties */
  properties?: AzureBareMetalInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: AzureBareMetalInstanceSystemData;
}
export const AzureBareMetalInstance = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    tags: S.optional(AzureBareMetalInstanceTagsMap),
    location: S.String,
    properties: S.optional(AzureBareMetalInstanceProperties),
    systemData: S.optional(AzureBareMetalInstanceSystemData),
  }),
).annotate({
  identifier: "AzureBareMetalInstance",
}) as any as S.Schema<AzureBareMetalInstance>;

/** The list of Azure BareMetal instances. */
export type AzureBareMetalInstancesListResultValueList =
  Array<AzureBareMetalInstance>;
export const AzureBareMetalInstancesListResultValueList = /*@__PURE__*/ S.Array(
  AzureBareMetalInstance,
) as any as S.Schema<AzureBareMetalInstancesListResultValueList>;

/** The response from the List AzureBareMetal Instances operation. */
export interface AzureBareMetalInstancesListResult {
  /** The list of Azure BareMetal instances. */
  value?: AzureBareMetalInstancesListResultValueList;
  /** The URL to get the next set of AzureBareMetal instances. */
  nextLink?: string;
}
export const AzureBareMetalInstancesListResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: S.optional(AzureBareMetalInstancesListResultValueList),
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "AzureBareMetalInstancesListResult",
}) as any as S.Schema<AzureBareMetalInstancesListResult>;

export interface ListAzureBareMetalInstanceBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListAzureBareMetalInstanceBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.BareMetalInfrastructure/bareMetalInstances",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "ListAzureBareMetalInstanceBySubscriptionRequest",
  }) as any as S.Schema<ListAzureBareMetalInstanceBySubscriptionRequest>;

export interface ListAzureBareMetalStorageInstanceByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListAzureBareMetalStorageInstanceByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "ListAzureBareMetalStorageInstanceByResourceGroupRequest",
  }) as any as S.Schema<ListAzureBareMetalStorageInstanceByResourceGroupRequest>;

/** Resource tags. */
export type AzureBareMetalStorageInstanceTagsMap = {
  [key: string]: string | undefined;
};
export const AzureBareMetalStorageInstanceTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<AzureBareMetalStorageInstanceTagsMap>;

/** The type of identity that created the resource. */
export type AzureBareMetalStorageInstanceSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const AzureBareMetalStorageInstanceSystemDataCreatedByType = S.String;

/** The type of identity that last modified the resource. */
export type AzureBareMetalStorageInstanceSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const AzureBareMetalStorageInstanceSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface AzureBareMetalStorageInstanceSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: AzureBareMetalStorageInstanceSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: AzureBareMetalStorageInstanceSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const AzureBareMetalStorageInstanceSystemData = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        AzureBareMetalStorageInstanceSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        AzureBareMetalStorageInstanceSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
).annotate({
  identifier: "AzureBareMetalStorageInstanceSystemData",
}) as any as S.Schema<AzureBareMetalStorageInstanceSystemData>;

/** AzureBareMetalStorageInstance info on Azure (ARM properties and AzureBareMetalStorage properties) */
export interface AzureBareMetalStorageInstance {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: AzureBareMetalStorageInstanceTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetalStorageInstance properties */
  properties?: AzureBareMetalStorageInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: AzureBareMetalStorageInstanceSystemData;
}
export const AzureBareMetalStorageInstance = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    tags: S.optional(AzureBareMetalStorageInstanceTagsMap),
    location: S.String,
    properties: S.optional(AzureBareMetalStorageInstanceProperties),
    systemData: S.optional(AzureBareMetalStorageInstanceSystemData),
  }),
).annotate({
  identifier: "AzureBareMetalStorageInstance",
}) as any as S.Schema<AzureBareMetalStorageInstance>;

/** The list of AzureBareMetalStorage instances. */
export type AzureBareMetalStorageInstancesListResultValueList =
  Array<AzureBareMetalStorageInstance>;
export const AzureBareMetalStorageInstancesListResultValueList =
  /*@__PURE__*/ S.Array(
    AzureBareMetalStorageInstance,
  ) as any as S.Schema<AzureBareMetalStorageInstancesListResultValueList>;

/** The response from the Get AzureBareMetalStorageInstances operation. */
export interface AzureBareMetalStorageInstancesListResult {
  /** The list of AzureBareMetalStorage instances. */
  value?: AzureBareMetalStorageInstancesListResultValueList;
  /** The URL to get the next set of AzureBareMetalStorage instances. */
  nextLink?: string;
}
export const AzureBareMetalStorageInstancesListResult = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      value: S.optional(AzureBareMetalStorageInstancesListResultValueList),
      nextLink: S.optional(S.String),
    }),
).annotate({
  identifier: "AzureBareMetalStorageInstancesListResult",
}) as any as S.Schema<AzureBareMetalStorageInstancesListResult>;

export interface ListAzureBareMetalStorageInstanceBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListAzureBareMetalStorageInstanceBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "ListAzureBareMetalStorageInstanceBySubscriptionRequest",
  }) as any as S.Schema<ListAzureBareMetalStorageInstanceBySubscriptionRequest>;

export interface ListOperationsRequest {}
export const ListOperationsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "GET",
      uri: "/providers/Microsoft.BareMetalInfrastructure/operations",
      code: 200,
      apiVersion: "2023-04-06",
    }),
  ),
).annotate({
  identifier: "ListOperationsRequest",
}) as any as S.Schema<ListOperationsRequest>;

/** Detailed BareMetal operation information */
export interface Display {
  /** The localized friendly form of the resource provider name. */
  provider?: string;
  /** The localized friendly form of the resource type related to this action/operation. */
  resource?: string;
  /** The localized friendly name for the operation as shown to the user. */
  operation?: string;
  /** The localized friendly description for the operation as shown to the user. */
  description?: string;
}
export const Display = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    provider: S.optional(S.String),
    resource: S.optional(S.String),
    operation: S.optional(S.String),
    description: S.optional(S.String),
  }),
).annotate({ identifier: "Display" }) as any as S.Schema<Display>;

/** AzureBareMetal operation information */
export interface Operation {
  /** The name of the operation being performed on this particular object. This name should match the action name that appears in RBAC / the event service. */
  name?: string;
  /** Displayed AzureBareMetal operation information */
  display?: Display;
  /** indicates whether an operation is a data action or not. */
  isDataAction?: boolean;
}
export const Operation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    display: S.optional(Display),
    isDataAction: S.optional(S.Boolean),
  }),
).annotate({ identifier: "Operation" }) as any as S.Schema<Operation>;

/** List of AzureBareMetal operations */
export type OperationListValueList = Array<Operation>;
export const OperationListValueList = /*@__PURE__*/ S.Array(
  Operation,
) as any as S.Schema<OperationListValueList>;

/** List of AzureBareMetal operations */
export interface OperationList {
  /** List of AzureBareMetal operations */
  value?: OperationListValueList;
}
export const OperationList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: S.optional(OperationListValueList),
  }),
).annotate({ identifier: "OperationList" }) as any as S.Schema<OperationList>;

/** Tags field of the AzureBareMetal/AzureBareMetaStorage instance. */
export type UpdateAzureBareMetalInstanceRequestTagsMap = {
  [key: string]: string | undefined;
};
export const UpdateAzureBareMetalInstanceRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<UpdateAzureBareMetalInstanceRequestTagsMap>;

export interface UpdateAzureBareMetalInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the Azure BareMetal on Azure instance. */
  azureBareMetalInstanceName: string;
  /** Tags field of the AzureBareMetal/AzureBareMetaStorage instance. */
  tags?: UpdateAzureBareMetalInstanceRequestTagsMap;
}
export const UpdateAzureBareMetalInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    azureBareMetalInstanceName: S.String.pipe(T.Label()),
    tags: S.optional(UpdateAzureBareMetalInstanceRequestTagsMap),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalInstances/{azureBareMetalInstanceName}",
      code: 200,
      apiVersion: "2023-04-06",
    }),
  ),
).annotate({
  identifier: "UpdateAzureBareMetalInstanceRequest",
}) as any as S.Schema<UpdateAzureBareMetalInstanceRequest>;

/** Resource tags. */
export type UpdateAzureBareMetalInstanceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const UpdateAzureBareMetalInstanceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<UpdateAzureBareMetalInstanceResponseTagsMap>;

/** The type of identity that created the resource. */
export type UpdateAzureBareMetalInstanceResponseSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const UpdateAzureBareMetalInstanceResponseSystemDataCreatedByType =
  S.String;

/** The type of identity that last modified the resource. */
export type UpdateAzureBareMetalInstanceResponseSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const UpdateAzureBareMetalInstanceResponseSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface UpdateAzureBareMetalInstanceResponseSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: UpdateAzureBareMetalInstanceResponseSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: UpdateAzureBareMetalInstanceResponseSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const UpdateAzureBareMetalInstanceResponseSystemData =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        UpdateAzureBareMetalInstanceResponseSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        UpdateAzureBareMetalInstanceResponseSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
  ).annotate({
    identifier: "UpdateAzureBareMetalInstanceResponseSystemData",
  }) as any as S.Schema<UpdateAzureBareMetalInstanceResponseSystemData>;

export interface UpdateAzureBareMetalInstanceResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: UpdateAzureBareMetalInstanceResponseTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetal instance properties */
  properties?: AzureBareMetalInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: UpdateAzureBareMetalInstanceResponseSystemData;
}
export const UpdateAzureBareMetalInstanceResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      tags: S.optional(UpdateAzureBareMetalInstanceResponseTagsMap),
      location: S.String,
      properties: S.optional(AzureBareMetalInstanceProperties),
      systemData: S.optional(UpdateAzureBareMetalInstanceResponseSystemData),
    }),
).annotate({
  identifier: "UpdateAzureBareMetalInstanceResponse",
}) as any as S.Schema<UpdateAzureBareMetalInstanceResponse>;

/** Tags field of the AzureBareMetal/AzureBareMetaStorage instance. */
export type UpdateAzureBareMetalStorageInstanceRequestTagsMap = {
  [key: string]: string | undefined;
};
export const UpdateAzureBareMetalStorageInstanceRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<UpdateAzureBareMetalStorageInstanceRequestTagsMap>;

export interface UpdateAzureBareMetalStorageInstanceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** Name of the AzureBareMetalStorage on Azure instance. */
  azureBareMetalStorageInstanceName: string;
  /** Tags field of the AzureBareMetal/AzureBareMetaStorage instance. */
  tags?: UpdateAzureBareMetalStorageInstanceRequestTagsMap;
}
export const UpdateAzureBareMetalStorageInstanceRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      azureBareMetalStorageInstanceName: S.String.pipe(T.Label()),
      tags: S.optional(UpdateAzureBareMetalStorageInstanceRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.BareMetalInfrastructure/bareMetalStorageInstances/{azureBareMetalStorageInstanceName}",
        code: 200,
        apiVersion: "2023-04-06",
      }),
    ),
  ).annotate({
    identifier: "UpdateAzureBareMetalStorageInstanceRequest",
  }) as any as S.Schema<UpdateAzureBareMetalStorageInstanceRequest>;

/** Resource tags. */
export type UpdateAzureBareMetalStorageInstanceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const UpdateAzureBareMetalStorageInstanceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<UpdateAzureBareMetalStorageInstanceResponseTagsMap>;

/** The type of identity that created the resource. */
export type UpdateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const UpdateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType =
  S.String;

/** The type of identity that last modified the resource. */
export type UpdateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  | "User"
  | "Application"
  | "ManagedIdentity"
  | "Key";
export const UpdateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType =
  S.String;

/** Metadata pertaining to creation and last modification of the resource. */
export interface UpdateAzureBareMetalStorageInstanceResponseSystemData {
  /** The identity that created the resource. */
  createdBy?: string;
  /** The type of identity that created the resource. */
  createdByType?: UpdateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType;
  /** The timestamp of resource creation (UTC). */
  createdAt?: string;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: UpdateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string;
}
export const UpdateAzureBareMetalStorageInstanceResponseSystemData =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      createdBy: S.optional(S.String),
      createdByType: S.optional(
        UpdateAzureBareMetalStorageInstanceResponseSystemDataCreatedByType,
      ),
      createdAt: S.optional(S.String),
      lastModifiedBy: S.optional(S.String),
      lastModifiedByType: S.optional(
        UpdateAzureBareMetalStorageInstanceResponseSystemDataLastModifiedByType,
      ),
      lastModifiedAt: S.optional(S.String),
    }),
  ).annotate({
    identifier: "UpdateAzureBareMetalStorageInstanceResponseSystemData",
  }) as any as S.Schema<UpdateAzureBareMetalStorageInstanceResponseSystemData>;

export interface UpdateAzureBareMetalStorageInstanceResponse {
  /** Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} */
  id?: string;
  /** The name of the resource */
  name?: string;
  /** The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts" */
  type?: string;
  /** Resource tags. */
  tags?: UpdateAzureBareMetalStorageInstanceResponseTagsMap;
  /** The geo-location where the resource lives */
  location: string;
  /** AzureBareMetalStorageInstance properties */
  properties?: AzureBareMetalStorageInstanceProperties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: UpdateAzureBareMetalStorageInstanceResponseSystemData;
}
export const UpdateAzureBareMetalStorageInstanceResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      tags: S.optional(UpdateAzureBareMetalStorageInstanceResponseTagsMap),
      location: S.String,
      properties: S.optional(AzureBareMetalStorageInstanceProperties),
      systemData: S.optional(
        UpdateAzureBareMetalStorageInstanceResponseSystemData,
      ),
    }),
  ).annotate({
    identifier: "UpdateAzureBareMetalStorageInstanceResponse",
  }) as any as S.Schema<UpdateAzureBareMetalStorageInstanceResponse>;

export type CreateAzureBareMetalStorageInstanceError = AzureOpError;
/** Create an azure baremetal storage resource. */
export const CreateAzureBareMetalStorageInstance: API.OperationMethod<
  CreateAzureBareMetalStorageInstanceRequest,
  CreateAzureBareMetalStorageInstanceResponse,
  CreateAzureBareMetalStorageInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAzureBareMetalStorageInstanceRequest,
  output: CreateAzureBareMetalStorageInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteAzureBareMetalStorageInstanceError = AzureOpError;
/** Delete an AzureBareMetalStorageInstance. */
export const DeleteAzureBareMetalStorageInstance: API.OperationMethod<
  DeleteAzureBareMetalStorageInstanceRequest,
  DeleteAzureBareMetalStorageInstanceResponse,
  DeleteAzureBareMetalStorageInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAzureBareMetalStorageInstanceRequest,
  output: DeleteAzureBareMetalStorageInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetAzureBareMetalInstanceError = AzureOpError;
/** Gets an Azure BareMetal instance. Gets an Azure BareMetal instance for the specified subscription, resource group, and instance name. */
export const GetAzureBareMetalInstance: API.OperationMethod<
  GetAzureBareMetalInstanceRequest,
  GetAzureBareMetalInstanceResponse,
  GetAzureBareMetalInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAzureBareMetalInstanceRequest,
  output: GetAzureBareMetalInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetAzureBareMetalStorageInstanceError = AzureOpError;
/** Gets an Azure BareMetal Storage instance. Gets an Azure BareMetal Storage instance for the specified subscription, resource group, and instance name. */
export const GetAzureBareMetalStorageInstance: API.OperationMethod<
  GetAzureBareMetalStorageInstanceRequest,
  GetAzureBareMetalStorageInstanceResponse,
  GetAzureBareMetalStorageInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAzureBareMetalStorageInstanceRequest,
  output: GetAzureBareMetalStorageInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureBareMetalInstanceByResourceGroupError = AzureOpError;
/** Gets a list of Azure BareMetal instances in the specified subscription and resource group. Gets a list of AzureBareMetal instances in the specified subscription and resource group. The operations returns various properties of each Azure BareMetal instance. */
export const ListAzureBareMetalInstanceByResourceGroup: API.OperationMethod<
  ListAzureBareMetalInstanceByResourceGroupRequest,
  AzureBareMetalInstancesListResult,
  ListAzureBareMetalInstanceByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureBareMetalInstanceByResourceGroupRequest,
  output: AzureBareMetalInstancesListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureBareMetalInstanceBySubscriptionError = AzureOpError;
/** Gets a list of Azure BareMetal instances in the specified subscription. Gets a list of AzureBareMetal instances in the specified subscription. The operations returns various properties of each Azure BareMetal instance. */
export const ListAzureBareMetalInstanceBySubscription: API.OperationMethod<
  ListAzureBareMetalInstanceBySubscriptionRequest,
  AzureBareMetalInstancesListResult,
  ListAzureBareMetalInstanceBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureBareMetalInstanceBySubscriptionRequest,
  output: AzureBareMetalInstancesListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureBareMetalStorageInstanceByResourceGroupError =
  AzureOpError;
/** Gets a list of Azure BareMetalStorage instances in the specified subscription and resource group. Gets a list of AzureBareMetalStorage instances in the specified subscription and resource group. The operations returns various properties of each Azure BareMetal instance. */
export const ListAzureBareMetalStorageInstanceByResourceGroup: API.OperationMethod<
  ListAzureBareMetalStorageInstanceByResourceGroupRequest,
  AzureBareMetalStorageInstancesListResult,
  ListAzureBareMetalStorageInstanceByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureBareMetalStorageInstanceByResourceGroupRequest,
  output: AzureBareMetalStorageInstancesListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListAzureBareMetalStorageInstanceBySubscriptionError = AzureOpError;
/** Gets a list of Azure BareMetalStorage instances in the specified subscription. Gets a list of AzureBareMetalStorage instances in the specified subscription. The operations returns various properties of each Azure BareMetal instance. */
export const ListAzureBareMetalStorageInstanceBySubscription: API.OperationMethod<
  ListAzureBareMetalStorageInstanceBySubscriptionRequest,
  AzureBareMetalStorageInstancesListResult,
  ListAzureBareMetalStorageInstanceBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAzureBareMetalStorageInstanceBySubscriptionRequest,
  output: AzureBareMetalStorageInstancesListResult,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListOperationsError = AzureOpError;
/** Gets a list of AzureBareMetal management operations. */
export const ListOperations: API.OperationMethod<
  ListOperationsRequest,
  OperationList,
  ListOperationsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListOperationsRequest,
  output: OperationList,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type UpdateAzureBareMetalInstanceError = AzureOpError;
/** Patches the Tags field of a Azure BareMetal instance. Patches the Tags field of a Azure BareMetal instance for the specified subscription, resource group, and instance name. */
export const UpdateAzureBareMetalInstance: API.OperationMethod<
  UpdateAzureBareMetalInstanceRequest,
  UpdateAzureBareMetalInstanceResponse,
  UpdateAzureBareMetalInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAzureBareMetalInstanceRequest,
  output: UpdateAzureBareMetalInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type UpdateAzureBareMetalStorageInstanceError = AzureOpError;
/** Patches the Tags field of a Azure BareMetalStorage instance. Patches the Tags field of a Azure BareMetalStorage instance for the specified subscription, resource group, and instance name. */
export const UpdateAzureBareMetalStorageInstance: API.OperationMethod<
  UpdateAzureBareMetalStorageInstanceRequest,
  UpdateAzureBareMetalStorageInstanceResponse,
  UpdateAzureBareMetalStorageInstanceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAzureBareMetalStorageInstanceRequest,
  output: UpdateAzureBareMetalStorageInstanceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));
