// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/azure-rest-api-specs). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  AzureProtocol,
  type AzureOpError,
  type AzureOpContext,
} from "../protocol.ts";
import { UnknownAzureError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { AzureOpError, AzureOpContext };

/** The resource tags. */
export type CreateControllerRequestTagsMap = {
  [key: string]: string | undefined;
};
export const CreateControllerRequestTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateControllerRequestTagsMap>;

export interface CreateControllerRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: CreateControllerRequestTagsMap;
}
export const CreateControllerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    resourceName: S.String.pipe(T.Label()),
    location: S.optional(S.String),
    tags: S.optional(CreateControllerRequestTagsMap),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/controller/{resourceName}",
      code: 200,
      apiVersion: "2021-03-15",
    }),
  ),
).annotate({
  identifier: "CreateControllerRequest",
}) as any as S.Schema<CreateControllerRequest>;

/** The resource tags. */
export type CreateControllerResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CreateControllerResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateControllerResponseTagsMap>;

/** The current state of dnc controller resource. */
export type DelegatedControllerPropertiesProvisioningState =
  | "Deleting"
  | "Succeeded"
  | "Failed"
  | "Provisioning";
export const DelegatedControllerPropertiesProvisioningState =
  /*@__PURE__*/ S.String;

/** Properties of Delegated controller resource. */
export interface DelegatedControllerProperties {
  /** Resource guid. */
  resourceGuid?: string;
  /** The current state of dnc controller resource. */
  provisioningState?: DelegatedControllerPropertiesProvisioningState;
  /** dnc application id should be used by customer to authenticate with dnc gateway. */
  dncAppId?: string;
  /** tenant id of dnc application id */
  dncTenantId?: string;
  /** dnc endpoint url that customers can use to connect to */
  dncEndpoint?: string;
}
export const DelegatedControllerProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    resourceGuid: S.optional(S.String),
    provisioningState: S.optional(
      DelegatedControllerPropertiesProvisioningState,
    ),
    dncAppId: S.optional(S.String),
    dncTenantId: S.optional(S.String),
    dncEndpoint: S.optional(S.String),
  }),
).annotate({
  identifier: "DelegatedControllerProperties",
}) as any as S.Schema<DelegatedControllerProperties>;

export interface CreateControllerResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: CreateControllerResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedControllerProperties;
}
export const CreateControllerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    tags: S.optional(CreateControllerResponseTagsMap),
    properties: S.optional(DelegatedControllerProperties),
  }),
).annotate({
  identifier: "CreateControllerResponse",
}) as any as S.Schema<CreateControllerResponse>;

/** The kind of workbook. Choices are user and shared. */
export type CreateOrchestratorInstanceServiceRequestKind = "Kubernetes";
export const CreateOrchestratorInstanceServiceRequestKind =
  /*@__PURE__*/ S.String;

/** The type of identity used for orchestrator cluster. Type 'SystemAssigned' will use an implicitly created identity orchestrator clusters */
export type OrchestratorIdentityInputType = "SystemAssigned" | "None";
export const OrchestratorIdentityInputType = /*@__PURE__*/ S.String;

export interface OrchestratorIdentityInput {
  /** The type of identity used for orchestrator cluster. Type 'SystemAssigned' will use an implicitly created identity orchestrator clusters */
  type?: OrchestratorIdentityInputType | (string & {});
}
export const OrchestratorIdentityInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(OrchestratorIdentityInputType),
  }),
).annotate({
  identifier: "OrchestratorIdentityInput",
}) as any as S.Schema<OrchestratorIdentityInput>;

/** The resource tags. */
export type CreateOrchestratorInstanceServiceRequestTagsMap = {
  [key: string]: string | undefined;
};
export const CreateOrchestratorInstanceServiceRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CreateOrchestratorInstanceServiceRequestTagsMap>;

/** controller details */
export interface OrchestratorResourcePropertiesInputControllerDetails {
  /** controller arm resource id */
  id?: string;
}
export const OrchestratorResourcePropertiesInputControllerDetails =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
    }),
  ).annotate({
    identifier: "OrchestratorResourcePropertiesInputControllerDetails",
  }) as any as S.Schema<OrchestratorResourcePropertiesInputControllerDetails>;

/** Properties of orchestrator */
export interface OrchestratorResourcePropertiesInput {
  /** AAD ID used with apiserver */
  orchestratorAppId?: string;
  /** TenantID of server App ID */
  orchestratorTenantId?: string;
  /** RootCA certificate of kubernetes cluster base64 encoded */
  clusterRootCA?: string;
  /** K8s APIServer url. Either one of apiServerEndpoint or privateLinkResourceId can be specified */
  apiServerEndpoint?: string;
  /** private link arm resource id. Either one of apiServerEndpoint or privateLinkResourceId can be specified */
  privateLinkResourceId?: string;
  /** controller details */
  controllerDetails: OrchestratorResourcePropertiesInputControllerDetails;
}
export const OrchestratorResourcePropertiesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    orchestratorAppId: S.optional(S.String),
    orchestratorTenantId: S.optional(S.String),
    clusterRootCA: S.optional(S.String),
    apiServerEndpoint: S.optional(S.String),
    privateLinkResourceId: S.optional(S.String),
    controllerDetails: OrchestratorResourcePropertiesInputControllerDetails,
  }),
).annotate({
  identifier: "OrchestratorResourcePropertiesInput",
}) as any as S.Schema<OrchestratorResourcePropertiesInput>;

export interface CreateOrchestratorInstanceServiceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** Location of the resource. */
  location?: string;
  /** The kind of workbook. Choices are user and shared. */
  kind: CreateOrchestratorInstanceServiceRequestKind | (string & {});
  /** The identity of the orchestrator */
  identity?: OrchestratorIdentityInput;
  /** The resource tags. */
  tags?: CreateOrchestratorInstanceServiceRequestTagsMap;
  /** Properties of the provision operation request. */
  properties?: OrchestratorResourcePropertiesInput;
}
export const CreateOrchestratorInstanceServiceRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      location: S.optional(S.String),
      kind: CreateOrchestratorInstanceServiceRequestKind,
      identity: S.optional(OrchestratorIdentityInput),
      tags: S.optional(CreateOrchestratorInstanceServiceRequestTagsMap),
      properties: S.optional(OrchestratorResourcePropertiesInput),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/orchestrators/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
).annotate({
  identifier: "CreateOrchestratorInstanceServiceRequest",
}) as any as S.Schema<CreateOrchestratorInstanceServiceRequest>;

/** The kind of workbook. Choices are user and shared. */
export type CreateOrchestratorInstanceServiceResponseKind = "Kubernetes";
export const CreateOrchestratorInstanceServiceResponseKind =
  /*@__PURE__*/ S.String;

/** The type of identity used for orchestrator cluster. Type 'SystemAssigned' will use an implicitly created identity orchestrator clusters */
export type OrchestratorIdentityType = "SystemAssigned" | "None";
export const OrchestratorIdentityType = /*@__PURE__*/ S.String;

export interface OrchestratorIdentity {
  /** The principal id of the system assigned identity which is used by orchestrator. */
  principalId?: string;
  /** The tenant id of the system assigned identity which is used by orchestrator. */
  tenantId?: string;
  /** The type of identity used for orchestrator cluster. Type 'SystemAssigned' will use an implicitly created identity orchestrator clusters */
  type?: OrchestratorIdentityType;
}
export const OrchestratorIdentity = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    principalId: S.optional(S.String),
    tenantId: S.optional(S.String),
    type: S.optional(OrchestratorIdentityType),
  }),
).annotate({
  identifier: "OrchestratorIdentity",
}) as any as S.Schema<OrchestratorIdentity>;

/** The resource tags. */
export type CreateOrchestratorInstanceServiceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const CreateOrchestratorInstanceServiceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<CreateOrchestratorInstanceServiceResponseTagsMap>;

/** The current state of orchestratorInstance resource. */
export type OrchestratorResourcePropertiesProvisioningState =
  | "Deleting"
  | "Succeeded"
  | "Failed"
  | "Provisioning";
export const OrchestratorResourcePropertiesProvisioningState =
  /*@__PURE__*/ S.String;

/** controller details */
export type OrchestratorResourcePropertiesControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;
export const OrchestratorResourcePropertiesControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;

/** Properties of orchestrator */
export interface OrchestratorResourceProperties {
  /** Resource guid. */
  resourceGuid?: string;
  /** The current state of orchestratorInstance resource. */
  provisioningState?: OrchestratorResourcePropertiesProvisioningState;
  /** AAD ID used with apiserver */
  orchestratorAppId?: string;
  /** TenantID of server App ID */
  orchestratorTenantId?: string;
  /** RootCA certificate of kubernetes cluster base64 encoded */
  clusterRootCA?: string;
  /** K8s APIServer url. Either one of apiServerEndpoint or privateLinkResourceId can be specified */
  apiServerEndpoint?: string;
  /** private link arm resource id. Either one of apiServerEndpoint or privateLinkResourceId can be specified */
  privateLinkResourceId?: string;
  /** controller details */
  controllerDetails: OrchestratorResourcePropertiesInputControllerDetails;
}
export const OrchestratorResourceProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    resourceGuid: S.optional(S.String),
    provisioningState: S.optional(
      OrchestratorResourcePropertiesProvisioningState,
    ),
    orchestratorAppId: S.optional(S.String),
    orchestratorTenantId: S.optional(S.String),
    clusterRootCA: S.optional(S.String),
    apiServerEndpoint: S.optional(S.String),
    privateLinkResourceId: S.optional(S.String),
    controllerDetails: OrchestratorResourcePropertiesInputControllerDetails,
  }),
).annotate({
  identifier: "OrchestratorResourceProperties",
}) as any as S.Schema<OrchestratorResourceProperties>;

export interface CreateOrchestratorInstanceServiceResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The kind of workbook. Choices are user and shared. */
  kind: CreateOrchestratorInstanceServiceResponseKind;
  /** The identity of the orchestrator */
  identity?: OrchestratorIdentity;
  /** The resource tags. */
  tags?: CreateOrchestratorInstanceServiceResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: OrchestratorResourceProperties;
}
export const CreateOrchestratorInstanceServiceResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      kind: CreateOrchestratorInstanceServiceResponseKind,
      identity: S.optional(OrchestratorIdentity),
      tags: S.optional(CreateOrchestratorInstanceServiceResponseTagsMap),
      properties: S.optional(OrchestratorResourceProperties),
    }),
  ).annotate({
    identifier: "CreateOrchestratorInstanceServiceResponse",
  }) as any as S.Schema<CreateOrchestratorInstanceServiceResponse>;

export interface DeleteControllerRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
}
export const DeleteControllerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    resourceName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/controller/{resourceName}",
      code: 200,
      apiVersion: "2021-03-15",
    }),
  ),
).annotate({
  identifier: "DeleteControllerRequest",
}) as any as S.Schema<DeleteControllerRequest>;

export interface DeleteControllerResponse {}
export const DeleteControllerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteControllerResponse",
}) as any as S.Schema<DeleteControllerResponse>;

export interface DeleteDelegatedSubnetServiceDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** Force delete resource */
  forceDelete?: boolean;
}
export const DeleteDelegatedSubnetServiceDetailsRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      forceDelete: S.optional(S.Boolean.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/delegatedSubnets/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "DeleteDelegatedSubnetServiceDetailsRequest",
  }) as any as S.Schema<DeleteDelegatedSubnetServiceDetailsRequest>;

export interface DeleteDelegatedSubnetServiceDetailsResponse {}
export const DeleteDelegatedSubnetServiceDetailsResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "DeleteDelegatedSubnetServiceDetailsResponse",
  }) as any as S.Schema<DeleteDelegatedSubnetServiceDetailsResponse>;

export interface DeleteOrchestratorInstanceServiceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** Force delete resource */
  forceDelete?: boolean;
}
export const DeleteOrchestratorInstanceServiceRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      forceDelete: S.optional(S.Boolean.pipe(T.Query())),
    }).pipe(
      T.Http({
        method: "DELETE",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/orchestrators/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
).annotate({
  identifier: "DeleteOrchestratorInstanceServiceRequest",
}) as any as S.Schema<DeleteOrchestratorInstanceServiceRequest>;

export interface DeleteOrchestratorInstanceServiceResponse {}
export const DeleteOrchestratorInstanceServiceResponse =
  /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
    identifier: "DeleteOrchestratorInstanceServiceResponse",
  }) as any as S.Schema<DeleteOrchestratorInstanceServiceResponse>;

export interface GetControllerDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
}
export const GetControllerDetailsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    resourceName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/controller/{resourceName}",
      code: 200,
      apiVersion: "2021-03-15",
    }),
  ),
).annotate({
  identifier: "GetControllerDetailsRequest",
}) as any as S.Schema<GetControllerDetailsRequest>;

/** The resource tags. */
export type GetControllerDetailsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const GetControllerDetailsResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<GetControllerDetailsResponseTagsMap>;

export interface GetControllerDetailsResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: GetControllerDetailsResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedControllerProperties;
}
export const GetControllerDetailsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    tags: S.optional(GetControllerDetailsResponseTagsMap),
    properties: S.optional(DelegatedControllerProperties),
  }),
).annotate({
  identifier: "GetControllerDetailsResponse",
}) as any as S.Schema<GetControllerDetailsResponse>;

export interface GetDelegatedSubnetServiceDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
}
export const GetDelegatedSubnetServiceDetailsRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/delegatedSubnets/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
).annotate({
  identifier: "GetDelegatedSubnetServiceDetailsRequest",
}) as any as S.Schema<GetDelegatedSubnetServiceDetailsRequest>;

/** The resource tags. */
export type GetDelegatedSubnetServiceDetailsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const GetDelegatedSubnetServiceDetailsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<GetDelegatedSubnetServiceDetailsResponseTagsMap>;

/** The current state of dnc delegated subnet resource. */
export type DelegatedSubnetPropertiesProvisioningState =
  | "Deleting"
  | "Succeeded"
  | "Failed"
  | "Provisioning";
export const DelegatedSubnetPropertiesProvisioningState =
  /*@__PURE__*/ S.String;

/** Properties of orchestrator */
export interface SubnetDetails {
  /** subnet arm resource id */
  id?: string;
}
export const SubnetDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "SubnetDetails" }) as any as S.Schema<SubnetDetails>;

/** controller details */
export type DelegatedSubnetPropertiesControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;
export const DelegatedSubnetPropertiesControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;

/** Properties of delegated subnet */
export interface DelegatedSubnetProperties {
  /** Resource guid. */
  resourceGuid?: string;
  /** The current state of dnc delegated subnet resource. */
  provisioningState?: DelegatedSubnetPropertiesProvisioningState;
  /** subnet details */
  subnetDetails?: SubnetDetails;
  /** controller details */
  controllerDetails?: OrchestratorResourcePropertiesInputControllerDetails;
}
export const DelegatedSubnetProperties = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    resourceGuid: S.optional(S.String),
    provisioningState: S.optional(DelegatedSubnetPropertiesProvisioningState),
    subnetDetails: S.optional(SubnetDetails),
    controllerDetails: S.optional(
      OrchestratorResourcePropertiesInputControllerDetails,
    ),
  }),
).annotate({
  identifier: "DelegatedSubnetProperties",
}) as any as S.Schema<DelegatedSubnetProperties>;

export interface GetDelegatedSubnetServiceDetailsResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: GetDelegatedSubnetServiceDetailsResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedSubnetProperties;
}
export const GetDelegatedSubnetServiceDetailsResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      tags: S.optional(GetDelegatedSubnetServiceDetailsResponseTagsMap),
      properties: S.optional(DelegatedSubnetProperties),
    }),
).annotate({
  identifier: "GetDelegatedSubnetServiceDetailsResponse",
}) as any as S.Schema<GetDelegatedSubnetServiceDetailsResponse>;

export interface GetOrchestratorInstanceServiceDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
}
export const GetOrchestratorInstanceServiceDetailsRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/orchestrators/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "GetOrchestratorInstanceServiceDetailsRequest",
  }) as any as S.Schema<GetOrchestratorInstanceServiceDetailsRequest>;

/** The kind of workbook. Choices are user and shared. */
export type GetOrchestratorInstanceServiceDetailsResponseKind = "Kubernetes";
export const GetOrchestratorInstanceServiceDetailsResponseKind =
  /*@__PURE__*/ S.String;

/** The resource tags. */
export type GetOrchestratorInstanceServiceDetailsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const GetOrchestratorInstanceServiceDetailsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<GetOrchestratorInstanceServiceDetailsResponseTagsMap>;

export interface GetOrchestratorInstanceServiceDetailsResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The kind of workbook. Choices are user and shared. */
  kind: GetOrchestratorInstanceServiceDetailsResponseKind;
  /** The identity of the orchestrator */
  identity?: OrchestratorIdentity;
  /** The resource tags. */
  tags?: GetOrchestratorInstanceServiceDetailsResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: OrchestratorResourceProperties;
}
export const GetOrchestratorInstanceServiceDetailsResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      kind: GetOrchestratorInstanceServiceDetailsResponseKind,
      identity: S.optional(OrchestratorIdentity),
      tags: S.optional(GetOrchestratorInstanceServiceDetailsResponseTagsMap),
      properties: S.optional(OrchestratorResourceProperties),
    }),
  ).annotate({
    identifier: "GetOrchestratorInstanceServiceDetailsResponse",
  }) as any as S.Schema<GetOrchestratorInstanceServiceDetailsResponse>;

export interface ListDelegatedNetworkByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListDelegatedNetworkByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/controllers",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListDelegatedNetworkByResourceGroupRequest",
  }) as any as S.Schema<ListDelegatedNetworkByResourceGroupRequest>;

/** The resource tags. */
export type DelegatedControllerTagsMap = { [key: string]: string | undefined };
export const DelegatedControllerTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<DelegatedControllerTagsMap>;

/** Represents an instance of a DNC controller. */
export interface DelegatedController {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: DelegatedControllerTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedControllerProperties;
}
export const DelegatedController = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    tags: S.optional(DelegatedControllerTagsMap),
    properties: S.optional(DelegatedControllerProperties),
  }),
).annotate({
  identifier: "DelegatedController",
}) as any as S.Schema<DelegatedController>;

/** An array of Delegated controller resources. */
export type DelegatedControllersValueList = Array<DelegatedController>;
export const DelegatedControllersValueList = /*@__PURE__*/ S.Array(
  DelegatedController,
) as any as S.Schema<DelegatedControllersValueList>;

/** An array of Delegated controller resources. */
export interface DelegatedControllers {
  /** An array of Delegated controller resources. */
  value: DelegatedControllersValueList;
  /** The URL to get the next set of controllers. */
  nextLink?: string;
}
export const DelegatedControllers = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: DelegatedControllersValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "DelegatedControllers",
}) as any as S.Schema<DelegatedControllers>;

export interface ListDelegatedNetworkBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListDelegatedNetworkBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.DelegatedNetwork/controllers",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListDelegatedNetworkBySubscriptionRequest",
  }) as any as S.Schema<ListDelegatedNetworkBySubscriptionRequest>;

export interface ListDelegatedSubnetServiceByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListDelegatedSubnetServiceByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/delegatedSubnets",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListDelegatedSubnetServiceByResourceGroupRequest",
  }) as any as S.Schema<ListDelegatedSubnetServiceByResourceGroupRequest>;

/** The resource tags. */
export type DelegatedSubnetTagsMap = { [key: string]: string | undefined };
export const DelegatedSubnetTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<DelegatedSubnetTagsMap>;

/** Represents an instance of a orchestrator. */
export interface DelegatedSubnet {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: DelegatedSubnetTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedSubnetProperties;
}
export const DelegatedSubnet = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    tags: S.optional(DelegatedSubnetTagsMap),
    properties: S.optional(DelegatedSubnetProperties),
  }),
).annotate({
  identifier: "DelegatedSubnet",
}) as any as S.Schema<DelegatedSubnet>;

/** An array of DelegatedSubnet resources. */
export type DelegatedSubnetsValueList = Array<DelegatedSubnet>;
export const DelegatedSubnetsValueList = /*@__PURE__*/ S.Array(
  DelegatedSubnet,
) as any as S.Schema<DelegatedSubnetsValueList>;

/** An array of DelegatedSubnet resources. */
export interface DelegatedSubnets {
  /** An array of DelegatedSubnet resources. */
  value: DelegatedSubnetsValueList;
  /** The URL to get the next set of DelegatedSubnet resources. */
  nextLink?: string;
}
export const DelegatedSubnets = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: DelegatedSubnetsValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "DelegatedSubnets",
}) as any as S.Schema<DelegatedSubnets>;

export interface ListDelegatedSubnetServiceBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListDelegatedSubnetServiceBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.DelegatedNetwork/delegatedSubnets",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListDelegatedSubnetServiceBySubscriptionRequest",
  }) as any as S.Schema<ListDelegatedSubnetServiceBySubscriptionRequest>;

export interface ListOperationsRequest {}
export const ListOperationsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "GET",
      uri: "/providers/Microsoft.DelegatedNetwork/operations",
      code: 200,
      apiVersion: "2021-03-15",
    }),
  ),
).annotate({
  identifier: "ListOperationsRequest",
}) as any as S.Schema<ListOperationsRequest>;

/** Localized display information for this particular operation. */
export interface OperationDisplay {
  /** The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute". */
  provider?: string;
  /** The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections". */
  resource?: string;
  /** The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine". */
  operation?: string;
  /** The short, localized friendly description of the operation; suitable for tool tips and detailed views. */
  description?: string;
}
export const OperationDisplay = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    provider: S.optional(S.String),
    resource: S.optional(S.String),
    operation: S.optional(S.String),
    description: S.optional(S.String),
  }),
).annotate({
  identifier: "OperationDisplay",
}) as any as S.Schema<OperationDisplay>;

/** The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system" */
export type OperationOrigin = "user" | "system" | "user,system";
export const OperationOrigin = /*@__PURE__*/ S.String;

/** Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. */
export type OperationActionType = "Internal";
export const OperationActionType = /*@__PURE__*/ S.String;

/** Details of a REST API operation, returned from the Resource Provider Operations API */
export interface Operation {
  /** The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action" */
  name?: string;
  /** Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for ARM/control-plane operations. */
  isDataAction?: boolean;
  /** Localized display information for this particular operation. */
  display?: OperationDisplay;
  /** The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system" */
  origin?: OperationOrigin;
  /** Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. */
  actionType?: OperationActionType;
}
export const Operation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    isDataAction: S.optional(S.Boolean),
    display: S.optional(OperationDisplay),
    origin: S.optional(OperationOrigin),
    actionType: S.optional(OperationActionType),
  }),
).annotate({ identifier: "Operation" }) as any as S.Schema<Operation>;

/** List of operations supported by the resource provider */
export type ListOperationsResponseValueList = Array<Operation>;
export const ListOperationsResponseValueList = /*@__PURE__*/ S.Array(
  Operation,
) as any as S.Schema<ListOperationsResponseValueList>;

export interface ListOperationsResponse {
  /** List of operations supported by the resource provider */
  value?: ListOperationsResponseValueList;
  /** URL to get the next set of operation list results (if there are any). */
  nextLink?: string;
}
export const ListOperationsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: S.optional(ListOperationsResponseValueList),
    nextLink: S.optional(S.String),
  }),
).annotate({
  identifier: "ListOperationsResponse",
}) as any as S.Schema<ListOperationsResponse>;

export interface ListOrchestratorInstanceServiceByResourceGroupRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
}
export const ListOrchestratorInstanceServiceByResourceGroupRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/orchestrators",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListOrchestratorInstanceServiceByResourceGroupRequest",
  }) as any as S.Schema<ListOrchestratorInstanceServiceByResourceGroupRequest>;

/** The kind of workbook. Choices are user and shared. */
export type OrchestratorKind = "Kubernetes";
export const OrchestratorKind = /*@__PURE__*/ S.String;

/** The resource tags. */
export type OrchestratorTagsMap = { [key: string]: string | undefined };
export const OrchestratorTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<OrchestratorTagsMap>;

/** Represents an instance of a orchestrator. */
export interface Orchestrator {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The kind of workbook. Choices are user and shared. */
  kind: OrchestratorKind;
  /** The identity of the orchestrator */
  identity?: OrchestratorIdentity;
  /** The resource tags. */
  tags?: OrchestratorTagsMap;
  /** Properties of the provision operation request. */
  properties?: OrchestratorResourceProperties;
}
export const Orchestrator = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    kind: OrchestratorKind,
    identity: S.optional(OrchestratorIdentity),
    tags: S.optional(OrchestratorTagsMap),
    properties: S.optional(OrchestratorResourceProperties),
  }),
).annotate({ identifier: "Orchestrator" }) as any as S.Schema<Orchestrator>;

/** An array of OrchestratorInstance resources. */
export type OrchestratorsValueList = Array<Orchestrator>;
export const OrchestratorsValueList = /*@__PURE__*/ S.Array(
  Orchestrator,
) as any as S.Schema<OrchestratorsValueList>;

/** An array of OrchestratorInstance resources. */
export interface Orchestrators {
  /** An array of OrchestratorInstance resources. */
  value: OrchestratorsValueList;
  /** The URL to get the next set of orchestrators. */
  nextLink?: string;
}
export const Orchestrators = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    value: OrchestratorsValueList,
    nextLink: S.optional(S.String),
  }),
).annotate({ identifier: "Orchestrators" }) as any as S.Schema<Orchestrators>;

export interface ListOrchestratorInstanceServiceBySubscriptionRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
}
export const ListOrchestratorInstanceServiceBySubscriptionRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
    }).pipe(
      T.Http({
        method: "GET",
        uri: "/subscriptions/{subscriptionId}/providers/Microsoft.DelegatedNetwork/orchestrators",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "ListOrchestratorInstanceServiceBySubscriptionRequest",
  }) as any as S.Schema<ListOrchestratorInstanceServiceBySubscriptionRequest>;

/** The resource tags. */
export type PatchControllerRequestTagsMap = {
  [key: string]: string | undefined;
};
export const PatchControllerRequestTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<PatchControllerRequestTagsMap>;

export interface PatchControllerRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** The resource tags. */
  tags?: PatchControllerRequestTagsMap;
}
export const PatchControllerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subscriptionId: S.String.pipe(T.Label()),
    resourceGroupName: S.String.pipe(T.Label()),
    resourceName: S.String.pipe(T.Label()),
    tags: S.optional(PatchControllerRequestTagsMap),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/controller/{resourceName}",
      code: 200,
      apiVersion: "2021-03-15",
    }),
  ),
).annotate({
  identifier: "PatchControllerRequest",
}) as any as S.Schema<PatchControllerRequest>;

/** The resource tags. */
export type PatchControllerResponseTagsMap = {
  [key: string]: string | undefined;
};
export const PatchControllerResponseTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<PatchControllerResponseTagsMap>;

export interface PatchControllerResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: PatchControllerResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedControllerProperties;
}
export const PatchControllerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    type: S.optional(S.String),
    location: S.optional(S.String),
    tags: S.optional(PatchControllerResponseTagsMap),
    properties: S.optional(DelegatedControllerProperties),
  }),
).annotate({
  identifier: "PatchControllerResponse",
}) as any as S.Schema<PatchControllerResponse>;

/** The resource tags. */
export type PatchDelegatedSubnetServiceDetailsRequestTagsMap = {
  [key: string]: string | undefined;
};
export const PatchDelegatedSubnetServiceDetailsRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PatchDelegatedSubnetServiceDetailsRequestTagsMap>;

export interface PatchDelegatedSubnetServiceDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** The resource tags. */
  tags?: PatchDelegatedSubnetServiceDetailsRequestTagsMap;
}
export const PatchDelegatedSubnetServiceDetailsRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      tags: S.optional(PatchDelegatedSubnetServiceDetailsRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/delegatedSubnets/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
  ).annotate({
    identifier: "PatchDelegatedSubnetServiceDetailsRequest",
  }) as any as S.Schema<PatchDelegatedSubnetServiceDetailsRequest>;

/** The resource tags. */
export type PatchDelegatedSubnetServiceDetailsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const PatchDelegatedSubnetServiceDetailsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PatchDelegatedSubnetServiceDetailsResponseTagsMap>;

export interface PatchDelegatedSubnetServiceDetailsResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: PatchDelegatedSubnetServiceDetailsResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedSubnetProperties;
}
export const PatchDelegatedSubnetServiceDetailsResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      tags: S.optional(PatchDelegatedSubnetServiceDetailsResponseTagsMap),
      properties: S.optional(DelegatedSubnetProperties),
    }),
  ).annotate({
    identifier: "PatchDelegatedSubnetServiceDetailsResponse",
  }) as any as S.Schema<PatchDelegatedSubnetServiceDetailsResponse>;

/** The resource tags. */
export type PatchOrchestratorInstanceServiceRequestTagsMap = {
  [key: string]: string | undefined;
};
export const PatchOrchestratorInstanceServiceRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PatchOrchestratorInstanceServiceRequestTagsMap>;

export interface PatchOrchestratorInstanceServiceRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** The resource tags. */
  tags?: PatchOrchestratorInstanceServiceRequestTagsMap;
}
export const PatchOrchestratorInstanceServiceRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      tags: S.optional(PatchOrchestratorInstanceServiceRequestTagsMap),
    }).pipe(
      T.Http({
        method: "PATCH",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/orchestrators/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
).annotate({
  identifier: "PatchOrchestratorInstanceServiceRequest",
}) as any as S.Schema<PatchOrchestratorInstanceServiceRequest>;

/** The kind of workbook. Choices are user and shared. */
export type PatchOrchestratorInstanceServiceResponseKind = "Kubernetes";
export const PatchOrchestratorInstanceServiceResponseKind =
  /*@__PURE__*/ S.String;

/** The resource tags. */
export type PatchOrchestratorInstanceServiceResponseTagsMap = {
  [key: string]: string | undefined;
};
export const PatchOrchestratorInstanceServiceResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PatchOrchestratorInstanceServiceResponseTagsMap>;

export interface PatchOrchestratorInstanceServiceResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The kind of workbook. Choices are user and shared. */
  kind: PatchOrchestratorInstanceServiceResponseKind;
  /** The identity of the orchestrator */
  identity?: OrchestratorIdentity;
  /** The resource tags. */
  tags?: PatchOrchestratorInstanceServiceResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: OrchestratorResourceProperties;
}
export const PatchOrchestratorInstanceServiceResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      kind: PatchOrchestratorInstanceServiceResponseKind,
      identity: S.optional(OrchestratorIdentity),
      tags: S.optional(PatchOrchestratorInstanceServiceResponseTagsMap),
      properties: S.optional(OrchestratorResourceProperties),
    }),
).annotate({
  identifier: "PatchOrchestratorInstanceServiceResponse",
}) as any as S.Schema<PatchOrchestratorInstanceServiceResponse>;

/** The resource tags. */
export type PutDelegatedSubnetServiceDetailsRequestTagsMap = {
  [key: string]: string | undefined;
};
export const PutDelegatedSubnetServiceDetailsRequestTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PutDelegatedSubnetServiceDetailsRequestTagsMap>;

/** controller details */
export type DelegatedSubnetPropertiesInputControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;
export const DelegatedSubnetPropertiesInputControllerDetails =
  OrchestratorResourcePropertiesInputControllerDetails;

/** Properties of delegated subnet */
export interface DelegatedSubnetPropertiesInput {
  /** subnet details */
  subnetDetails?: SubnetDetails;
  /** controller details */
  controllerDetails?: OrchestratorResourcePropertiesInputControllerDetails;
}
export const DelegatedSubnetPropertiesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    subnetDetails: S.optional(SubnetDetails),
    controllerDetails: S.optional(
      OrchestratorResourcePropertiesInputControllerDetails,
    ),
  }),
).annotate({
  identifier: "DelegatedSubnetPropertiesInput",
}) as any as S.Schema<DelegatedSubnetPropertiesInput>;

export interface PutDelegatedSubnetServiceDetailsRequest {
  /** The ID of the target subscription. */
  subscriptionId: string;
  /** The name of the resource group. The name is case insensitive. */
  resourceGroupName: string;
  /** The name of the resource. It must be a minimum of 3 characters, and a maximum of 63. */
  resourceName: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: PutDelegatedSubnetServiceDetailsRequestTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedSubnetPropertiesInput;
}
export const PutDelegatedSubnetServiceDetailsRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      subscriptionId: S.String.pipe(T.Label()),
      resourceGroupName: S.String.pipe(T.Label()),
      resourceName: S.String.pipe(T.Label()),
      location: S.optional(S.String),
      tags: S.optional(PutDelegatedSubnetServiceDetailsRequestTagsMap),
      properties: S.optional(DelegatedSubnetPropertiesInput),
    }).pipe(
      T.Http({
        method: "PUT",
        uri: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DelegatedNetwork/delegatedSubnets/{resourceName}",
        code: 200,
        apiVersion: "2021-03-15",
      }),
    ),
).annotate({
  identifier: "PutDelegatedSubnetServiceDetailsRequest",
}) as any as S.Schema<PutDelegatedSubnetServiceDetailsRequest>;

/** The resource tags. */
export type PutDelegatedSubnetServiceDetailsResponseTagsMap = {
  [key: string]: string | undefined;
};
export const PutDelegatedSubnetServiceDetailsResponseTagsMap =
  /*@__PURE__*/ S.Record(
    S.String,
    S.String,
  ) as any as S.Schema<PutDelegatedSubnetServiceDetailsResponseTagsMap>;

export interface PutDelegatedSubnetServiceDetailsResponse {
  /** An identifier that represents the resource. */
  id?: string;
  /** The name of the resource. */
  name?: string;
  /** The type of resource. */
  type?: string;
  /** Location of the resource. */
  location?: string;
  /** The resource tags. */
  tags?: PutDelegatedSubnetServiceDetailsResponseTagsMap;
  /** Properties of the provision operation request. */
  properties?: DelegatedSubnetProperties;
}
export const PutDelegatedSubnetServiceDetailsResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      id: S.optional(S.String),
      name: S.optional(S.String),
      type: S.optional(S.String),
      location: S.optional(S.String),
      tags: S.optional(PutDelegatedSubnetServiceDetailsResponseTagsMap),
      properties: S.optional(DelegatedSubnetProperties),
    }),
).annotate({
  identifier: "PutDelegatedSubnetServiceDetailsResponse",
}) as any as S.Schema<PutDelegatedSubnetServiceDetailsResponse>;

export type CreateControllerError = AzureOpError;
/** Create a dnc controller */
export const CreateController: API.OperationMethod<
  CreateControllerRequest,
  CreateControllerResponse,
  CreateControllerError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateControllerRequest,
  output: CreateControllerResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type CreateOrchestratorInstanceServiceError = AzureOpError;
/** Create a orchestrator instance */
export const CreateOrchestratorInstanceService: API.OperationMethod<
  CreateOrchestratorInstanceServiceRequest,
  CreateOrchestratorInstanceServiceResponse,
  CreateOrchestratorInstanceServiceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateOrchestratorInstanceServiceRequest,
  output: CreateOrchestratorInstanceServiceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteControllerError = AzureOpError;
/** Deletes the DNC controller */
export const DeleteController: API.OperationMethod<
  DeleteControllerRequest,
  DeleteControllerResponse,
  DeleteControllerError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteControllerRequest,
  output: DeleteControllerResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteDelegatedSubnetServiceDetailsError = AzureOpError;
/** Delete dnc DelegatedSubnet. */
export const DeleteDelegatedSubnetServiceDetails: API.OperationMethod<
  DeleteDelegatedSubnetServiceDetailsRequest,
  DeleteDelegatedSubnetServiceDetailsResponse,
  DeleteDelegatedSubnetServiceDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteDelegatedSubnetServiceDetailsRequest,
  output: DeleteDelegatedSubnetServiceDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type DeleteOrchestratorInstanceServiceError = AzureOpError;
/** Deletes the Orchestrator Instance */
export const DeleteOrchestratorInstanceService: API.OperationMethod<
  DeleteOrchestratorInstanceServiceRequest,
  DeleteOrchestratorInstanceServiceResponse,
  DeleteOrchestratorInstanceServiceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteOrchestratorInstanceServiceRequest,
  output: DeleteOrchestratorInstanceServiceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetControllerDetailsError = AzureOpError;
/** Gets details about the specified dnc controller. */
export const GetControllerDetails: API.OperationMethod<
  GetControllerDetailsRequest,
  GetControllerDetailsResponse,
  GetControllerDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetControllerDetailsRequest,
  output: GetControllerDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetDelegatedSubnetServiceDetailsError = AzureOpError;
/** Gets details about the specified dnc DelegatedSubnet Link. */
export const GetDelegatedSubnetServiceDetails: API.OperationMethod<
  GetDelegatedSubnetServiceDetailsRequest,
  GetDelegatedSubnetServiceDetailsResponse,
  GetDelegatedSubnetServiceDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetDelegatedSubnetServiceDetailsRequest,
  output: GetDelegatedSubnetServiceDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type GetOrchestratorInstanceServiceDetailsError = AzureOpError;
/** Gets details about the orchestrator instance. */
export const GetOrchestratorInstanceServiceDetails: API.OperationMethod<
  GetOrchestratorInstanceServiceDetailsRequest,
  GetOrchestratorInstanceServiceDetailsResponse,
  GetOrchestratorInstanceServiceDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOrchestratorInstanceServiceDetailsRequest,
  output: GetOrchestratorInstanceServiceDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListDelegatedNetworkByResourceGroupError = AzureOpError;
/** Get all the delegatedController resources in a resource group. */
export const ListDelegatedNetworkByResourceGroup: API.OperationMethod<
  ListDelegatedNetworkByResourceGroupRequest,
  DelegatedControllers,
  ListDelegatedNetworkByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDelegatedNetworkByResourceGroupRequest,
  output: DelegatedControllers,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListDelegatedNetworkBySubscriptionError = AzureOpError;
/** Get all the delegatedController resources in a subscription. */
export const ListDelegatedNetworkBySubscription: API.OperationMethod<
  ListDelegatedNetworkBySubscriptionRequest,
  DelegatedControllers,
  ListDelegatedNetworkBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDelegatedNetworkBySubscriptionRequest,
  output: DelegatedControllers,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListDelegatedSubnetServiceByResourceGroupError = AzureOpError;
/** Get all the DelegatedSubnets resources in a resource group. */
export const ListDelegatedSubnetServiceByResourceGroup: API.OperationMethod<
  ListDelegatedSubnetServiceByResourceGroupRequest,
  DelegatedSubnets,
  ListDelegatedSubnetServiceByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDelegatedSubnetServiceByResourceGroupRequest,
  output: DelegatedSubnets,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListDelegatedSubnetServiceBySubscriptionError = AzureOpError;
/** Get all the DelegatedSubnets resources in a subscription. */
export const ListDelegatedSubnetServiceBySubscription: API.OperationMethod<
  ListDelegatedSubnetServiceBySubscriptionRequest,
  DelegatedSubnets,
  ListDelegatedSubnetServiceBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDelegatedSubnetServiceBySubscriptionRequest,
  output: DelegatedSubnets,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListOperationsError = AzureOpError;
/** Lists all of the available DelegatedNetwork service REST API operations. */
export const ListOperations: API.OperationMethod<
  ListOperationsRequest,
  ListOperationsResponse,
  ListOperationsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListOperationsRequest,
  output: ListOperationsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListOrchestratorInstanceServiceByResourceGroupError = AzureOpError;
/** Get all the OrchestratorInstances resources in a resource group. */
export const ListOrchestratorInstanceServiceByResourceGroup: API.OperationMethod<
  ListOrchestratorInstanceServiceByResourceGroupRequest,
  Orchestrators,
  ListOrchestratorInstanceServiceByResourceGroupError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListOrchestratorInstanceServiceByResourceGroupRequest,
  output: Orchestrators,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type ListOrchestratorInstanceServiceBySubscriptionError = AzureOpError;
/** Get all the orchestratorInstance resources in a subscription. */
export const ListOrchestratorInstanceServiceBySubscription: API.OperationMethod<
  ListOrchestratorInstanceServiceBySubscriptionRequest,
  Orchestrators,
  ListOrchestratorInstanceServiceBySubscriptionError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListOrchestratorInstanceServiceBySubscriptionRequest,
  output: Orchestrators,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type PatchControllerError = AzureOpError;
/** Update dnc controller */
export const PatchController: API.OperationMethod<
  PatchControllerRequest,
  PatchControllerResponse,
  PatchControllerError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PatchControllerRequest,
  output: PatchControllerResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type PatchDelegatedSubnetServiceDetailsError = AzureOpError;
/** Patch delegated subnet resource */
export const PatchDelegatedSubnetServiceDetails: API.OperationMethod<
  PatchDelegatedSubnetServiceDetailsRequest,
  PatchDelegatedSubnetServiceDetailsResponse,
  PatchDelegatedSubnetServiceDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PatchDelegatedSubnetServiceDetailsRequest,
  output: PatchDelegatedSubnetServiceDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type PatchOrchestratorInstanceServiceError = AzureOpError;
/** Update Orchestrator Instance */
export const PatchOrchestratorInstanceService: API.OperationMethod<
  PatchOrchestratorInstanceServiceRequest,
  PatchOrchestratorInstanceServiceResponse,
  PatchOrchestratorInstanceServiceError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PatchOrchestratorInstanceServiceRequest,
  output: PatchOrchestratorInstanceServiceResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));

export type PutDelegatedSubnetServiceDetailsError = AzureOpError;
/** Put delegated subnet resource */
export const PutDelegatedSubnetServiceDetails: API.OperationMethod<
  PutDelegatedSubnetServiceDetailsRequest,
  PutDelegatedSubnetServiceDetailsResponse,
  PutDelegatedSubnetServiceDetailsError,
  AzureOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutDelegatedSubnetServiceDetailsRequest,
  output: PutDelegatedSubnetServiceDetailsResponse,
  errors: [UnknownAzureError],
  protocol: AzureProtocol,
  retry: Retry.Retry,
}));
